### ISSUE TITLE
[Homework 1] parallel web server with cache (due: 2021-09-26T23:59:59+0900)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#345]
Implement a parallel web server with cache.

- Read [this manual](https://github.com/kaist-cp/cs431/tree/main/homework/src/hello_server) for general advice on homework. The manual contains skeleton code that serves as a starting point. You're going to fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- You can grade your solution yourself by running `./script/grade-1.sh` in the `homework` directory. If the server's evaluation results differ from your own evaluation results, please let me know.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/33/). You can submit as follows:

  ```sh
  cd cs492-concur/homework
  ./scripts/submit.sh
  ls ./target/hw1.zip     # file to submit
  ```

- **IMPORTANT**: only the last submission counts.  Please make sure the last line of the "log" says "Score: ?? / ??".

**Comment by jeehoonkang** [comment]
## Reading Rust book
This homework requires a good understanding of materials covered in Rust book §20. This is the minimal path for understanding §20: §1, 2, 3, 4, 5, 6, 8, 9, 10, 13.1, 13.2, **15**, **16**, **20**.

Specifically, make sure that you understand following topics.
* [`Drop`](https://doc.rust-lang.org/std/ops/trait.Drop.html) trait and [`drop`](https://doc.rust-lang.org/std/mem/fn.drop.html) function
* Type signature of [`std::thread::spawn`](https://doc.rust-lang.org/std/thread/fn.spawn.html) and the meaning of [`std::thread::JoinHandle`](https://doc.rust-lang.org/std/thread/struct.JoinHandle.html).
* The meaning and usage of [`Arc<`](https://doc.rust-lang.org/std/sync/struct.Arc.html)[`Mutex<T>>`](https://doc.rust-lang.org/std/sync/struct.Mutex.html).
* [Channels](https://doc.rust-lang.org/std/sync/mpsc/index.html).


## Major differences between HW1 and Rust book §20
1. We use [`crossbeam_channel`](https://docs.rs/crossbeam-channel/) instead of [`std::sync::mpsc`](https://doc.rust-lang.org/std/sync/mpsc/index.html). Since crossbeam channel is mpmc, you don't need to wrap the `Receiver` inside a `Mutex`.
2. We do not use explicit exit message for thread pool. Instead, we disconnect the channel by `drop`ping the receiver/sender.
    * The message type is simply defined as:
      ```rust
      struct Job(Box<dyn FnOnce() + Send + 'static>);

      ```
    * Each worker thread automatically breaks out of the loop if the channel is disconnected.
3. We `join()` each thread in the destructor of `Worker`, not in the destructor of `ThreadPool`. Since `ThreadPool` has field `workers: Vec<Worker>`, the worker destructor will be called when the pool is dropped. Note that the channel should be disconnected before `join()`ning the worker threads. (Otherwise, `join` will block.) This means that the `Sender` should be dropped before `Vec<Worker>`. You can specify the drop order in many ways. In this homework, we use `ThreadPool::job_sender` of type `Option<Sender<Job>>`, content of which can be `take()`n and `drop()`ped explicitly in `<ThreadPool as Drop>::drop`.

## Tips for implementing each extension
* Cache: Start with `Mutex<HashMap<K, V>>`. To fully implement the specification, you will need a more complicated type.
* Interrupt handler: just follow the comments.
* Thread pool: Ignore `ThreadPoolInner` first (used for `ThreadPool::join`), and implement the changes discussed in the previous section.

## Testing
I just added some tests for homework 1. To run the tests, run
```
cargo test hello_server
```
We will use those tests for grading, too. We may add some more tests for grading, but if your solution passes all the given tests, it's very likely that you will get the full score.

Also try running tests with the [LLVM sanitizers](https://github.com/kaist-cp/cs492-concur/tree/master/homework#using-llvm-sanitizers) enabled. 
```
RUSTFLAGS="-Z sanitizer=address" cargo +nightly test hello_server --target x86_64-unknown-linux-gnu
TSAN_OPTIONS="suppressions=suppress_tsan.txt" RUST_TEST_THREADS=1 RUSTFLAGS="-Z sanitizer=thread" cargo +nightly test hello_server --target x86_64-unknown-linux-gnu
```
They are not that useful for HW1 but they will be very helpful for upcoming homeworks.

## Some changes in the specification
See <https://github.com/kaist-cp/cs492-concur/commit/85722fd5f1a5e5383e370e7feeebbb91192aff35#diff-1db87cfba2d093beedfd2fcf93408fefR20-R21>.  This change is for [this test function](https://github.com/kaist-cp/cs492-concur/blob/36e06f05caac461974a216a7e377b001ee3de44b/homework/src/hello_server/thread_pool.rs#L153).  If you're already running `.join().unwrap()` on the thread join handle, you probably won't need to fix your code.

**Comment by tomtomjhj** [comment]
Updated the manual and tests. https://github.com/kaist-cp/cs431/commit/0246ff96d2dee2fad884f97b8682026fd3f7b963

**Comment by jeehoonkang** [comment]
Now you may submit your solution as instructed in the issue.

**Comment by yj-han** [comment]
@jeehoonkang It would be great if `zip` package is installed in our project server. 🙂

**Comment by tomtomjhj** [comment]
Installed `zip` and `unzip` in the server.

**Comment by kimjungwow** [comment]
To be clear, the score in gg.kaist.ac.kr submission log will be my score? (meaning there is no hidden testcase)

**Comment by tomtomjhj** [comment]
Yes. But we may (very unlikely) add some more tests or change the grading scheme, if the deadline is not too close (less than 1 week left). In that case, we'll announce in each homework announcement issue.
