### ISSUE TITLE
[Question] How to install rustup

### ISSUE THREAD

**Issue by bronte000** [kaist-cp/cs431#349]
Summarize: I couldn't follow the instructions of the video. So, I don't have rustup. How can I download it?

I watched the video (https://www.youtube.com/watch?v=TTVuUIhdn_g&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=4) but couldn't follow the instruction.
First of all, my visual studio has no Rust(rls) extension. So, I just installed Rust(the first one) and code LLDB.

![image](https://user-images.githubusercontent.com/48073703/131787786-be4f04e4-1cae-498a-9e19-5eee79bbf081.png)

Then, there was no Rust:cargo.
I tried to start rust server but it failed with error message: Rustup not available.
![image](https://user-images.githubusercontent.com/48073703/131788378-a37bb00e-8bcd-4779-a735-559eef818f25.png)
![image](https://user-images.githubusercontent.com/48073703/131788509-107f4401-69c2-4d67-bd5f-33893b0d21af.png)

I found the issue dealing with exactly same problem https://github.com/kaist-cp/cs431/issues/48#issuecomment-685866756
and realized that I don't have ~/.cargo/bin/rustup.
But I don't know how to download it.
I referred to rust textbook https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html and tried to install with curl instruction, but curl was not available, with error message "bash: curl: command not found". So I tried to install curl command, but it was impossible because I was not in home directory.

How can I download rustup and run Rust code?

**Comment by jeehoonkang** [comment]
I just installed `curl`. If you need any packages, please let us know.

**Comment by jeehoonkang** [comment]
One more thing: we now recommend Rust Analyzer instead of Rust(rls).
