### ISSUE TITLE
How to download lecture videos? (instructions here)

### ISSUE THREAD

**Issue by jessyoon14** [kaist-cp/cs431#352]
Where may we find the recorded lecture for today's class?

**Comment by jeehoonkang** [comment]
Only the first week's videos will be uploaded somewhere. Today's video won't be available, but you can watch previous semester's videos because the content doesn't change a lot.

**Comment by jeehoonkang** [comment]
- You can download the recording for the first session here: https://klms.kaist.ac.kr/mod/courseboard/article.php?id=576413&bid=72724&bwid=249744
- The later lectures have almost the same content as previous semesters, so please watch YouTube videos instead.

**Comment by drzix** [comment]
I've added the instructions above into [README.md](https://github.com/kaist-cp/cs431#online-sessions).

**Comment by vilotgit** [comment]
Would you upload this Wednesday's lecture (9/8) please?
I recall the professor saying he'll upload the lecture because Wednesday's lecture was very different from last year's.
