### ISSUE TITLE
Quiz announcements

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#354]
From now on, all the quizzes are announced as a reply to this issue.

**Comment by jeehoonkang** [comment]
2021/09/06: https://gg.kaist.ac.kr/quiz/74/

**Comment by jeehoonkang** [comment]
2021/09/08: https://gg.kaist.ac.kr/quiz/76/

**Comment by jeehoonkang** [comment]
2021/09/13: https://gg.kaist.ac.kr/quiz/78/

**Comment by jeehoonkang** [comment]
2021/09/15: https://gg.kaist.ac.kr/quiz/80/

**Comment by jeehoonkang** [comment]
2021/09/29: https://gg.kaist.ac.kr/quiz/83/

**Comment by jeehoonkang** [comment]
2021/10/06: https://gg.kaist.ac.kr/quiz/85/

**Comment by jeehoonkang** [comment]
2021/11/01: https://gg.kaist.ac.kr/quiz/91/

**Comment by kimjungwow** [comment]
Is there no quiz today? @jeehoonkang

**Comment by jeehoonkang** [comment]
2021/11/08: https://gg.kaist.ac.kr/quiz/94/

**Comment by jeehoonkang** [comment]
2021/11/10: https://gg.kaist.ac.kr/quiz/96/

**Comment by Gyubin-Lee** [comment]
> 2021/11/10: https://gg.kaist.ac.kr/quiz/96/

Is there any problem with gg server? I cannot access to the quiz

**Comment by jeehoonkang** [comment]
2021/11/22: https://gg.kaist.ac.kr/quiz/100/

**Comment by jeehoonkang** [comment]
@Gyubin-Lee it seems it's working now. if the problem continues to exist, please create a new issue.

**Comment by jeehoonkang** [comment]
- 2021/11/24: https://gg.kaist.ac.kr/quiz/102/
- video: https://www.youtube.com/watch?v=1GjSfyijaxo
