### ISSUE TITLE
[Question] May we make multiple attempts at attendance quizzes?

### ISSUE THREAD

**Issue by jessyoon14** [kaist-cp/cs431#355]
Are multiple attempts allowed for attendance quizzes?
I would like to change my submitted answer to something else, but the website does not let me edit the response.

**Comment by kimjungwow** [comment]
It seems you can't submit with wrong answer. 

![image](https://user-images.githubusercontent.com/20202266/132159378-e7d39a33-a5cd-45e9-8f79-f3978a22e83f.png)

**Comment by jeehoonkang** [comment]
you can try as much times as you wish. as @kimjungwow says, if you don't get the right answer, gg will reject your answer and let you try again.
