### ISSUE TITLE
[Question] QUIZ SUBMISSION

### ISSUE THREAD

**Issue by vm3fk5dla2** [kaist-cp/cs431#356]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

(YOUR QUESTION HERE)
What should I do if I don't know the answer to today's attendance quiz?

I'm asking because Wrong answer has not been submitted.

Thank you.

**Comment by jeehoonkang** [comment]
@vm3fk5dla2 you can ask course materials here, which happen to be related to the quiz.
