### ISSUE TITLE
[Question] Quiz due util 14:59:59 or 23:59:59. Which time is correct?

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs431#358]
When you're asking a question, please make sure:

- [x] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

On gg.kaist.ac.kr/course/9 , the quiz due is until 23:59:59 like this photo
![image](https://user-images.githubusercontent.com/22411406/132512903-40abe9f9-f83a-4906-b37b-130a0d24df56.png)
But on quiz, it says the due is until 14:59:59.
![image](https://user-images.githubusercontent.com/22411406/132513042-175cb115-5137-430c-aeae-09f7c9b71e3a.png)
So I wonder which is actually correct due.
Also i think i submitted the 9/6 quiz on 4pm. Is this could be allowed?
Thank you.

Now I noticed that 14:59:59 may be GMT, and 23:59:59 may be KST so actually the quiz due is until 23:59:59 KST i think.
Is this correct?

**Comment by kimjungwow** [comment]
In the lecture (9/8), professor explained that we don't need to worry about 14:59:59, and all quizes' due are 23:59:59.

**Comment by junsooo** [comment]
Thank you. I vaccinated today(9/8) so i didn't listen it
