### ISSUE TITLE
[Question] HW1 Does threadpool join function work well even if some threads occur pannic?

### ISSUE THREAD

**Issue by bronte000** [kaist-cp/cs431#359]
When you're asking a question, please make sure:

- [x] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [x] You read the corresponding sections of the slide.
    + [x] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I had difficulty with passing thread_pool_drop_propagate_panic test.
Now I solved the problem referring to this issue. https://github.com/kaist-cp/cs431/issues/79#issue-705415315
But I still don't know why it works..

If we should not wait for all threads to be finished in drop function-because we cannot catch pannic-, is it okay for threadpool join function? threadpool::join should wait until all the jobs are done. What happens if some job occurs pannic?

I don't understand what 
""If the 00 panics, then this function should panic too."" this sentence means...
I thought if pannic occurs -> system will be immediately stopped.
Should we do some extra job to guarantee that?

**Comment by kohs100** [comment]
I thought panic only affects the context in which the code is running, the thread. When a parent thread attempts to join the JoinHandle of a particular child thread, if that thread panicked and became a zombie, the returned Option of the JoinHandle::join() method will be None, so unwrapping that Option will help you to get the desired result.

And Threadpool::join does not seem to assume a case in which a job causes a panic is executed. There is no test to check this case, and the ThreadpoolInner::wait_empty() method does not have the ability to notice about the thread panicked.

**Comment by tomtomjhj** [comment]
@kohs100 is right. Thanks for the great answer.

**Comment by bronte000** [comment]
@kohs100  
I understand.
So, that's the reason why we should use unwrap() when we use join for child thread.
And, Threadpool::join is not able to deal with panck. Right?

Thank you for your nice answer.

**Comment by tomtomjhj** [comment]
> Threadpool::join is not able to deal with panck.

`Threadpool::join` can do some more work to deal with the panic. For example, it can spawn more threads to ensure that there is an enough number of live threads.

 But in order to keep the homework simple, we won't require such sophisticated panic handling and instead require the simplest possible solution (propagating the panic).
