### ISSUE TITLE
[Question] Cannot connect to cs431 server.

### ISSUE THREAD

**Issue by Oh-yk** [kaist-cp/cs431#364]
Last time I checked that I was connected to the cs431 server and set a password.
Now, when I try to connect again through Visual Studio Code, I can't connect.

Could not establish connection to "cs431".
Could not establish connection to "cs431": The operation timed out.
These are the error messages.

I think it is because I forgot to register the SSH key. Can you please check it?
Could you please allow me to connect?

**Comment by bronte000** [comment]
Actually I can't connect to the server with ssh key, either.
Is there any server issue?

**Comment by GrasshopperBears** [comment]
I think it works now

**Comment by Oh-yk** [comment]
Thank you. It works.
