### ISSUE TITLE
[Question] This Wednesday's video

### ISSUE THREAD

**Issue by Mins0o** [kaist-cp/cs431#365]
When you're asking a question, please make sure:

- [x] You clarify your questions as clear as possible.  If possible, please make it a **yes/no** question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- ~If you're asking a question on concepts:~
    + [ ] ~You read the corresponding sections of the slide.~
    + [ ] ~You searched for the concepts using search engines and Wikipedia.~

- ~If you're asking a question on Rust programming:~
    + [ ] ~You searched for error messages or any relevant logs using search engines.~
    + [ ] ~Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.~
    + [ ] ~You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.~
    + [ ] ~You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.~

--

I was waiting for the video of the Sep.15 lecture,  
but I may have missed another announcement of canceling the upload.

### Q. Is the video going to be uploaded? (Y/N)

Sorry for hurrying, I thought it was better to mention it before the holidays start.

**Comment by jeehoonkang** [comment]
I don't recall so asking: I wonder if I promised to share the video.

**Comment by Mins0o** [comment]
Maybe I have mistaken. Sorry for the disturbance.
