### ISSUE TITLE
Non-realtime session on Sep 27 (Mon)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#366]
- I'm on leave on Sep 27 (Mon), so I won't be able to give a real-time lecture. Sorry.
- Instead, I'll upload a lecture video to the usual place and notify you with a reply to this issue.

**Comment by GrasshopperBears** [comment]
Do we still have quiz on that session?

**Comment by jeehoonkang** [comment]
@GrasshopperBears No. non-realtime sessions will not have quizzes.

**Comment by jeehoonkang** [comment]
For Sep 27, please watch the following videos:
- https://www.youtube.com/watch?v=uuHHMQgv_9s&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4 (somewhat overlapped with the previous sessions)
- https://www.youtube.com/watch?v=Pccs-JhZBQE&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4
- https://www.youtube.com/watch?v=noQOMI1LnNc&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4
