### ISSUE TITLE
[Homework 2] Linked List (due: 2021-10-17T23:59:59+0900)

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/cs431#367]
* Documentation: [homework/doc/linked_list.md](https://github.com/kaist-cp/cs431/blob/main/homework/doc/linked_list.md)
* Submission link: https://gg.kaist.ac.kr/assignment/34/

**Comment by jeehoonkang** [comment]
Now you can submit your solution to gg (see the original post).
