### ISSUE TITLE
[Question] HW2 linked list: No peek_next test on github code, but gg.kaist.ac.kr has it

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs431#369]
When you're asking a question, please make sure:

- [x] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Hello. I'm doing HW#2 linked list.
On github [code](https://github.com/kaist-cp/cs431/blob/main/homework/tests/linked_list.rs), there is no test for peek_next.
But on gg.kaist.ac.kr, it tests for peek_next. So i can not see how it works.
Is it intended? 
Thank you.

**Comment by junsooo** [comment]
By the way, now I checked that source's example comment is enough for passing test.

```
fn test_peek_next() {
    let mut list: LinkedList<_> = vec![1, 2, 3].into_iter().collect();

    let mut it = list.iter_mut();
    assert_eq!(it.next().unwrap(), &1);
    assert_eq!(it.peek_next().unwrap(), &2);
    // We just peeked at 2, so it was not consumed from the iterator.
    assert_eq!(it.next().unwrap(), &2);
}
```

**Comment by tomtomjhj** [comment]
In fact, the example code in the comment is a actual test. It's called "doc test" and you can run them with
```
cargo test --doc linked_list
```

**Comment by junsooo** [comment]
Oh thank you.. I didn't notice that
