### ISSUE TITLE
[Question] The Scope of Promising Semantics

### ISSUE THREAD

**Issue by yj-han** [kaist-cp/cs431#371]
Summary: This question is about how broad the scope of promising semantics can be.

Watching the video lectures given as homework, I understood promising semantics as a means of modeling relaxed behaviors and orderings, so that we can determine if a certain event is possible to occur on given lines of code. (Being able to answer [causality test cases](https://www.cs.umd.edu/~pugh/java/memoryModel/CausalityTestCases.html) formally)

Since I have not taken compiler courses nor have deep understanding in language semantics, I'm not sure if promising semantics can cover all optimization rules that cause relaxed behaviors and instruction reorderings. Can we apply promising semantics to multiple different languages?

**Comment by drzix** [comment]
Hi Yeji,

Promising semantics supports relaxed behaviors based on C++ memory model. Therefore, it can also be applied to languages whose memory model is inspired by C/C++'s one. (e.g. Rust, LLVM, D, Go, OCaml, ....)

**Comment by yj-han** [comment]
@drzix Thank you for your explanation!
