### ISSUE TITLE
Midterm exam on Oct 20, mandatory practice session on Oct 13

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#373]
Please read carefully for the exam.

- While we tried our best to build a fair and reasonable exam environment for the students, this online exam method still provides less control to the instructors.
  Therefore, we do not have a choice but to enforce a lot of restrictive rules.
  Please kindly understand the inevitable strictness and keep in mind the following rules so that you will not get into unnecessary trouble in the exam. 

- We will remotely conduct the **midterm exam on Oct 20 (Wed), 10:00-11:45**.  (**No extension** will be given.)
  + **IMPORTANT: TIME CHANGED**

- We will have a **mandatory practice session on Oct 13 (Wed), 10:30-11:45**.

- For the exam, students are required to **join (1) [the usual Zoom room](https://kaist.zoom.us/my/jeehoon.kang) and (2) another Zoom room (TBA) at least 10 minutes before the beginning.**

  + **IMPORTANT**: You'll need **two Zoom accounts** to join the two Zoom rooms. If you have only one, please sign up once again.

  + [The usual Zoom "Announcement" room](https://kaist.zoom.us/my/jeehoon.kang):

    Join with a device (probably desktop/laptop) in which you'll solve the exam problems.

    Turn off the camera and microphone.

  + Another Zoom "CCTV" room (TBA):

    Join with another device (probably laptop/mobile) that observes you during the exam.

    **For the entirety of the meeting, you need to (1) turn on the camera and microphone; (2) show your hand, paper, keyboard, and monitor**; and (3) turn off the speaker.
    (For privacy concerns: please be noted that you agreed to do this at the beginning of the semester.)

    I've attached the model scene from the experienced TA above.

- On the screen, you can only look at the followings:

  + The Announcement Zoom room

  + https://gg.kaist.ac.kr

    * Go to https://gg.kaist.ac.kr/course/9 and click the exam event.

    * Here, you can see the "event token" (see below).

    * Here, you can also ask questions.

      If your question is not answered for 10 minutes, please let us know in the announcement room's chat.
      Your questions can be written either in English or Korean. Answers will be in English.

  + the Google Form for the exam problems and answers

    * It will be announced in the announcement room.

    * To answer the Google Form, you need to (1) log in with a Google account, and (2) fill out your KAIST email address, name, student ID, and the event token.

    * The problems will be in English. You may answer either in English or Korean.

    * Frequently save your answer.

      Google Form does not automatically save your answers unless you "submit" them.
      You are allowed to resubmit the answers as many times as you want, so it is strongly recommended for you to submit your answers frequently.
      It is your responsibility to maintain your answers reliably and we will not make any exceptions due to technical problems such as network disconnections, web browser crashes, web browser hanging, etc.

- You need to follow the following rules:

  + **You should be properly present in both Announcement and CCTV rooms for the entirety of the exam.**
    If you disappear from the camera after the exam starts, we will assume that you gave up on the exam and your score will be automatically zero.
    Network disconnections and/or power outages will not be excuses. Make sure you find a place where you can get a reliable internet connection and power supply.
    No restroom break will be allowed.

  + **Your Zoom name should be "<student-id> <full-name>"**, e.g., "200711632 강지훈". Otherwise, you may be disqualified.
     As soon as you join the rooms, please write down your name and student id in both rooms.

  + Frequently read Annoucement Zoom room's messages. We'll DM you when your CCTV doesn't work properly.

  + At the beginning of the exam, you will be asked to show your student card.
    Please show it in front of the CCTV camera.

  + The use of pencil and paper is allowed. Calculators and tablets are not allowed. Text editors are not allowed.

  + You may leave at least 30 minutes after the beginning **only after getting permission.**
    To get permission, ask a question.  If you leave without permission, your score will be automatically zero.

**Comment by jeehoonkang** [comment]
I finished marking the midterm exam.
- N = 41, min = 40, max = 91, median = 69, average = 69.03, stdev = 12.39 ([histogram](https://docs.google.com/spreadsheets/d/e/2PACX-1vSJ1GOad3JntPEJl-EHfcjuzxUtQBnh2WQtH4JT1TMPkUFe2g0jELHhbAAFt_sIDeHmnF8ANSry-Ux8/pubchart?oid=88179016&format=interactive))
- Your socres for each part will be published at gg.
- If you want to claim on the midterm exam, please send the head TA (https://cp.kaist.ac.kr/kyeongmin.cho/) an email before 2021/11/5 (Fri).

**Comment by drzix** [comment]
**The maximal point of part 4 (ticket lock) was CHANGED**
- Before: 15
- After: **10**

Your scores have no change. Sorry for confusing.

(Regardless of this change, all claims of part 4 will be addressed.)

**Comment by jeehoonkang** [comment]
Claims have been reflected on gg: https://gg.kaist.ac.kr/course/9/
