### ISSUE TITLE
[Question] Java Causality Case 11 And the reason for no-recertify in lecture's example

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs431#375]
When you're asking a question, please make sure:

- [x] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [x] You read the corresponding sections of the slide.
    + [x] You searched for the concepts using search engines and Wikipedia.

--
https://www.cs.umd.edu/~pugh/java/memoryModel/CausalityTestCases.html
```
Causality test case 11
Initially, x = y = z = 0

Thread 1:
r1 = z
w = r1
r2 = x
y = r2

Thread 2:
r4 = w
r3 = y
z = r3
x = 1

Behavior in question: r1 = r2 = r3 = r4 = 1

Decision: Allowed. Reordering of independent statements can transform the code to:
	Thread 1:
	r2 = x
	y = r2
	r1 = z
	w = r1

	Thread 2:
	x = 1
	r3 = y
	z = r3
	r4 = w

  after which the behavior in question is SC.
```
I am curious for "nested promise" in case 11. Is this thought process for promising semantics correct?
1. On Thread 2, make promise for x = 1. And it is certified. (always x can be 1)
2. On Thread 1, make promise for y = 1. And it is certified. (By r2 = x = 1, y = r2 = 1. line 3, 4 respectively)
3. On Thread 2, make promise for z = 1. And it is certified. (By r3 = y = 1, z = r3 = 1)
4. On Thread 1, make promise for w = 1. And it is certified. (By r1 = z = 1, w = r1 = 1)
5. Execute Thread 1. Thread 1 can use Thread 2's promise, that is x = 1 and z = 1. So r1 = 1, r2 = 1 and this allows recertify about y = 1 and w = 1 that promises made by thread 1.
6. Execute Thread 2. Thread 2 can use Thread 1's promise, that is y = 1 and w = 1. So r4 = 1, r3 = 1 and this allows recertify about z = 1 and x = 1 that promises made by thread 2. 

If it is incorrect, i want to know the reason why it is.
(Is promising semantics allows "reordering"? I think the answer is no)
(Or promising semantics don't allow "nested promise")

--------------------------------------------------------------------------------

I have another question.
This is the example on lecture. On ppt page 61.
```
Thread 1:
r1=X
Y=r1

Thread 2:
r2=Y; r3=X // due to RW coherence
if r2==1 { X=r2 }
else { X=1 }

r1=r2=r3=1 disallowed
```

Lecture says
1. Thread 2 -> make promise for x = 1. certified because of else statement
2. execute thread 1. use thread 2's promise and r1 can be 1, y can be 1.
3. execute thread 2. and r3=X fails to re-certify because "it is already x=1..??? and the view should be after x=1..??"(this may be wrong....)

Actually I don't understand why recertify for X fails and so curious about it.
Please check below statement is correct and reason why.
a) Because r3=X statement is more in front than if-else statement. If r3=X statement goes back than if-else statement, then recertify success. 
b) We can use x = 1 only for thread 1, because it is thread 2's promise. On thread 2, we have to certify x = 1 line by line. so on r3=X line, we can only use X=0 value. (But i don't understand because if r3=0, r2=1 then anyway recertify success.)
c) If add "X=1" line after Thread 1's final line(Y=r1), then recertify success because on thread 2, we can use r3=X=1. and r1=r2=r3=1 allowed.
d) other reason...

Thank you.

**Comment by junsooo** [comment]
Thank you very much for replying.
I didn't know that document exist.

I have two more questions...
For page 61, 
So I understood that the failing reason is actually it tried to assume X=1 before it comes to 'reality', so if r3=1 goes back than if-else statement, then recertify success, right? (I think it's true)
Also, if we add "X=r1" line after Thread 1's final line(Y=r1), then is recertify success? (i think it's false because Thread 2 should anyway recertify, and it fails)

Thank you. @drzix

**Comment by drzix** [comment]
We've resolved the questions above at office hour,

1. A thread can't re-certify another's promise because of *rules* of Promising semantics which define a promise set is per-thread one and mandate a thread to fulfill promises only in its own promise set. There may be a complicated counterexample, if a promise set is defined as a global one so that a thread can fulfill other's promise.
2. Yes, it's possible. From the point of view of other threads, a promise is no different from an ordinary write: once *T* has promised to write *v* to *x*, other threads can read from that write.

Closing, but feel free to reopen it if you have follow-up questions.
