### ISSUE TITLE
[Question] Having trouble with debugging. Debugger shows strangely huge number.

### ISSUE THREAD

**Issue by kaist-kihwan** [kaist-cp/cs431#517]
I've used debugger for VSCode and CLion, but both of them have a same issue.

I was following step-by-step my code and watch the value. Suddenly, the debugger shows strange number for integer value.
This is the screen that debugger shows.
![image](https://user-images.githubusercontent.com/62145252/137493755-b6bc5348-0bf6-4a77-b7a0-8334f0a4cd11.png)
I have no idea what -858995912 means....
I just click 'step into' for function application and don't do anything else.
Why is this happening? How can I fix it?

**Comment by Lee-Janggun** [comment]
What probably happens is that you are reading into uninitialized memory. That value is very close to 2^33.

**Comment by tomtomjhj** [comment]
I agree with Janggun. If that's the case, running with AddressSanitizer would help debugging it. https://github.com/kaist-cp/cs431/tree/main/homework#using-llvm-sanitizers

**Comment by kaist-kihwan** [comment]
Thank you! Address sanitizer helps a lot.
