### ISSUE TITLE
[Question] Midterm exam coverage

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#519]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

--

Could you specify the midterm exam coverage?
Am I correct?

- Slides up to page 73
- Video up to 16
- Rust programming which has been introduced only in the lecture

**Comment by jeehoonkang** [comment]
The midterm exam covers:
- slide pages 1-73, roughly corresponding to YouTube video #16 (https://www.youtube.com/watch?v=j0demG9TU6s&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=16)
- all the Rust documentation and YouTube videos referenced during the lecture or assigned as watching assignment
- programming assignments 1-2
