### ISSUE TITLE
[Question] How does MCS lock ensures data integrity when only relaxed ordering is used?

### ISSUE THREAD

**Issue by n0gu** [kaist-cp/cs431#521]
In some cases (when there is very low contention), the MCS lock implementation only uses relaxed ordering. Could you explain how it ensures data integrity without acquire / release ordering?

For example, consider following case (initial state: L.tail is null, Data is `A`):

1. T1 `lock()`s
2. T1 modifies Data to `B`
3. T1 `unlock()`s, but because no other threads are waiting, T1 just swaps L.tail with null with `Relaxed` ordering
4. Now, T2 `lock()`s, and because L.tail was null, T2 just swaps L.tail with `Relaxed` ordering and immediately returns

Because there is no acquire / release ordering guarantees in above code path, it seems like it is possible for T2 to read the outdated data (`A`), not `B`.

Am I missing something?

**Comment by junsooo** [comment]
I think this issue may help you.... (actually i don't know exactly)
https://github.com/kaist-cp/cs431/issues/296

**Comment by junsooo** [comment]
I think this issue may help you. (actually i don't know exactly)
https://github.com/kaist-cp/cs431/issues/296

**Comment by n0gu** [comment]
@tomtomjhj Sorry to bother you again, but in 4bd55e9 I think the change with CLH lock is not necessary, since ordering guarantees are always satisfied through line 42 and line 51. Could you examine it once again?

**Comment by n0gu** [comment]
Clearly understood. Thank you very much for the detailed explanation! 😁
