### ISSUE TITLE
[Question] A few questions about promising semantics.

### ISSUE THREAD

**Issue by syoh0708** [kaist-cp/cs431#522]
제 짧은 영어 실력으로 제 의도를 정확히 전달하지 못할 것 같아 한글로 먼저 적겠습니다.

### case 1
```
T1     || T2
r1 = X || r2 = Y // instruction 1
Y = r1 || r3 = X // instruction 2
       || if r2 == 1 { X = r2 } // instruction 3
              else   { X = 1 }
```
is r1=r2=r3=1 allowed? -> causality problem이라고 부르는 게 맞나요? 일단 맞다고 생각하고 마저 서술하겠습니다.
## Q1. Relation between causality problem & store hoisting & promising semantics

case 1에서 
r1=r2=1은 instruction 2 - instruction 3 - instruction 1의 순서로 reordering이 가능한 반면
r1=r2=r3=1은 만약 가능하려면 instruction 3 이 맨 앞으로 hoisting 되어야하지만 program semantic의 변화없이는 불가능한데 

Q1-1. causality problem(일반화시키면, set of combination of register values)과 program semantic의 변화를 무시(coherence 무시)한 store hoisting(일반화시키면, set of all available reordering of instructions)가 동치관계(엄밀히 말하면 store hoisting case -> register values인 함수)에 있나요?
Q1-2. instruction 3의 store hoisting이 가능하다는 명제 q를 판별하기 위해 이와 동치인 명제 p에 대해서 판별을 하는데 
명제 p가 성립하기 위해서는 case 1과 같이 T2의 맨 처음에 X = 1을 적겠다는 promise를 해야하고, 
certification과 re-certification이 성공하면 q is consistent in promising semantics(program semantic의 변화 없이 hoisting이 가능하다) 이렇게 이해하면 될까요?

### case 1 - 1
```
T1     || T2
r1 = X || (promise to write X = 1) // promise
Y = r1 || r2 = Y // instruction 1
       || r3 = X // instruction 2
       || if r2 == 1 { X = r2 } // instruction 3
              else   { X = 1 }
```

> In T1's (re-)certification, we don't consider interleaving with T2 or the other threads. T1 is certified alone. But at the beginning of the certification, we add arbitrary messages to the memory that models the interferences of arbitrary threads (not only from T2).
from https://github.com/kaist-cp/cs431/issues/161#issuecomment-713914276

> (Re-)certification is checking if a thread is able to fulfill its promises even with arbitrary interferences.
https://github.com/kaist-cp/cs431/issues/161#issuecomment-713910538

Q2-1. 위의 arbitrary interference, interferences of arbitrary threads가 뜻하는 것이 case 1-1에서 instruction 1이 실행되기 전 메모리의 값 X, Y 값이 arbitrary하다는 말이 맞나요? 
Q2-2. 그리고 **we don't consider interleaving with T2 or the other threads. T1 is certified alone.** 이 말은 instruction 1과 instruction 2 사이에 X = 666과 같은 다른 thread의 instruction이 들어갈 수 없다는 말이 맞나요?

> From the point of view of other threads, a promise is no different from an ordinary write: once T has promised to write v to x, other threads can read from that write. **(In contrast, T cannot read from its own promised write until T has fulfilled the promise: this is crucial to preserve basic sanity of the semantics.)**
https://sf.snu.ac.kr/publications/promising.pdf

https://youtu.be/Av7QPv_foRU?list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&t=2099
Q2-3. 위 링크의 강의에서 case 1-1 re-certification에서 instruction 1, 2가 실행이 되고 T2의 view가 X = 1으로 업데이트되어서 현재 view보다 뒤의 timestamp에 메시지를 쓸 수 없기 때문에 instruction 3이 불가능하다. 라고 설명하신 것으로 이해했는데요.
교수님 논문에서 참고했을 때 **promise가 fulfill되지 않은 상태기 때문에 instruction 2 에서 r3에 1을 읽어오는게 불가능하다**라고 해석하는 것이 좀 더 이해가 잘 되어서, 제가 잘 이해한 것인지 궁금합니다.

Q2-4. 혹시 certification이 가능하지만, re-certification에서 promise한 값을 쓸 수 없어서 실패하는 경우를 공유해주실 수 있을까요?(저도 고민해보겠습니다.)

긴 질문 읽어주셔서 감사합니다.

**Comment by syoh0708** [comment]
먼저 굉장히 불친절한 질문에 친절히 답해주셔서 감사합니다. 🙇🏻 

1번 질문은 같은 코드에 대해서(예를 들어 case 1의 경우) 
r1=r2=1 -> causality problem 1은 instruction 순서를 2 - 3 - 1로 바꾸면 가능하고
r1=r2=r3=1 -> causality problem 2는 instruction 순서를  3 - 1 - 2(or 3 - 2 - 1)로 바꿔야하지만, rw coherence, promising semantic에 의해 프로그램의 의미자체가 바뀌기 때문에 불가능 한 것으로 보입니다.
그래서 causality problem과 instruction의 순서가 굉장히 연관이 깊어보여서, 둘이 어떤 관계에 있나 여쭤본 것인데 1-1 질문은 표현하기가 어려워서 넘어가도 될 것 같습니다. 😅 

1-2 질문은 
특정 hoisting의 유효성을 promising semantics로 판별하기 하는 방법으로 
이 hoisting이 valid하다고 가정했을 때 가능한 causality problem(r1=r2=r3=1인 경우가 가능한지)을 certify, re-certify함으로써 이 과정에서 모순이 생기면 hoisting이 불가능, 모순 없이 promise가 fulfill 가능하면 hoisting이 가능하다고 판별하는 것
이 맞는지 여쭤본 것이었습니다.

causality problem, hoisting, promising semantics의 의미에 대해서 여쭤보려고했는데 제 표현이 이상해서 이해가 안 되신다면 넘어가져도 괜찮습니다.

2-1, 2-2의 경우
certification에 대한 설명에 arbitrary interference, interferences of arbitrary threads라는 표현과 we don't consider interleaving with T2 or the other threads. 라는 표현이 상충되게 해석될 수 있는 부분이 있어서

Thread 2가 X=1을 promise했다고 했을 때 T2의 certification을 할 때 instruction을 수행하기 전의 memory의 상태는 아래처럼 어떤 값이든 가능하지만
ex)
case 1) X = 666, Y = 66
case 2) X = 0, Y = 0
case 3) X = 666, Y = 0
case 4) X = 1, Y = 1
...

아래와 같이 certification 중간에 다른 thread가 개입해 메모리의 걊이 변경되지는 않는 것이 맞는지 여쭤본 것입니다.

r2 = Y // instruction 1
**X = 666 // instruction 1과 2사이에 다른 스레드에 의해 X의 값이 666으로 변함**
r3 = X // instruction 2
if r2 == 1 { X = r2 } // instruction 3
else   { X = 1 }

**Comment by drzix** [comment]
All promises should be eventually re-certified.

If you mean "Should we re-certify existing promises before promising another message?", the answer is no.
See this [slide](https://docs.google.com/presentation/d/1INonaKICTV7ygiams-0xkA6BjCv3L_kFLtE8_Zp66xI/edit#slide=id.gb0d86fa221_0_148).

**Comment by syoh0708** [comment]
@drzix 
긴 질문 친절하게 답변해주셔서 다시 한 번 감사드립니다. 🙇🏻 
이슈는 닫도록 하겠습니다!
