### ISSUE TITLE
[Question] Question about difference btw acquire/release ordering and seq_cst ordering

### ISSUE THREAD

**Issue by syoh0708** [kaist-cp/cs431#525]
https://stackoverflow.com/questions/14861822/acquire-release-versus-sequentially-consistent-memory-order

```
Thread 1:

x.store(1, release); // instruction 1

Thread 2:

y.store(1, release); // instruction 2

Thread 3:

a = x.load(acquire); // x before y
b = y.load(acquire);

Thread 4:

c = y.load(acquire); // y before x
d = x.load(acquire);
```

> As written, there is no relationship between the stores to x and y, so it is quite possible to see a==1, b==0 in thread 3, and c==1 and d==0 in thread 4.

In this stackoverflow question, it says it is possible to see a==1, b==0 in thread 3, and c==1 and d==0 in thread 4.
I thought relax behavior is about reordering instructions.
In just reordering instructions, since instruction 1 and instruction 2 has an order in global timestamp. I think it is not possible to see that case. How is it possible?

**Comment by tomtomjhj** [comment]
To be clear, what is the question about?
1. Why this is possible in the memory model (promising semantics, ISO C/C++ memory model, ...)
2. How this behavior may happen in the actual implementation of the language/hardware.

**Comment by syoh0708** [comment]
My intent was second one.
But I would appreciate it if you could answer first one.
As my short understanding with respect to release - acquire ordering, 
Thread 1 - Thread 3 : release - acquire relation for variable x
Thread 2 - Thread 3 : release - acquire relation for variable y
-> Should be ordered, so it seems a = b = 1;
I can't understand also in promising semantics 😢

**Comment by tomtomjhj** [comment]
1. Note that `x.store(1, release)` and `y.store(1, release)` are done by different threads. So the message of `x.store` and `x.store` are not related, meaning that the release-acquire synchronization doesn't carry any meaningful information.
2. I agree that reordering alone doesn't produce this behavior in this particular example. A possible scenario would be reading the outdated value in the cache (hardware). But as a user of the language, we don't really need to understand the exact mechanism of this stuff (after all, the purpose of the semantics is to abstract these details away). So this question would be best answered by compiler/hardware engineers.

**Comment by syoh0708** [comment]
I also wondered why the "if" condition exists, but that's the reason!
Thank you for explanation.
I'd close this issue.
