### ISSUE TITLE
[Homework 4] Lock-coupling linked list (due: 2021-11-19T23:59:59+0900)

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/cs431#530]
* Documentation: [homework/doc/list_set.md](https://github.com/kaist-cp/cs431/blob/main/homework/doc/list_set.md)
* Submission link: https://gg.kaist.ac.kr/assignment/40/

**Comment by junsooo** [comment]
Could I know the expected due of HW4 roughly?

**Comment by tomtomjhj** [comment]
Sorry for late announcement. The due is 2021-11-19T23:59:59+0900.

**Comment by yj-han** [comment]
@tomtomjhj May I ask you when the submission link is open? Actually this question goes for HW5 as well!

**Comment by jeehoonkang** [comment]
The submission link is now provided (https://gg.kaist.ac.kr/assignment/40/).
