### ISSUE TITLE
[Question] HW3 Is it possible to call Box::from_raw without calling drop on the fields of the struct that is being deallocated by Box::from_raw for try_unwrap?

### ISSUE THREAD

**Issue by asmir-a** [kaist-cp/cs431#534]
Box::from_raw both deallocates the memory and calls drop on the fields of the struct. Therefore, the test for the value being dropped only once did not pass. I solved the issue by using another function.
However, I am curious if it is possible to use ```Box::from_raw``` to complete the implementation for try_unwrap. If so, could you give a cue?

**Comment by tomtomjhj** [comment]
Yes it's possible. Hint: [`mem::forget`](https://doc.rust-lang.org/std/mem/fn.forget.html)

**Comment by asmir-a** [comment]
I cannot use it one the ArcInner because ArcInner does not implement Clone or Copy. Also, I need to deallocate the counter being stored in the ArcInner as well as the ArcInner itself.
Calling ```mem::forget``` on Arc did not help me to use ```Box::from_raw``` on the pointer inside of Arc (which is ArcInner). So, what do I need to pass into ```mem::forget```?

**Comment by tomtomjhj** [comment]
> the test for the value being dropped only once did not pass

Hint: Identify where the value gets dropped. Then prevent the extra drop with `mem::forget`.

**Comment by asmir-a** [comment]
I tried preventing the whole ArcInner from being dropped, but that resulted in a memory leak. I believe it is because I need to somehow separately deallocate the count and data of the ArcInner field, right? So using ```mem::forget``` on the whole ArcInner is not correct, is it right?

**Comment by tomtomjhj** [comment]
> Box::from_raw both deallocates the memory and calls drop on the fields of the struct.

`Box::from_raw` creates a `Box`, whose `drop` `drop`s the data and `free`s the memory.


> separately deallocate the count and data of the ArcInner field, right?

The heap memory occupied by `ArcInner` must be deallocated (and usually "separate deallocation" of a single memory block doesn't make sense), while preventing `data` from being `drop`ped (and passed to the caller instead).

Tips for implementing that:
* https://github.com/kaist-cp/cs431/issues/125#issuecomment-706039332
* https://github.com/kaist-cp/cs431/issues/140#issuecomment-709664508

There are several things that will be `drop`ped in `try_unwrap`:
* `Box` made from the pointer to `ArcInner`: is it ok to drop this?
* `this`: it is ok to drop this?

**Comment by asmir-a** [comment]
oh, okay, thank you. I think now I get it.
