### ISSUE TITLE
[Question] Today's quiz + lock free queue questions

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#535]
I always appreciate your kind lecture. 

Here are some questions! Thanks in advance.

1. Is there no quiz for today (11/03)? I can not figure out the quizzes in gg.kaist.
2. Why should we use tail->next in lock free queue push compare and swap operation?
```
 let _ = self.tail.compare_exchange(
                    tail,
                    next,
                    Ordering::Release,
                    Ordering::Relaxed,
                    guard,
                );
```
 What if we use self.tail instead of next..? Current code requires that if there are a lot of push operations, then the tail likely be more stale, and finally it loops several times.

Maybe I guess there are some reasons to make it impossible.. could you let me know the reasons?

Thanks!

**Comment by drzix** [comment]
I recommend you divide multiple questions into multiple issues next time :)

1. @jeehoonkang Would you please answer this question about quiz?
2. I'm sorry but I don't fully understand what your question is about. Would you explicitly write down (1) which part (i.e. line number) of the code you want to suggest to change and (2) specific reasons? Maybe it's more convenient to use Pull Request to discuss this kind of question:)

**Comment by anonymous1782** [comment]
> I recommend you divide multiple questions into multiple issues next time :)
Thank you for your advice! I will keep in mind from next questions!

> I'm sorry but I don't fully understand what your question is about. Would you explicitly write down (1) which part (i.e. line number) of the code you want to suggest to change and (2) specific reasons? Maybe it's more convenient to use Pull Request to discuss this kind of question:)

Fortunately, I somewhat understood.. I will ask again if I have ambiguous things again. Sorry and Thank you!

**Comment by jeehoonkang** [comment]
Oh sorry, I forgot to set up the quiz. Let's say we don't have a quiz for that day.
