### ISSUE TITLE
[Question] Question about relaxed behavior in the Treiber's Stack

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs431#536]
I read this issue. https://github.com/kaist-cp/cs431/issues/232
And I have additional question for this issue's question 1.
I understood every line of question 1 except "until it read the latest value." 

push 함수에서 50 line CAS가 fail한 이후에, loop을 계속 돌면서 45 line에서 head의 값을 Ordering::relaxed를 통해 가져오게 되면, promising semantics 상에서 봤을 때 head가 최신 값인 B를 읽어오는 게 아니라 계속해서 이전 값인 A를 읽어올 수 있는 것으로 이해했습니다.(Because there is no sc view) 
그럼 무한정으로 계속 A를 읽어오면 계속 실패하는 게 맞는 건가요? 제가 잘못 이해한 것인지 궁금합니다.
Promising semantics가 현실 세계와는 달라서 언젠가 B를 읽어온다고 생각해도, 만약 실패하는 경우가 늘어나서 loop를 계속 돌게 되면, 차라리 45 line을 Acquire로 바꿔줘서 50 line에서 Release 해준 값을 첫번째 loop에서 바로 받아올 수 있도록 해주는게 더 빠를 수 있지 않을까 하는 생각이 듭니다.

**Comment by drzix** [comment]
> Ordering::relaxed를 통해 가져오게 되면, ... 계속해서 이전 값인 A를 읽어올 수 있는 것으로 이해했습니다.
> 차라리 45 line을 Acquire로 바꿔줘서

In Promising semantics, relaxed ordering doesn't mean that "I may read old value" nor acquire ordering doesn't mean that "I always read the latest value".
Regardless of ordering, all read may read old message whose timestamp is greater than or equal to the thread view. And acquire ordering is just used to incorporate a message view with thread view for synchronization.

> 무한정으로 계속 A를 읽어오면 계속 실패하는 게 맞는 건가요?

It doesn't happen because the thread view(`head`) is updated when CAS failing.

**Comment by junsooo** [comment]
I have another question.
It is about https://github.com/kaist-cp/cs431/blob/main/lockfree/src/stack.rs#L50 and L64's release-acquire pair.
I'm trying to understand it without invariant.
Lecture에서, L50과 L64에 release acquire pair가 있는 이유는 Thread A에서 push해준 값을 Thread B에서 바로 pop 해줄 수 있도록 해주기 위함이라고 들었습니다.
그런데 L50, L64를 둘 다 relaxed로 해줬을 때 항상 아래와 같이 되는 것이 아닌가요? 제가 잘못 이해한 것인지 궁금합니다.

기존 stack 상태: top -> 2
1. Thread A에서 push를 실행. head에 값 1을 넣어줌 .. top -> 1 -> 2
2. Thread B에서 pop을 실행. Thread A에서 넣어준 값을 인지하지 못하고 head로 2를 가져옴
3. 이 때 head값이 최신이 아니기 때문에 Thread B의 cas가 실패함.
So By "It doesn't happen because the thread view(head) is updated when CAS failing.", Thread B가 다음 번 loop(63 line - 83 line)를 돌 때 항상 최신 head 값인 1을 가져오게 되므로 결과적으로는 Thread B에서 Thread A에서 넣어준 head값을 항상 가져올 수 있게 됨.

**Comment by drzix** [comment]
In your example, if those two CAS are executed with relaxed ordering, thread B may read old values in the head node (e.g. `n.next=NULL`). Of course it can be described by Promising semantics and I think you can easily draw a diagram about this example:)
