### ISSUE TITLE
Q&A session on Nov 17th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#540]
We will have a Q&A session on Nov 17th. Please ask questions at this issue tracker beforehand!

**Comment by junsooo** [comment]
At this issue tracker means this issue? #540
I have question for https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L277-L278
1. What is the head cursor's inner value when list is empty?
is it prev : pointer to null pointer, curr: null pointer? And is it "defined behavior"?
2. On find_harris(https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L101), is this statement correct?
-> 찾으려는 key에서 가장 가까운 한개의 chain of logically removed nodes만 삭제해준다.

**Comment by yj-han** [comment]
In lock-free data structures, `guard` from `crossbeam-epoch` keeps the current thread pinned. Out of curiosity, I looked into the internal implementation of `Guard`, but unable to understand how the thread stay pinned after all. Can you explain about the implementation strategy for `guard` and why we use `guard` in lock-free data structures again?

**Comment by junsooo** [comment]
I heard on find_haris function, (https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L101)
Line 109(let next) should be acquire to get latest value after found loop.
There is no release-acquire pair but only acquire pair. is it okay?

**Comment by jeehoonkang** [comment]
- I'll be more convenient to post a new issue.
- @junsooo `prev` will be the pointer to the head pointer, and `next` will be `nullptr`. It's well defined.
- @junsooo Harris traversal cleans up the **last** chain of logically deleted nodes at once. Harris-Michael traversal cleans up **all** logically deleted nodes one by one.
- @yj-han the guard and *epoch-based reclamation* is the topic of a later session: https://www.youtube.com/watch?v=cYDMq5FOiw4&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=26 I'm really glad you're interested in the materials. Please stay tuned!
- @yj-han Yes, for the code, two guards are created and destroyed. That's a limitation of the API of the Treiber's stack you posted: a more faithful API would accept `&guard` in the `push()` and `is_empty()` APIs. Then you may be able to create a single guard and use it for both functions.
- @junsooo Release is used for most occurrences of CASes, and they are synchronized with the Acquire at L109.
