### ISSUE TITLE
[HW4] How to change only cursor, not head value in Cursor.find

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs431#541]
My situation is:
```
       1 -> 2 -> 3
       |
       |
   self.head
```
And want to insert 4.
In my OrderedListSet.find, I call cursor.find like this.
```
let mut cursor = Cursor(self.head.lock().unwrap());
(cursor.find(key), cursor)
```
and want result for cursor: 3, cursor.find(key): false.

And in my Cursor.find function, when i find wanted value(in this case, 3), i write code like this:
`*self.0 = wanted_node;` to change the cursor value to return 3. 
But after debugging, I noticed that the self.head value is also changed to 3, so I couldn't use Cursor(self.head.lock().unwrap()) again.
So, how to change only cursor value, not head value in cursor.find? 

Thank you.

**Comment by kimjungwow** [comment]
How about using `*self=Cursor(MutexGuard_of_WantedNode)` ?

**Comment by junsooo** [comment]
Thank you! It works.
