### ISSUE TITLE
[Question] HW4 insert implementation

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#542]
Thank you for your hard works, always.

I am thoughtfully reading the entire posts regarding of HW4.
However, I am confused by the post : #199 

In this post, the writer asked about last node next pointer, and I also think like him/her.

After the writer inserted some figure:

_OrderedListSet -> head : null
insert 1
OrderedListset -> head : node(1) -> null
insert 2
OrderedListset -> head : node(1) -> node(2) -> null_

TA's answer was 
> The list is supposed to be sorted by the element.

I'm sorry, but I can not follow the flow of the conversation. Could you explain it again briefly?

**Comment by tomtomjhj** [comment]
Unfortunately, I don't remember what I meant by "The list is supposed to be sorted by the element". But I recall that this issue

> When I use *self.head.lock().unwrap() = Node::new(key, ptr::null_mut());,
> it does not make error but value is not inserted when I check by contains or remove.

can be fixed by following the hint

> hint: Is ptr::null_mut() correct?

**Comment by anonymous1782** [comment]
Thank you for quick answer! Then, the writer's comment 

_OrderedListSet -> head : null
insert 1
OrderedListset -> head : node(1) -> null
insert 2
OrderedListset -> head : node(1) -> node(2) -> null_

is right. Am I correct?

**Comment by tomtomjhj** [comment]
Yes

**Comment by anonymous1782** [comment]
Thanks!!!
