### ISSUE TITLE
[Question] HW4 log_concurrent Test Failed

### ISSUE THREAD

**Issue by kaist-kihwan** [kaist-cp/cs431#543]
When I run cargo test, `smoke`, `parallel_iter_end`, and `iter_consistent` pass.
However, `log_concurrent` always fails.
Since the code of the `log_concurrent` function is quite complex, I have no idea what's the problem.
Can someone explain what kind of problem might be possible?

**Comment by junsooo** [comment]
I think you can first narrow the range of ops.
There is a line `let ops = [Ops::Contains, Ops::Insert, Ops::Remove];` and you can exclude some ops.
In my case, the problem was remove function. So when i erase Ops::Remove from log_current, test passed.

**Comment by tomtomjhj** [comment]
It randomly runs many operations concurrently and logs the operations & results per thread. It then checks the consistency of the log. For example, if the key k was successfully deleted twice, then k must have been inserted at least twice.

**Comment by kaist-kihwan** [comment]
> I think you can first narrow the range of ops. There is a line `let ops = [Ops::Contains, Ops::Insert, Ops::Remove];` in log_current function and you can exclude some ops. In my case, the problem was remove function. So when i erase Ops::Remove from log_current, test passed.

Now I got it.
If we remove `Ops::Remove`, `log_concurrent` will test insert and contain.
If we remove `Ops::Insert`, `log_concurrent` will be meaningless.
If we remove `Ops::Contains`, `log_concurrent` will test insert and remove.

Now I notice the problem is remove part (still don't know yet what's the exact problem)
Thx to @tomtomjhj and nice reply of @junsooo

**Comment by junsooo** [comment]
For remove function, #207 helped me, especially this comment
https://github.com/kaist-cp/cs431/issues/207#issuecomment-724448650
@kaist-kihwan
