### ISSUE TITLE
[Question] Mutex Verification from RustBelt Lecture

### ISSUE THREAD

**Issue by yj-han** [kaist-cp/cs431#548]
I watched the lecture [RustBelt: Logical Foundations for the Future of Safe Systems Programming](https://www.youtube.com/watch?v=1GjSfyijaxo) and enjoyed a lot, but then I have a simple question about mutex verification (starting from 46:45).

I understood that the invariant for mutex is `(x ↦ 0 * P) ｖx ↦ 1` and when we acquire the mutex through CAS, the following holds.
```
(x ↦ 0 * P)
CAS(x, 0, 1)
(x ↦ 1 * P)
```
However on the next part, at 49:05, I didn't get the meaning of the phrase from the slide "Restored on the shared state; Hold on to P" and the animation that removes P. Does it mean that we cannot acquire the mutex, thus unable to access P when x ↦ 1?

**Comment by tomtomjhj** [comment]
Since the CAS returns `x ↦ 1`, you can restore the invariant through the RHS, without returning `P` to the invariant. `P` is then given to the thread that acquired the mutex. When the thread releases the mutex, it will return `P` to the mutex invariant.

**Comment by yj-han** [comment]
Oh, I understood. Thank you!
