### ISSUE TITLE
[Question] HW5 growable array, how to consider other thread's insert?

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs431#550]
I'm thinking high level design for GrowableArray.get().

I wonder below case should be considered or not.
When SEGMENT_LOGSIZE = 3,
```
///                          +----+
///                          |root|
///                          +----+
///                            | height: 1
///                            v
///                 +---+---+---+---+---+---+---+---+
///                 |111|110|101|100|011|010|001|000|
///                 +---+---+---+---+---+---+---+---+
```
- I want to insert "dog" in self.root -> 0b001.
So I get self.root with self.root.load(). The height is 1.
And other thread A suddenly insert "cat" in self.root -> 0b111. So 0b000 to 0b111 segment is updated.
And now i insert "dog" in 0b001 with cas operation, and I have outdated segment information(no "cat") but cas doesn't fail because root's height is same as 1, that means tag is not changed. Also self.root value is not changed because segment value itself is pointer. So thread A's insert disappears.
Is this true? And should i consider this case in GrowableArray.get()?

 - On the other head, if thread A suddenly insert "cat" in self.root -> 0b111000000000, root's height should be changed to 4, and tag is changed to 4. So my insert "dog" with cas in 0b001 fails. 
is this true? And should i consider this case in GrowableArray.get()?

**Comment by tomtomjhj** [comment]
The CAS for inserting an element is performed on an `AtomicUsize` in the `Segment` directly. If the thread has obtained the reference to a segment, the changes to the root pointer is not relevant to the thread's CAS operation on the segment.

* Thread A's

**Comment by junsooo** [comment]
Thank you.
So I think i should consider this case in GrowableArray.get:
 - CAS fail because of root.height changes.

If CAS success, I have nothing to do with other thread's insert or delete ..etc.

Thank you.

**Comment by junsooo** [comment]
Now I understand that I have to consider all cases where self.root is changed by another thread.
