### ISSUE TITLE
[Question] Link to Linearizability post in the professor's blog

### ISSUE THREAD

**Issue by jessyoon14** [kaist-cp/cs431#552]
Hello!

In order to understand linearizability better, I want to read the [professor's blog](https://jeehoonkang.github.io/2017/08/23/synchronization-patterns.html) linked in slide 75.
However, the given link points to an unrelated post.
I tried to find the post about linearizability in the professor's blog, but there seems to be only one article in this blog.

Can anyone point me to the correct link to the professor's article about linearizability?

Thank you!

**Comment by jeehoonkang** [comment]
Sorry for the confusion. I just updated the slide page 75: https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.ga50d357ce9_0_11
