### ISSUE TITLE
Video watching sessions on Nov 29 and Dec 6

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#553]
For Nov 29th (tomorrow) and Dec 1st, we will have video-watching sessions instead of real-time sessions due to a personal matter of mine. I'm sorry to announce this late. Please do the following for the online sessions. There will be no quizzes for Nov 29th and Dec 1st.

For the two sessions, watch the following videos:

- https://www.youtube.com/watch?v=drXrIVfBKaQ&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=25
- https://www.youtube.com/watch?v=cYDMq5FOiw4&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=26
- https://www.youtube.com/watch?v=rL9Z8eQEgek&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=27

Then we'll reach the end of the slide, hooray! The plan for the rest of the semester is as follows:
- Dec 6th: We will listen to a guest lecture (TBA).
- Dec 8th: We will have a final Q&A session covering everything.
- Dec 15th: We will conduct the final exam.

**Comment by kjy2844** [comment]
Where can I see related slides?
I thought the link in the slide 101 is for these lectures, but it doesn't work.

**Comment by jeehoonkang** [comment]
@kjy2844 sorry, the link is now fixed: https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.ga357465992_0_0

**Comment by jeehoonkang** [comment]
I just realized that I should have canceled today's lecture due to undergrad interviews. I'm sorry. Instead, I'd like to say these videos are for Nov 29 and Dec 6 (not Dec 1). We won't have a guest lecture on Dec 6, and we will have the final Q&A on Dec 8.

**Comment by 2JS** [comment]
Will it be possible to have guest lecture with optional attendance? I was looking forward to it.

**Comment by jeehoonkang** [comment]
@2JS sorry, I couldn't arrange for one... I'll invite everyone to the invited talks in the next semester.
