### ISSUE TITLE
[Question] HW5 test passes locally but fails on grading server

### ISSUE THREAD

**Issue by c0m0r1** [kaist-cp/cs431#554]
the submission link for HW#5 seems available from the course website. ([link](https://gg.kaist.ac.kr/assignment/41/))
However, When I submit the code, all tests immediately fails and get 0 points even it passes all tests on the given provided homework server.
I'm not sure if it's a grading server's issue or an implemented code's issue.
Please check this issue to confirm the causes.
Thanks.

**Comment by junsooo** [comment]
Me too https://github.com/kaist-cp/cs431/issues/551

**Comment by jeehoonkang** [comment]
I'll fix it soon.

**Comment by jeehoonkang** [comment]
I believe it's now fixed. Would you please try again?

**Comment by c0m0r1** [comment]
I resubmitted now and got full credit. 
Thanks!
