### ISSUE TITLE
[Question] About implementation of find_harris

### ISSUE THREAD

**Issue by Gyubin-Lee** [kaist-cp/cs431#556]
In the code implementation of find_harris in [here](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs),
```
if prev_next == self.curr {
  return OK(found);  //in line 123
}
```
is needed to check prev and curr are adjacent. However, I think by the code below
```
Less => {
    self.curr = next.with_tag(0);
    self.prev = &curr_node.next;
    prev_next = next
}
```
self.curr and prev_next are going to point same location(next) and
```
prev_next == self.curr
```
will always succeed.  Do I misunderstand the code?

**Comment by tomtomjhj** [comment]
Note that the `Less` case doesn't exit the loop

**Comment by Gyubin-Lee** [comment]
Oh, I miss that. Thank you!
