### ISSUE TITLE
[Question] About implementation of find_harris(2)

### ISSUE THREAD

**Issue by Gyubin-Lee** [kaist-cp/cs431#557]
I'm still stuck on understanding the implementation of find_harris in [here](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L101).

Suppose current structure of the link is
```
1 -> 2 -X-> 3 -X-> 4 -> 5 -> 6 -> ㅗ //So node 2 and 3 are logically deleted
```
and search key is 5
```
search key = 5
```
In the first loop of [found](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L107), 
curr_node.key is 1 and it is less than 5, so at the end of the loop,
```
self.curr -> pointer to the node with key 2
self.prev -> reference of (1 -> 2)
prev_next -> pointer the to node with key 2
```
For the second loop, next tag (2 -X-> 3) is 0, so
```
self.curr -> pointer to the node with key 3
```
and continue the loop.
For the third loop, next tag(3 -X-> 4) is 0, so
```
self.curr -> pointer to the node with key 4
```
For the forth loop, curr_node.key is 4 and it is less than 5, so at the end of the loop,
```
self.curr -> pointer to the node with key 5
self.prev -> reference of (4 -> 5)
prev_next -> pointer to node with key 5 // because in this loop, next is curr_node.next
```
And finally the fifth loop, curr_node.key is 5 so we break the loop and final state is
```
self.curr -> pointer to the node with key 5
self.prev -> reference of (4 -> 5)
prev_next -> pointer to the node with key 5
```

In this case, we have to fix the list but 
```
prev_next == self.curr
```
so, it will immediately return the found value.

I think I must misunderstand something but I can't figure it out. Would you help me understanding the code?

**Comment by tomtomjhj** [comment]
Your understanding is correct.

**Comment by Gyubin-Lee** [comment]
But in the [lecture](https://www.youtube.com/watch?v=WYJBdAuX7zw), Harris traversal tries to fix the linked list by physically deleting the node that is logically deleted. So I think in this case we should delete nodes 2 and 3.

**Comment by tomtomjhj** [comment]
Yeah, more precise description would be "physically delete the chain of locally deleted nodes that are right before the search key". But why? When the cursor passes through 4 realizes that 4 is not logically deleted (thus the chain of logically deleted nodes has ended), it's too late to physically delete the nodes, because

**Comment by Gyubin-Lee** [comment]
I got it! Thank you for your answer :)
