### ISSUE TITLE
[HW5] Split ordered list - insert_concurrent fails

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs431#558]
I'm doing hw5 split ordered list.
Test fails with 
`cargo_asan test  --test split_ordered_list insert_concurrent`
with error
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', tests/map/mod.rs:194:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', tests/map/mod.rs:200:6
```
And i'm debugging for reason, and I'm really curious for below situation why happens.

On lookup_bucket, I initialize bucket recursively.
Initialize_bucket's Flow is:
1. initialize parent's bucket
2. Make my sentinel node
3. Find my sentinel node's insert location with parent_cursor.find_harris_michael
4. Try to insert
5. It can be fail because other thread can insert same key with my sentinel node
6. Retry. Before retry, i have to find my sentinel key is already inserted. so reallocate parent_cursor and `parent_cursor.find_harris_michael` again to find it
7. If no exists, I insert my sentinel node. If exists, just return function.
8. If i success to insert sentinel node, I get bucket from my sentinel node's index.
9. I think this bucket's inner value should be null, because i'm the actual inserter for my sentinel node
10. But rarely it's value is not null... I think that means other thread inserted my sentinel node. But In my function, there is no other cas for bucket. So I'm really curious for this. 
It rarely fails in my environment and always fails with grading server, so i have hard time for debugging.

Could you give some suggestion for this situation? I'll really appreciate it.
Thank you.

**Comment by junsooo** [comment]
I found that cas error happens because index == 1's bucket value(bucket.load()) is already in index == 55's bucket value.(the number is changed always)
Is this can be from wrong implementation of buckets.get? But i got full credit for growable_array.

**Comment by anonymous1782** [comment]
I'm actually suffering from similar problem.

Have you passed cargo test, not cargo_asan?

**Comment by junsooo** [comment]
@anonymous1782 
I found that it was actually cargo_asan and cargo.
And i think i found the (not right, but pass) solution right now.
When cas error happens, just retry with current my bucket value. Then test passes. 
But I don't understand why this passes, because already wrote bucket value will overwrited and get the wrong cursor.

**Comment by anonymous1782** [comment]
Thank you for sharing your experience.

Honestly, I thoroughly read your step (1 ~ 10), and I am confusing which is write:
1. cursor insert -> bucket write after cursor insert success (It seems that your implementation is this)
2. bucket write -> cursor insert after bucket write success (This is my implementation)

**Comment by junsooo** [comment]
I thought 1 is correct because i thought 
1. after bucket write, cursor insert can be failed.
2. if anyway there is a method to make it always success,   if i bucket write and other thread read that value, but there is a chance that actually cursor is not inserted yet.

if i'm wrong, please correct me.

**Comment by anonymous1782** [comment]
Thank you! Your second reason looks very very correct.

And, I have one question about your sentence:

> When cas error happens, just retry with current my bucket value. Then test passes.
But I don't understand why this passes, because already wrote bucket value will overwrited and get the wrong cursor.

If cursor insert passed, is there other bucket writers that makes overwritten case?

**Comment by junsooo** [comment]
If cursor insert passed, is there other bucket writers that makes overwritten case?
-> If insert_concurrent test passes, then i think there is no certain case.
But I just thought it can be overwritten, because for example, index = 4 and parent_index = 0,
then cas retry will make parent_index's location to index's location, which is back side from parent_index.(index = 4 의 node가 index = 0의 node보다 뒤에 있음) So I thought that node key between index = 0 and index 4's node can not be found.

**Comment by anonymous1782** [comment]
If I correctly understand your opinion...

> then cas retry will make parent_index's location to index's location

Umm... The parent_index's location will not be changed because it has been already created by someone. (index 0의 bucekt이 이미 만들어졌다면, 다른 이에 의해 수정될 수 없음) Please feel free to criticize me!

**Comment by junsooo** [comment]
Now I think you are right. I misunderstood something, but anyway i don't understand why index == 1 bucket value is in index == 55 value...

**Comment by junsooo** [comment]
If someone knows the reason, please let me know. Now i close issue. @anonymous1782 Please comment something if you have anything!
