### ISSUE TITLE
[HW5] split_ordered_list only stress_concurrent timeout

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#559]
I have passed all test cases except for stress_concurrent, especially cargo_tsan.

Unfortunately, in order to do debug why only cargo_tsan failed,

> cargo_tsan test --release -- --nocapture --test split_ordered_list stress_concurrent

`

     test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.00s

     Running tests/bst.rs (target/x86_64-unknown-linux-gnu/release/deps/bst-c2ad973f0dbb6d6a)

      running 1 test
      test bst_stress_concurrent ... thread '<unnamed>' panicked at 'not implemented', 
      /home/s20204459/cs431/homework/src/bst/mod.rs:66:9
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      thread '<unnamed>' panicked at 'not implemented', /home/s20204459/cs431/homework/src/bst/mod.rs:82:9
      thread '<unnamed>' panicked at 'not implemented', /home/s20204459/cs431/homework/src/bst/mod.rs:66:9
      thread '<unnamed>' panicked at 'not implemented', /home/s20204459/cs431/homework/src/bst/mod.rs:66:9
      thread '<unnamed>' panicked at 'not implemented', /home/s20204459/cs431/homework/src/bst/mod.rs:82:9
      thread '<unnamed>' panicked at 'not implemented', /home/s20204459/cs431/homework/src/bst/mod.rs:82:9

`

failed because bst unimplemented function. (without --nocapture, it works well)

1. Could you give me some suspicious point? Only cargo_tsan stress_concurrent fails due to timeout (it takes about 250 seconds)
2. How to debug it with cargo_tsan test --release -- --nocapture?

**Comment by tomtomjhj** [comment]
2. Try
```
cargo_tsan test --test split_ordered_list --release -- --nocapture stress_concurrent
```
The `--test` argument should come before `--`. The arguments after `--` are passed to each test binaries, and the arguments before `--` are passed to cargo to select the proper test binary.

1.  There are some issues concerning the performance from the last year's iteration of the course. e.g. #276

**Comment by anonymous1782** [comment]
2. Thank you for your answer. It works well.

1. Thank you for your hyperlink. Honestly, I already have checked the entire question regarding HW#5. I thoroughly thought about these problems, but I can not figure them out. (I think it is weird the only 'tsan' stress failed due to timeout while 'cargo', 'cargo --release', 'asan', and 'asan --release' are passed). Finally, I tried to submit my code to the grading server, and I got 180 / 180. Is this problematic?

**Comment by tomtomjhj** [comment]
The score you got on the grading server is the final score, so you have the full credit for hw5.

BTW where were you running the test? If you were running the test in a less performant machine, it may time out because I have set the timeout based on the running time on our lab server and tsan slows down a lot.

**Comment by anonymous1782** [comment]
Hmm... I tested kaist-cp-cs431 server..

**Comment by tomtomjhj** [comment]
Hmm that's weird. Our implementation takes less than 10s with cargo_tsan --release and about 1s with cargo --release.

**Comment by tomtomjhj** [comment]
Since you got the full credit, I think you don't need to worry too much right now. If you want to further investigate the issue, please email me after the end of the semester.

**Comment by anonymous1782** [comment]
Thank you for sharing your execution time and last comment.

My result in grading server of cargo --release is 2s, while 4s in kaist-cp-cs431 for same code. 
Anyway, I will try to optimize it as possible and contact you if I can not resolve it. 

Thank you again!
