### ISSUE TITLE
[Question] HW6 About ABA problem of HazardSlot stack

### ISSUE THREAD

**Issue by c0m0r1** [kaist-cp/cs431#560]
I don't know how to implement a stack that manages available hazard slots safely from the ABA problem.
Comments from `hazard.rs` say,
```
/// - `HazardBag.head_available` and `HazardSlot.next_available` from an "overlay" Treiber stack of
///   slots that are not owned by a shield. This is for efficient recycling of the slots.
```
However, If we implement this stack in the traditional way, I think the ABA problem might be happening with thread interleaving and racy `pop_available`/`push_available` call from protecting/retiring pointers.
Am I on the right point? or is there any solution to deal with this issue?
Thanks.

**Comment by tomtomjhj** [comment]
Good catch! This is indeed a bug. I'll fix this by Monday with a less efficient but simple version that traverses the list to find an inactive (an additional  field of type `AtomicBool`) slot. Another solution is to use something similar to Harris-Michael list (this is what crossbeam does for maintaining the set of per-thread metadata), but I think this is unnecessarily complex for this homework.

@jeehoonkang Please give this student extra credit.

**Comment by tomtomjhj** [comment]
By the way, there's another solution for ABA problem. See https://en.wikipedia.org/wiki/ABA_problem#Tagged_state_reference.

**Comment by c0m0r1** [comment]
I considered both solutions(tagged pointer/list traverse) first but I rejected them since a small bit of tag doesn't guarantee ABA-safeness and list traverse seems too inefficient.
Thanks!
