### ISSUE TITLE
[Question] HW6 grading server shows No on SUCCESS field for full credit submission

### ISSUE THREAD

**Issue by c0m0r1** [kaist-cp/cs431#563]
I have trouble on submit the HW6 to the course website.
The submission log says the submitted code passes all tests and gets full credit.
```
...
2. Running synchronization tests...

running 1 test
test sync::try_protect_collect_sync ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 0.05s


running 1 test
test sync::protect_collect_sync ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 0.26s


running 1 test
test sync::shield_drop_all_hazards_sync ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 0.01s

Score: 100 / 100
```
However, the log also prints return code `1`, and the `SUCCESS?` field shows `NO` for it.
```
Input
hw6.zip (submitted at 2021-12-05 21:22:37)
Return code
1
```
![submission](https://user-images.githubusercontent.com/42940224/144746877-0e9a31ac-0d92-4f8e-95dc-54b40e2deb54.PNG)

Is it still valid submission? or is there any problem with the submitted file or implementation?
(I remember there's a bunch of diff results and warnings on the submission log and I wonder if one of them is the cause.)

Thanks.

**Comment by jeehoonkang** [comment]
@c0m0r1 I just fixed it. Would you please try again?

**Comment by c0m0r1** [comment]
I succeeded to get full credit with the same submission file.
Thanks!
