### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by Gyubin-Lee** [kaist-cp/cs431#568]
I cannot connect to the cp-service@kaist.ac.kr from the afternoon. Is it my own problem? or is there any problem with server?

**Comment by Gyubin-Lee** [comment]
I think VS Code Server raises some problem. However, it has no problem with VS Code Server until yesterday. Why is it happen?

**Comment by kaist-kihwan** [comment]
I experienced that kind of problem multiple time and I know how to fix it. Connect to the server with your shell(e.g. cmd) and delete all files under .vscode/bin folder. The important point is you must use shell, NOT vscode. Also, sometime, .vscode directory is hidden. Just use cd command.

**Comment by Gyubin-Lee** [comment]
Do you know the path of .vscode? I cannot find it... @kaist-kihwan

**Comment by Gyubin-Lee** [comment]
Do you know the path of .vscode/bin? I found .vscode in cs431 folder but there is only launch.json...

**Comment by jeehoonkang** [comment]
- @Gyubin-Lee try `~/.vscode` or `~/.vscode-server`.
- If you cannot remove a directory, which is probably due to a bug in NFSv4, you can `mv dir-to-delete somewhere-else`.

**Comment by Gyubin-Lee** [comment]
The problem are now solved! Now it works well. Thanks for @jeehoonkang  and @kaist-kihwan :)
