### ISSUE TITLE
[Question] When removing B in lock-coupled linked list, why can't we release A's lock first?

### ISSUE THREAD

**Issue by vilotgit** [kaist-cp/cs431#569]
During the lecture for lock-coupled linked list (specifically, slide 80), professor told us that, when removing node B between A and C, releasing A's lock before releasing B's lock and freeing B will result in a bug. I tried to think of a problematic situation, but I couldn't think of any. Can you give us some hints regarding this?

**Comment by tomtomjhj** [comment]
I think it's safe to release A's lock at any point after writing `A.next = C`

**Comment by vilotgit** [comment]
Oh yes. Professor answered this question during class. He said that there might be problems if the removing thread wants to continue traversing, but it shouldn't really result in a bug. Thanks!
