### ISSUE TITLE
[Homework 5] About submission for HW5

### ISSUE THREAD

**Issue by yj-han** [kaist-cp/cs431#570]
I submitted HW5 to gg. However, I found the log from the submission page a bit strange. In the log, it said 
`test insert_concurrent ... [0;31m[1mTest timed out: cargo_asan test --release --test split_ordered_list insert_concurrent[0m`, so I ran the following command on CS431 server to reproduce the error.

```sh
RUSTFLAGS="-Z sanitizer=address" \
RUSTDOCFLAGS="-Z sanitizer=address" \ 
cargo +nightly test --target x86_64-unknown-linux-gnu --release --test split_ordered_list insert_concurrent
```

However, my codes pass the upper test even if I tried it multiple times. The result says
```sh
running 1 test
test insert_concurrent ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.46s
```

Is there anything wrong with my command, or is there any chance of running consecutive commands make errors while running only one command does not?

**Comment by Gyubin-Lee** [comment]
I got same problem in `cargo_asan test --release --test split_ordered_list` too

**Comment by tomtomjhj** [comment]
Hmm, our implementation consistently gets full grade on gg. Can you try submitting again?

**Comment by Gyubin-Lee** [comment]
I have submitted same (full credit in cp-kaist server) code several times. However, for each trial, there are all different `timeout` error in gg.

trial 1
`0;31m[1mTest timed out: cargo_asan test  --test split_ordered_list stress_concurrent[0m`

trial 2
`0;31m[1mTest timed out: cargo_asan test --release --test split_ordered_list insert_concurrent[0m`

trial 3
`0;31m[1mTest timed out: cargo_asan test --release --test split_ordered_list log_concurrent[0m`

For these three cases, tasks are different but runners are all cargo_asan. I want to debug my code but in cp-kaist server, but it gives me full credit so I can't figure it out what is the problem in my code. Why is it happen? 🤷‍♂️

**Comment by tomtomjhj** [comment]
gg runs that script without any modification. Can you send your hw5.zip to jaehwang.jung@kaist.ac.kr?

**Comment by Gyubin-Lee** [comment]
I just send you my HW5 file! @tomtomjhj

**Comment by Gyubin-Lee** [comment]
Oh, finally I got full credit on the gg! But It is weird why I got error before this submission. Just ignore my mail and I will cancel my e-mail. @tomtomjhj

**Comment by yj-han** [comment]
I think my code makes timeout error at some point. I will close this issue and work on it again!
