### ISSUE TITLE
How can we make Hazardbag pointer mutable to use NonNull::new

### ISSUE THREAD

**Issue by bronte000** [kaist-cp/cs431#572]
I have some trouble with creating new HazardSlot inside the HazardBag member function.

```rust
impl HazardSlot {
    fn new(root: NonNull<HazardBag>) -> Self {
        Self {
            root,
            hazard: AtomicUsize::new(0),
            next: ptr::null(),
            next_available: AtomicPtr::new(ptr::null_mut()),
        }
    }
```

![image](https://user-images.githubusercontent.com/48073703/145327351-70e23e52-388d-485f-bc44-76a757bea0e6.png)
It seems that we need NonNull<HazardBag> to create new Hazardslot.
I read the documentation of NonNull(https://doc.rust-lang.org/stable/std/sync/atomic/struct.AtomicPtr.html#method.compare_and_swap).
I think there is no other way to make NonNull<HazardBag> except using NonNull::new(mut& pointer).

But, this function requires mutable pointer of HazardBag.
Since member functions of HazardBag only receive constant pointer as below,
`fn acquire_slot(&self)`
I can't use NonNull::new() with self(HazardBag).

How can I create HazardSlot? 
I tried several ways (direct conversion and else) but can't convert &HazardBag to mutable pointer.
Also, I think converting shared pointer to mutable pointer should not be allowed...
How can I use HazardSlot::new() with constant HazardBag...

**Comment by tomtomjhj** [comment]
I think you're working with the outdated template code. Please rebase onto the latest version. In the latest version, `HazardSlot::new` doesn't take the pointer to the bag. 

Anyway, you can convert `&T` to `NonNull<T>` by `x.into()`. This works thanks to https://doc.rust-lang.org/core/ptr/struct.NonNull.html#impl-From%3C%26%27_%20T%3E and https://doc.rust-lang.org/core/ptr/struct.NonNull.html#impl-Into%3CU%3E.
Or you can do something like this: `NonNull:new(x as *const _ as *mut HazardBag)`.

**Comment by bronte000** [comment]
I rebased my code and it now works! Thank you for fast response. I'll close this issue.
