### ISSUE TITLE
The meaning of 'store-load fence' in SMR slide

### ISSUE THREAD

**Issue by Gyubin-Lee** [kaist-cp/cs431#575]
In the[ lecture node of SMR](https://docs.google.com/presentation/d/1cJhqCDQVo_R0RDRiRIyNqJQNBdQ8zAw-/edit#slide=id.p7), it says that HP is not fast because it should issue 'store-load fence' for synchronization.

Is it okay to understand 'stroe-load fence' as a SC fence in [here](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g47700261b6_13_13)?
Or is there any difference between store-load fence and SC fence?

**Comment by tomtomjhj** [comment]
yes SC fence also known as store-load fence.

**Comment by Gyubin-Lee** [comment]
Thank you for your answer!
