### ISSUE TITLE
About insert() in lock-free linked list

### ISSUE THREAD

**Issue by Gyubin-Lee** [kaist-cp/cs431#578]
I was studying `insert()` function of lock-free linked list in [here](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L310), and I felt something strange in this implementation(Maybe I misunderstood something)

Suppose current list looks like
`... -> [3] -> [4] -> [6] -> ... `(the integer inside the "[ ]" means the key of the node), and the expected shape of the list after insertion is `... -> [3] -> [4] -> [5] -> [6] -> ... `

If I want to insert a node with key 5, first I need to create a new node with [L314](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L314)

then I call `self.find()` in [L284 ](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L284). Maybe the result is
```
found: false
cursor:
    prev: reference to [4] -> [6]
    curr: Shared pointer to [6] 
```

and now, found is false, so `cursor.insert(node, guard)` in [L219](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs#L219) will be called.

However, in the implementation of `cursor.insert()`, cursor's `prev` field is being CASed from `self.curr` to the `input node`. I think It only changed the value of `self.curr`, but it does not change the node [4]'s next pointer(It should be changed into `-> [5]` from `-> [6]`)

Am I correctly understanding the implementation of `insert()`? Or did I misunderstand something?

**Comment by drzix** [comment]
I'm not sure if it understand your question correctly. At that time, as you said, cursor's `prev` is the **reference** to [4]'s `next` field. By CASing it, it is changed to [6] to [5] (if CAS is successful). Note that we don't CAS cursor's `prev` field.

**Comment by Gyubin-Lee** [comment]
Oh, I got it! Thanks for your answer :)
