### ISSUE TITLE
[HW6] About module 'loom'

### ISSUE THREAD

**Issue by Gyubin-Lee** [kaist-cp/cs431#579]
I use `get_mut()` function in my drop function and it works well in the test `1. Running basic tests...`. However, in the next test `2. Running synchronization tests...`, build is failed with this message.

` method not found in 'loom::sync::atomic::AtomicPtr<HazardSlot>'`

So I searched about module loom and I found this [document](https://docs.rs/loom/0.5.1/loom/sync/atomic/index.html). What is the purpose of using loom and how can I use `get_mut()` in the loom environment? Or, should I fix the code to not use `get_mut()`?

**Comment by tomtomjhj** [comment]
Loom enumerates possible executions (but not exhaustively) of the code in the relaxed memory model. This is useful because many concurrency bugs can't be reliably detected with ordinary testing.

It seems that Loom indeed doesn't support `get_mut`. So please use `load(Relaxed)` instead.

**Comment by Gyubin-Lee** [comment]
Oh, I'll use load(Relaxed). For now I will close this issue but if I get another trouble related to loom, I will reopen it. Thanks
!
