### ISSUE TITLE
[Question] The coverage of the final exam

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/cs431#580]
Hi! 😁
Could you specify the coverage of the final exam please?
I guess
- slides 73 ~ 107 (from Key ideas of concurrent data structure) + corresponding videos (including RustBelt video)
- a separate slide : Garbage collection for concurrent data structures + corresponding videos
- programming assignment 3 ~ 6?

**Comment by jeehoonkang** [comment]
@kimjungwow yeah, that's correct.
