### ISSUE TITLE
[HW6] About counter_sleep()

### ISSUE THREAD

**Issue by Gyubin-Lee** [kaist-cp/cs431#581]
I'm stuck on debugging `counter_sleep()` in [here](https://github.com/kaist-cp/cs431/blob/main/homework/tests/hazard_pointer.rs#L54). 

For each test, sometimes it success and sometimes it failed with this kind of message
```
thread 'counter_sleep' panicked at 'assertion failed: `(left == right)`
  left: `65531`, // the value of left is all different for the test but it always lower than 65536(1024 * 16)
 right: `65536`', tests/hazard_pointer.rs:91:5
```
I tried to figure out what is happened in the code but I'm not sure why it occurred. (I passed all other tests in test session 1) Can you give me some advise what is the role of `counter_sleep()` and why it can be occured?

**Comment by tomtomjhj** [comment]
Try removing `retire` and `collect` from the test code so that no memory block is recycled. If the test passes after this change, then the problem is probably due to the ABA problem, which means that your implementation fails to protect the pointers from being reclaimed.

**Comment by Gyubin-Lee** [comment]
I'll try it. Thanks for your answer!
