### ISSUE TITLE
[Question] Is the assignment "assignment 01 (late)" in gg website corresponding to another class (CS220)?

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/cs431#584]
Is the assignment **"assignment 01 (late)"** in https://gg.kaist.ac.kr/course/9/ corresponding to another class (CS220)?
- https://gg.kaist.ac.kr/assignment/45/

![image](https://user-images.githubusercontent.com/20202266/145719877-7a6f93ca-ed73-4fdc-8684-0e396592ced0.png)

**Comment by jeehoonkang** [comment]
Thanks! it's now moved to cs220.
