### ISSUE TITLE
[Question] drop protect the pointer in stack, while queue does not.

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#586]
1. 
In the drop function of lock free stack: https://github.com/kaist-cp/cs431/blob/main/lockfree/src/stack.rs#L95

it holds the valid protect guard to drop the nodes,

while in the drop function of lock free queue: https://github.com/kaist-cp/cs431/blob/main/lockfree/src/queue.rs#L164

it holds the unprotected guard.

I would like to know the reason why there are difference.

2. I have watched the video of Dr. Derek Dreyer, I can not find the relationship between the verification of linearizability and the video (It dealt with invariant and user-defined logical state. Could you specify the relationship?

**Comment by tomtomjhj** [comment]
1. Stack can use unprotected guard too.
2. Yeah that lecture doesn't specifically deal with linearizability.

**Comment by anonymous1782** [comment]
1. Thank you!

2. Then, the slide 100's title makes me be confused a little bit. Anyway, thanks for your comment!
