### ISSUE TITLE
[Question] Should the new node be into_shared in MSQueue::push()?

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/cs431#587]
Hi! 😊

I have a question about `MSQueue::push()`.

https://github.com/kaist-cp/cs431/blob/bcc8dc4a3afeafbfba12ca97a0d8512e01a75782/lockfree/src/queue.rs#L77

Since the "new" argument of `compare_exchange` could be either `Shared` or `Owned` ([docs](https://docs.rs/crossbeam-epoch/latest/crossbeam_epoch/struct.Atomic.html#method.compare_exchange)) I wonder why the new node should be `into_shared()` as shown in `queue.rs:L77`.

Thanks in advance!

**Comment by tomtomjhj** [comment]
The CAS for `// try to move the tail pointer forward` also uses `new`, so it shouldn't be an owned pointer.
