### ISSUE TITLE
[Question] HW6 synchronization test case

### ISSUE THREAD

**Issue by HEALWON** [kaist-cp/cs431#592]
I'm debugging for 3 synchromization test cases (try_protect_collect_sync, protect_collect_sync, shield_drop_all_hazards_sync).
For simplicity, I'm using Acquire-Release ordering for all atomic instruction.

In the case of try_protect_collect_sync, failure is like this:
```
thread 'sync::try_protect_collect_sync' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `123`', tests/hazard_pointer.rs:253:25
```
```
...
            let th = {
                let atomic = atomic.clone();
                thread::spawn(move || {
                    let mut local = atomic.load(Relaxed) as *const usize;
                    if local.is_null() {
                        return;
                    }
                    let shield = Shield::default();
                    if shield.try_protect(&mut local, &atomic) {
                        // safe to deref a valid pointer via a validated shield
                        assert_eq!(unsafe { *local }, 123); <- fails!
                    }
                })
            };

            // unlink, retire, and collect
            let local = atomic.load(Relaxed);
            atomic.store(ptr::null_mut(), Relaxed);
            retire(local);
            collect(); <- A
            th.join().unwrap();
```
I'm reasoning from the `println!` result and I think the error comes from this situation:
`try_protect` success, so `local` is in hazard pointer list(it's node insertion is like treiber's stack). However, `local` is freed in the `collect()` (A)  before assertion, because it cannot find `local` in the hazard pointer llist.

However, as I said, I'm using acquire-release ordering all time... Can you give any advise?

Also, can I use `all_hazard()` in the `collect()`?

**Comment by tomtomjhj** [comment]
Your interpretation looks correct. However, release-acquire cannot enforce such an ordering. Please see the documentation in hazard_pointer/mod.rs.

> Also, can I use all_hazard() in the collect()?

Yes you should use it

**Comment by HEALWON** [comment]
It was a SILLY question.. I found that explanation and solved it. Really thanks for your advice.
