### ISSUE TITLE
[Homework 5] My growable_array pass cargo and cargo_tsan but it takes 326s.

### ISSUE THREAD

**Issue by kaist-kihwan** [kaist-cp/cs431#593]
I thought my implementation goes infinite loop or deadlock in the first place. But I notice my implementation pass for `cargo` and `cargo_tsan`.
`cargo_asan` tolds me it just have some memory leaking issues.
Is it possible that memory leaking makes growable_array too slow, so it takes more than 5 minutes?
Is there any possibility that there exists some other hidden issue in my implementation?

**Comment by tomtomjhj** [comment]
Hmm That's interesting. I guess the leak might be related if the leak is huge, since AddressSanitizer has to track the leaked memory blocks. Try fixing the leak first.

**Comment by kaist-kihwan** [comment]
Can you help me to fix memory leaking?
`cargo_asan` raise memory-leak when the height of GrowableArray needs to be more than or equal to 2.
For example,
```
let list = ArrayMap::<usize>::default();
let guard = pin();
assert_eq!(list.insert(&10250, 10250, &guard), Ok(()));
```
When I run this test, there's leaked memory which is allocated from `Owned::new(Segment::new())`
That value is used for CAS with `AtomicUsize` and new `Segment` to create segment from already grown array while running `get`.
I also handle failure case of CAS and drop shared segment which is not used by `.into_owned().into_box()`
I believe my implementation of `Drop` is correct, because when I restrict some segments of array, there's no memory leaking issue.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs431/issues/576#issuecomment-990620920 ?

**Comment by kaist-kihwan** [comment]
@tomtomjhj 
I tried to drop segment manually by `mem::drop(segment.into_owned().into_box().inner)` but it doesn't work.
Should I do something more?
+) My implementation guarantees `segment`, which is allocated from the line where `cargo_asan` tolds me, is all zeroed. So I don't need to traverse.

**Comment by tomtomjhj** [comment]
>  I tried to drop segment manually by mem::drop(segment.into_owned().into_box().inner) but it doesn't work.

Dropping an `AtomicUsize` does nothing. So dropping `...inner` doesn't do anything meaningful. So the above code does nothing more than `drop(segment.into_owned())`.

> segment, which is allocated from the line where cargo_asan tolds me, is all zeroed.

This means that the zeroed child segment is leaked, right? Then it's likely that `drop(parent_segment.into_owned())` doesn't deallocate the child segment.

**Comment by kaist-kihwan** [comment]
The problem was `SEGMENT_LOGSIZE`. In my for-loop inside the `drop` implementation, I use `SEGMENT_LOGSIZE` instead of `1 << SEGMENT_LOGSIZE`. Sorry and thank you.

**Comment by kaist-kihwan** [comment]
Okay, it's going worse. Now I pass all `cargo`,`cargo_asan`, `cargo_tsan` but `stress_concurrent` takes 600s.
How can I fix this?
+) Since I'm using only CAS to attach segments to the growable array, I strongly argue that my implementation is lock-free.

**Comment by loneo** [comment]
I had same problem, and in my case, it was the count variable in the insert and delete that was the problem. Originaly I used loop and compare exchange to add and subtract from the count, but there was much more simpler atomic function for just adding and subtracting. 
It was the solution for me, and if you implemented the same way, it might be worth a try. Hope it helps!

**Comment by kaist-kihwan** [comment]
@loneo Oh you are talking about `split_ordered_list.rs`, right? I'm having trouble with `growable_array.rs`

**Comment by loneo** [comment]
Oh sorry... I got confused

**Comment by tomtomjhj** [comment]
> Since I'm using only CAS to attach segments to the growable array, I strongly argue that my implementation is lock-free.

Using CAS doesn't imply lock-free. For example, acquiring lock is not lock-free.

Can you provide a brief outline of your algorithm? Specifically, what loops do you have?

Also, how do you handle the case that the height grows ≥ 2 steps, e.g. 1 to 3?

**Comment by kaist-kihwan** [comment]
@tomtomjhj What I mean by CAS is,
```
let old = atomic.load();
atomic.compare_exchange(old, new);
```
If this CAS success, there's progress.
If this CAS fails, it implies some thread success CAS and it is also progress.
That's why I believe my code is look-free.

My implementation is as follows.
1. count desired height of the array to grow from the value of the index.
2. make a new segment that `segment[0]=self.root`.
3. try `self.root.compare_exchange(old, Pointable(segment).with_tag(current_tag+1))` to make a new segment as new root of array.
4. do step 3 until self.root.load().tag() is greater than or equal to desired height. (I use `loop`-loop, but I think it can be replaced by `for`-loop)
5. try to search for a location of the index. Start from the root. If there exists a pointer to segment, go to it. If not, make a new segment and attach it. Do this root.tag() times. (I use `for`-loop)
6. return the result.

**Comment by tomtomjhj** [comment]
Hmm, looks correct to me. So the previous version that leaks memory passed all tests except cargo_asan due to leak and timeout, and the new version without leak passes all tests except stress_concurrent due to timeout. Right? Then I guess the slowdown might be due to the stuff that you added to prevent the leak.

**Comment by kaist-kihwan** [comment]
Still, time out occurs and I think there's no way to fix this until 12/20. Thank you for your help.
