### ISSUE TITLE
[Question] A question about slides p50

### ISSUE THREAD

**Issue by night-cruise** [kaist-cp/cs431#598]
After the thread-1 executed `Y.store(1, release);`, the thread-1 view should point the `Y = 1`. But the thread-2 view should still points the `Y = 0`, because the thread-2 does not know what happened to the thread-1, so how does the thread-2 know `Y = 1` when executing `if Y.load(acquire) {}` ? According to my understanding, a thread can only access its current view, is it right?

the link: [Promising semantics 3: views (3/4)
](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g47700261b6_9_0)

**Comment by Lee-Janggun** [comment]
Sorry for the insanely late reply.

In the animations of the slide, we are considering the case when load returns 1, i.e., when the execution order is `Y.store(1, release) -> Y.load(acquire)`. Hence, the second thread will read the message done by the first thread, so its view will be updated to that of the message.

If the execution order was `Y.load(acquire) -> Y.store(1, release)`, then indeed the value of Y will still be 0. Then, the `assert` will never be checked, so the program will still succeed.

**Comment by night-cruise** [comment]
> Sorry for the insanely late reply.
> 
> In the animations of the slide, we are considering the case when load returns 1, i.e., when the execution order is `Y.store(1, release) -> Y.load(acquire)`. Hence, the second thread will read the message done by the first thread, so its view will be updated to that of the message.
> 
> If the execution order was `Y.load(acquire) -> Y.store(1, release)`, then indeed the value of Y will still be 0. Then, the `assert` will never be checked, so the program will still succeed.

Thank you for your answer. Now I have understood this problem.
