### ISSUE TITLE
Quizzes for 2022 Fall

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#602]

**Comment by jeehoonkang** [comment]
2022/08/29: https://gg.kaist.ac.kr/quiz/118/

**Comment by jeehoonkang** [comment]
2022/09/05: https://gg.kaist.ac.kr/quiz/120/

**Comment by metamon123** [comment]
@jeehoonkang If you don't mind, could you please consistently upload new quizzes in this issue before deadline? There can be someone who rely on the update of this issue, because gg.kaist.ac.kr doesn't have any notification system.

**Comment by Allgot** [comment]
Actually I have forgotten.. ;(

**Comment by jeehoonkang** [comment]
@metamon123 @Allgot sorry for the omission. I'll not count today's quiz in the evaluation.

**Comment by jeehoonkang** [comment]
2022/09/19: https://gg.kaist.ac.kr/quiz/127/

**Comment by lhi0901** [comment]
Sorry to bother you, but I wonder whether there is no quizz for today's class. If there is, sorry for my impatience.

**Comment by Lee-Janggun** [comment]
2022/09/26: There will be no quiz for today.

**Comment by azretkenzhaliev** [comment]
Sorry for the silly question - why the quizzes are not being posted?

**Comment by jeehoonkang** [comment]
2022/09/28: no quizzes today. Sorry for a late annoucement.

**Comment by jeehoonkang** [comment]
2022/10/04: https://gg.kaist.ac.kr/quiz/131/

**Comment by jeehoonkang** [comment]
2022/10/05: https://gg.kaist.ac.kr/quiz/132/

**Comment by azretkenzhaliev** [comment]
Professor @jeehoonkang, are there going to be quizzes?

**Comment by jeehoonkang** [comment]
@azretkenzhaliev we'll have a quiz when the snow falls.
