### ISSUE TITLE
[Question] Default password for server is not working

### ISSUE THREAD

**Issue by boingkiri** [kaist-cp/cs431#603]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Hello for all in CS431.

I have question, which is came from silly of me I guess, but the default password for accessing provided server is not working (at least for me).

I tried to access the provided server with VS code SSH connection.
but I got permission denied when access the server with the default password.

Is there anyone who is suffered by the same problem? and how to deal with it?

**Comment by Ariaspect** [comment]
I'm having the same issue.
Default pwd(123454321) won't work for me.

**Comment by jeehoonkang** [comment]
- Did you register for the course today? Maybe it has not been applied.
- Otherwise, please send me an email.

**Comment by shapoid** [comment]
I have same problem even if I registered the course.

**Comment by jeehoonkang** [comment]
I think now the problem has been resolved. Would you please try again?

**Comment by zprime0920** [comment]
@jeehoonkang It's resolved! Thanks a lot!

**Comment by KAIST16-Ryu** [comment]
Thank you for your reply!

The problem has been solved now.

Thank you

- Eojin Ryu -

-----Original Message-----

**Comment by jeehoonkang** [comment]
Closing, as it seems the problem has been resolved. If you're experiencing the same problem, please feel free to reopen this issue.
