### ISSUE TITLE
[Homework 1] Parallel Web Server with Cache (due: 2022-09-25 23:59:59)

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs431#606]
Implement a parallel web server with cache.

- Read [this manual](https://github.com/kaist-cp/cs431/tree/main/homework) for general advice on homework. The manual contains skeleton code that serves as a starting point. You're going to fill out the `todo!()`s.
    + **IMPORTANT**: don't fork this repository.  It'll be public!
- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/hello_server.md).

- You can grade your solution yourself by running `./script/grade-1.sh` in the `homework` directory. If the server's evaluation results differ from your own evaluation results, please let us know.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/61/). You can create the zip to submit as follows:

  ```sh
  cd cs431/homework
  ./scripts/submit.sh
  ls ./target/hw-hello_server.zip     # file to submit
  ```

- **IMPORTANT**: only the last submission counts.  Please make sure the last line of the "log" says "Score: ?? / ??".

**Comment by Lee-Janggun** [comment]
`cargo_tsan` currently fails, even with correct implementation, so please ignore it for now.
https://github.com/kaist-cp/cs431/issues/607

**Comment by Lee-Janggun** [comment]
**Update**: Rust is fixed to an old nightly due to a thread sanitizer bug #607 . Please rebase on top of https://github.com/kaist-cp/cs431/commit/e0c5a2218f5dbd6430b02d8fa4f648a504f3af1d.

**Comment by Lee-Janggun** [comment]
**Update**: I made a proper fix for #607 in https://github.com/kaist-cp/cs431/commit/46df4c1aa1657ae25889e1cb538bff09223b7d9e. Please rebase your homework on top of it.

**Comment by cskwak99** [comment]
@Lee-Janggun Can you please check the cp-service.kaist.ac.kr server state? Me and my friends cannot access to it - Connection Timeout -  from an hour ago.

**Comment by Lee-Janggun** [comment]
@cskwak99 can you try again now?

**Comment by cskwak99** [comment]
> 

Now it works well, thank you!

**Comment by cskwak99** [comment]
> @cskwak99 can you try again now?

Now it works well! Thank you.

**Comment by Lee-Janggun** [comment]
**Update**: I have enforced the linters in the grading script with some tweaks. (https://github.com/kaist-cp/cs431/commit/0fab2c730a6c632ec673e7a06afb9614d152ca77). 
- Now you should not see the >100 warnings that appeared when compiling your homework or when submitting.
- On the other hand, you must fix the warnings that appear to be able to submit.
- Enforcing a linter forces one to write more ergonomic and correct Rust code (e.g, the linter catches when [references are dropped](https://rust-lang.github.io/rust-clippy/rust-1.56.0/index.html#drop_ref), which is a no-op).

**Comment by smpak19** [comment]
It seems curl is not installed yet. While installing rustup in the server, curl: command not found error appears.

**Comment by Lee-Janggun** [comment]
@smpak19 Can you try again?

**Comment by smpak19** [comment]
@Lee-Janggun Thank you! Solved :)

**Comment by CastOrdo** [comment]
I found out that grade-1.sh no longer exists in the scripts folder. What would be the change file name of it?

**Comment by Lee-Janggun** [comment]
> I found out that grade-1.sh no longer exists in the scripts folder. What would be the change file name of it?
> 
> 

I updated the documentation file as well, so please check it.

**Comment by dripcharacter** [comment]
I was using cs431 server according to README at kaist-cp/431 and it worked before 9/18 7-8:pm. But suddenly I can't access cs431 server via vscode ssh remote. And error is like picture1
![vscodeserver_install_fail](https://user-images.githubusercontent.com/53895663/190917648-7504893d-2a9d-419b-b72d-340d2b9a6dc6.PNG)
(picture1)

So, I checked ssh-key but there is my ssh-key in authorized_keys.
![ed25519incs431server](https://user-images.githubusercontent.com/53895663/190918148-fad070b9-38e1-40be-a2ba-44cdfd84dda7.PNG)
(picture2)

After I googled it, I found answer that I have to delete .vscode-server but I can't delete it like picture3.
![cannotdeletevscodeserver](https://user-images.githubusercontent.com/53895663/190918198-ec0af552-7d46-47ae-8f5a-5ec1b63cd6c8.PNG)
(picture3)
Do you know what should I do?

**Comment by Lee-Janggun** [comment]
@dripcharacter 
1. Please open a separate issue for this, and don't use images.
2. The server can lag when deleting many files at once. Do you still have the same problem after disconnecting/reconnecting?

**Comment by dripcharacter** [comment]
First, sorry for mismaking issue and using images.
After doing with https://stackoverflow.com/questions/67374506/visual-studio-code-remote-ssh-no-longer-working-waiting-for-server-log, I can connect to vscode ssh to cs431 server. Thank you.
