### ISSUE TITLE
[Question] SSH Public Key Authentication

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#608]
I tried to register public SSH keys to server.
Following tutorial (https://serverpilot.io/docs/how-to-use-ssh-public-key-authentication), I successfully generate an SSH key pair.

Then I tried next step in tutorial with method 2: Manual Configuration because I use Windows.
I made ~/.ssh and ~/.ssh/authorized_keys same as tutorial.
And I copy my public key to authorized_keys with following code.
$ cp id_rsa.pub ~/.ssh/authorized_keys

But when I try to log in the server, it still requires me a password.
Also, when I try to check authorized_keys folder with
$ cd ~/.ssh/authorized_keys
it says '-bash: cd: authorized_keys: Not a directory'

* I did same thing with ed25519, but it returned same result.

How can I fix this problem?
Thank you.

**Comment by ichianr** [comment]
Could you check the `authorized_keys` again? It should be a plaintext file containing public keys in each line (it's not a directory.)

**Comment by jeehoonkang** [comment]
you should specify the port 13002 for the `ssh-copy-id` command.

**Comment by ichianr** [comment]
Did you try to connect the server with `-i path_to_private_key` option?
I guess it's not a server's problem, as I can log in with my key file on Windows using PuTTY.

**Comment by DaeyongKwon98** [comment]
With '$ ssh-copy-id -p 13002 s20170040@cp-service.kaist.ac.kr', it returns

'/usr/bin/ssh-copy-id: WARNING: All keys were skipped because they already exist on the remote system.
                (if you think this is a mistake, you may want to use -f option)'

So I use -f option, '$ ssh-copy-id -f -p 13002 s20170040@cp-service.kaist.ac.kr'
(I also test with '$ ssh-copy-id -f -i ~/.ssh/id_rsa -p 13002 s20170040@cp-service.kaist.ac.kr' and
'$ ssh-copy-id -f -i ~/.ssh/id_rsa.pub -p 13002 s20170040@cp-service.kaist.ac.kr', but everything works same.)
and returns

'Number of key(s) added: 1

Now try logging into the machine, with:   "ssh -p '13002' 's20170040@cp-service.kaist.ac.kr'"       
and check to make sure that only the key(s) you wanted were added.'

But it still doesn't work...
Perhaps it would be better to proceed without solving this problem, because I only need to solve it before March. :(

**Comment by Lee-Janggun** [comment]
Would you post the error messages as well? I have never tried `ssh` with a windows, so it is extremely difficult for me to help you without knowing the exact kind of error you see.

**Comment by ichianr** [comment]
`-i` option is still omitted for `ssh`. Can you try `ssh s20170040@cp-service.kaist.ac.kr -p13002 -i path_to_private_key`?
(BTW, `ssh-copy-id -i path_to_public_key` is correct anyway.)

**Comment by DaeyongKwon98** [comment]
There is no error message, and only problem is server require me a password.

When I tried to copy and paste my public key to authorized_key with '$ vi authorized_key'

E325: ATTENTION
Found a swap file by the name ".authorized_keys.swp"
          owned by: s20170040   dated: Tue Aug 30 12:41:12 2022      
         file name: ~s20170040/.ssh/authorized_keys
          modified: YES
         user name: s20170040   host name: kaist-cp-cs431
        process ID: 141837
While opening file "authorized_keys"
             dated: Wed Aug 31 03:48:24 2022
      NEWER than swap file!

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same

    file when making changes.  Quit, or continue with caution.       
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r authorized_keys"  
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file ".authorized_keys.swp"
    to avoid this message.

Swap file ".authorized_keys.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort:

it returns this message above, and I press (E)dit anyway and proceed. Is it a problem?

**Comment by Lee-Janggun** [comment]
Is the password the server requested (1) the server password that you reset from `123454321` or (2) the password to your ssh key? If it is (2), then it is natural.

If you don't want to do (2), then you should set up your ssh key without a password (just press enter on the enter password prompt)

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen the issue if you have further questions!
