### ISSUE TITLE
About installing rustup

### ISSUE THREAD

**Issue by jonge-1124** [kaist-cp/cs431#610]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

(YOUR QUESTION HERE)
After connecting to the given server, can we install rustup on the individual server to implement the rust code?

**Comment by Lee-Janggun** [comment]
Yes, see #609

**Comment by Lee-Janggun** [comment]
Instructions added in https://github.com/kaist-cp/cs431/commit/bf859e018bcc4d6cabb7052de049cfbd5a00449f
