### ISSUE TITLE
[Question] SSH connection error

### ISSUE THREAD

**Issue by TriangleYJ** [kaist-cp/cs431#612]
Hello, I checked that ssh connection worked yesterday, but today connecting to ssh is not working.
It returns the error `ssh: connect to host cp-service.kaist.ac.kr port 13002: No route to host`
How can I fix this problem?
Thank you.

**Comment by jeehoonkang** [comment]
Sorry for the inconvenience. I believe it's now resolved.

If the problems continue, then I'll switch to another server later.

**Comment by TriangleYJ** [comment]
I think the problem happens again.. It worked a few hours ago.

**Comment by Lee-Janggun** [comment]
@TriangleYJ is it still happening?

**Comment by TriangleYJ** [comment]
Yes, I think it is still not working..
`ssh: connect to host cp-service.kaist.ac.kr port 13002: No route to host`
The same ssh command worked well a days ago.

**Comment by smpak19** [comment]
It happens same for me. `ssh: connect to host cp-service.kaist.ac.kr port 13002: Network is unreachable` in Mac OS

**Comment by jeehoonkang** [comment]
Hi all,

Sorry for the inconvenience. To resolve the server problem, I just switched the CS431 server to new hardware.
- If you connect to a new SSH connection, it will warn you that it's an unknown host. Please edit your `~/.ssh/known_hosts` to resolve it.
- Your password is reset to `123454321`.
