### ISSUE TITLE
[Homework 3] Lock-Coupling Linked List (due: 2022-10-30 23:59:59)

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs431#617]
Implement a Linking List with fine-grained lock coupling.

- Read [this manual](https://github.com/kaist-cp/cs431/blob/main/homework/README.md) for general advice on homework.

- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/list_set.md).

- Use [skeleton code](https://github.com/kaist-cp/cs431/tree/main/homework/src/list_set.rs) as a starting point, and fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- Submit your [`list_set.rs`](https://github.com/kaist-cp/cs431/tree/main/homework/src/list_set.rs) [here](https://gg.kaist.ac.kr/assignment/64/).

**Comment by Lee-Janggun** [comment]
The due date has been updated from 11/04 -> 10/23.

Since this homework deals with midterm material, I do recommend at least trying it out before the midterm

**Comment by deepkyu** [comment]
Hi @Lee-Janggun 
First of all, thank you always for your clear explanation.

I found that the professor changed the midterm range from slide 1-48 (from #655),
so this homework may be out of range for midterm exam.

I totally agree that the homework due date could be independent from the course schedule,
but just in case I kindly ask you if there is any change in the due date of Homework 3.

**Comment by deepkyu** [comment]
BTW, it would be better if you change the year in the issue title from _2021_ to **2022** 😄

**Comment by Lee-Janggun** [comment]
@deepkyu Thank you for notice on the due date! Why did I make that mistake... :p.

Regarding the range, this is still midterm material, the last few slides deal with fine grained lock coupling.

Regarding the due date, it is a bit more stricter then we anticipated since the course is going a bit slow. We'll discuss if it is possible to extend it a week.

**Comment by deepkyu** [comment]
@Lee-Janggun, thank you for your consideration 👍🏻

**Comment by Lee-Janggun** [comment]
**UPDATE**: Since lock coupling is the topic of this week, the deadline is extended to 10/30, since we wanted to give two weeks for the homework after the material was dealt with in class.
