### ISSUE TITLE
[Homework 5] Hash Table (due: 2022-12-19 23:59:59)

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs431#619]
Implement a concurrent lock-free Hash Table.

- Read [this manual](https://github.com/kaist-cp/cs431/blob/main/homework/README.md) for general advice on homework.

- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/hash_table.md).

- Use [skeleton code](https://github.com/kaist-cp/cs431/tree/main/homework/src/hash_table) as a starting point, and fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- Submit your code [here](https://gg.kaist.ac.kr/assignment/65/). You can create the zip to submit as follows:

  ```sh
  cd cs431/homework
  ./scripts/submit.sh
  ls ./target/hw-hash_table.zip     # file to submit
  ```

**Comment by jeong0982** [comment]
@Lee-Janggun [Link in documentation](https://github.com/kaist-cp/cs431/blob/main/lockfree/src/list.rs) is not working. Could you check it?

**Comment by Lee-Janggun** [comment]
@jeong0982 I updated the links. Can you check again?

**Comment by Lee-Janggun** [comment]
We have updated the grading script to partially allow `SeqCst`. You will still need to use more relaxed orderings to get full points.

**Comment by Lee-Janggun** [comment]
I forgot to mention it above, but since the grading script has changes, all previous submissions are nullified, so please submit again.

**Comment by kingdoctor123** [comment]
I resubmitted my answer and found that `Success?` status is stuck with `Checking...` state even if `Score: 180 / 180` is shown at the bottom of the log. (This happens only in homework 5, not in homework 6)

Could you please check this problem? Thank you in advance.

**Comment by Lee-Janggun** [comment]
@kingdoctor123 
1. can you send me your code to janggun.lee@kaist.ac.kr so that I can have a look?
2. does the problem also happen locally?

**Comment by kingdoctor123** [comment]
@Lee-Janggun 

1. I sent the mail right now. So could you please check it?
2. I'm now running test on local machine, and I'll let you know when it is done.

**Comment by kingdoctor123** [comment]
@Lee-Janggun For question 2, it seems there's no problem when I run the test on local machine.

**Comment by Lee-Janggun** [comment]
Update: https://github.com/kaist-cp/cs431/commit/5f7d611d4a4d3a87e2fead4a76d63adfe08c547c made the previously unsafe `Cursor::from_raw()`  into a safe `Cursor::new()`, as we realized there was no reason to make this unsafe.

This is a breaking change, and as we expected `split_ordered_list.rs` to use this API, all previous solutions will probably not work. Please adapt to this change.

**Comment by Lee-Janggun** [comment]
@kingdoctor123 We updated the grading script to be more efficient. Can you try again?

**Comment by kingdoctor123** [comment]
@Lee-Janggun I tried it once more, but I'm still having the same problem.

**Comment by Lee-Janggun** [comment]
@kingdoctor123 I tried submitting your code to gg and it worked. Can you try again?

**Comment by kingdoctor123** [comment]
@Lee-Janggun Now it works well. Thank you so much for your help.

**Comment by kangwon** [comment]
I think there is the same issue with https://github.com/kaist-cp/cs431/issues/619#issuecomment-1255041987.
The log prints score, but `SUCCESS?` is `Checking...`.
Thank you for all your assistance.

**Comment by Lee-Janggun** [comment]
@kangwon does re-submitting also not work?

**Comment by kangwon** [comment]
(I guess) it depends on the score. 
When some tests are failed, the `SUCCESS?` becomes `Yes`. 
But when all tests are succeed, the `SUCCESS?` is not changing.

**Comment by kangwon** [comment]
> I think there is the same issue with [#619 (comment)](https://github.com/kaist-cp/cs431/issues/619#issuecomment-1255041987)....

The symptom has been gone now. Thanks to fix the issue!
