### ISSUE TITLE
[Question] Request for clarification on the semantics of `ThreadPool::execute`

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs431#622]
Hello, I have a question about the expected behavior of `ThreadPool::execute`.

If the main thread calls `ThreadPool::execute` more than the number of threads in that pool, there could be two ways to handle this.

* First, it might block the main thread until a thread becomes idle.
* Second, it might not block the main thread and keep executing.

I think both implementations do 'work', and there are pros and cons for each implementation. However, in my opinion I think the first design is superior due to the following reasons:

* The time until the newly given work to be served is the same as in the first case.
* Employing the second design complicates the semantics of `ThreadPool::join` greatly. 

Let's imagine a situation like the following.
```rust
let pool = ThreadPool::new(4);
for i in 0..4 {
  pool.execute(|| { /* some function */}); // [1]
}
pool.execute(|| { /* some another function */}); // [2]
pool.join(); // [3]
``` 

If `pool.join()` is executed before `some_another_function` is executed, and all of the 4 threads created in [1] terminates before the thread created in [2] begins, `pool.join()` will return after joining 4 threads, instead of 5. Clearly there is a problem with this, because the behavior is inconsistent.

So, from the two different semantics above, which one should we follow?

**Comment by Lee-Janggun** [comment]
# Regarding design choice
- As long as the test case passes, the implementation is up to you.
- Also in designing your semantics, it may be helpful to look over the API for  [`Sender`](https://docs.rs/crossbeam/latest/crossbeam/channel/struct.Sender.html) and [`Reciver`](https://docs.rs/crossbeam/latest/crossbeam/channel/struct.Receiver.html) for crossbeam so you know what you can do.

# Regarding the example
- From the way you explained the example with the second semantics, it would hint that it is does not 'work', i.e incorrect semantics. 
- What you are missing is that your semantic of `join()` is incorrect: a `join()` must block until all closures given to the call of  `execute()` are finished. Hence, if a `join()` behaves as your explanation, it is a bug.
- Then the question is: How do we ensure such condition between `join()` and `execute()`? For that, think about how to utilize the helper functions for `ThreadPoolInner`.

**Comment by pr0cf5** [comment]
Thank you for your reply. I will maintain this issue open for a day and close it.
