### ISSUE TITLE
Midterm exam on October 17th (Mon), 13:00-14:30 in N1 102 and 111 

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs431#625]
**Please read carefully for the exam.**
 
 * **Date and Place**
   We will conduct the **midterm exam on October 17th (Mon), 13:00-14:30 in N1 102 and 111**.  (**No extension** will be given.)
* **Range**
   See https://github.com/kaist-cp/cs431/issues/654#issuecomment-1267777543
 * **Presence**
   
   * You must be **physically present** in the lecture room.
   * You must not take a break for restrooms or other reasons.
   * You may leave 30 minutes after the beginning.
 * **Supplies**
   
   * You should **bring your own laptop** to take the exam.
     If you don't any, please borrow one from the CS admin office by sending an email to Mr. Daejong Kim with me cc'ed.
   * You should have **a valid Google account** because the problem/answer sheet will be given as a Google Form.
   * You should bring your student ID card. If you don't have any, bring a government-issued ID card.
   * You may use pencil and paper, but you must not use calculators, tablets, and text editors.
 * **Screen Policy**
   On the laptop screen, you can only look at the following websites:
   
   * https://gg.kaist.ac.kr
     
     * Go to https://gg.kaist.ac.kr/course/11 and click the exam event.
     * Here, you can see the "event token" (see below).
     * Here, you can also ask questions.
       If your question is not answered for 10 minutes, please let us know.
       Your questions can be written either in English or Korean. Answers will be in English.
   * The problem/answer sheet is a Google Form
     
     * It will be announced in gg.
     * To answer the Google Form, you need to (1) log in with a Google account, and (2) fill out your KAIST email address, name, student ID, and the event token.
     * The problems will be in English. You may answer either in English or Korean.
     * Frequently save your answer.
       Google Form does not automatically save your answers unless you "submit" them.
       You are allowed to resubmit the answers as many times as you want, so it is strongly recommended for you to submit your answers frequently.
       It is your responsibility to maintain your answers reliably and we will not make any exceptions due to technical problems such as network disconnections, web browser crashes, web browser hanging, etc.
 * **Remote Participation Policy**
   
   * If you really cannot be physically present in the exam room, send an email to [jeehoon.kang@kaist.ac.kr](mailto:jeehoon.kang@kaist.ac.kr) to **ask for explicit permission for remote participation**.
     Without such explicit permission, you will be regarded as absent from the exam.
   * You should **join two Zoom rooms with two Zoom accounts**: ["Announcement" room](https://kaist.zoom.us/my/jeehoon.kang) and "CCTV" room (privately emailed).
     If you have only one account, please sign up once again.
   * Join the Announcement room with a device (probably desktop/laptop) in which you'll solve the exam problems.
     Turn off the camera and microphone.
   * Join the CCTV room with another device (probably a laptop/mobile) that observes you during the exam.
     **For the entirety of the meeting, you need to (1) turn on the camera and microphone; (2) show your hand, paper, keyboard, and monitor; and (3) turn off the speaker.**
     (For privacy concerns: please be noted that you agreed to do this at the beginning of the semester.)
     I've attached the model scene from the experienced TA below.
   * **You should be properly present in both Announcement and CCTV rooms 10 minutes before the beginning to the end of the exam.**
     If you disappear from the camera after the exam starts, we will assume that you gave up on the exam and your score will be automatically zero.
     Network disconnections and/or power outages will not be excuses. Make sure you find a place where you can get a reliable internet connection and power supply.
   * Your Zoom name should be in the form of "200711632 강지훈". Otherwise, you may be disqualified.
   * At the beginning of the exam, you will be asked to show your student card.
     Please show it in front of the CCTV camera.
   * Frequently read Announcement Zoom room's messages. We'll DM you when your CCTV doesn't work properly.
 
 ![20220608_111857](https://user-images.githubusercontent.com/1201316/172517337-57e9fada-a37d-4732-9559-05e746785c7d.jpg)

**Comment by jeehoonkang** [comment]
Superceded by https://github.com/kaist-cp/cs431/issues/655
