### ISSUE TITLE
[Question] (Is it possible to install Web browser in the server?)

### ISSUE THREAD

**Issue by KAIST16-Ryu** [kaist-cp/cs431#626]
I want to implement web server in rust book chapter 20.

To run the WebServer Code and verification, I should run rust code and run web browser in the server to check connection. But I cannot Install web browser like chrome or firefox in the server because I don't have any permission.

Anyway, it there any possible way to implement web server implementation in rust book chapter 20 using a server?

Thank you for your attention!

**Comment by woojinnn** [comment]
Why don't you use `curl` command as explained in [document](https://github.com/kaist-cp/cs431/blob/main/homework/doc/hello_server.md)?

**Comment by KAIST16-Ryu** [comment]
Thank you for your reply. Good bb!!

**Comment by Lee-Janggun** [comment]
For HW1, you should also be able to run your code in your local machine.
