### ISSUE TITLE
[Question HW1] How to define new Worker?

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#629]
In thread_pool.rs, there's no new() function in Worker.
So I make my code like

![image](https://user-images.githubusercontent.com/70640395/190919645-37d849e7-47b0-43f9-a970-6f689fe0e8a1.png)

Then following error occurs.
![image](https://user-images.githubusercontent.com/70640395/190919530-ff3be017-9397-4ba1-8621-98590f77e7db.png)

How can I handle this?
Thank you.

**Comment by ironore15** [comment]
I think you should not upload your specific source code.
Also, do not upload the errors with an image (see [comment](https://github.com/kaist-cp/cs431/issues/615#issuecomment-1235101283))

By the way, the type of `thread` field of `Worker` struct is `Option<JoinHandle<()>>`.
You should consider using `Some(...)` or `None` for `thread` field and the argument of `thread::spawn` also have to return `()`, not `Receiver`.

**Comment by Lee-Janggun** [comment]
Closing due to use of images. Please upload your code with proper markup.

**Comment by DaeyongKwon98** [comment]
Sorry for uploading source code and images :(

Anyway, I change defining new worker and push it to vector like this.
```rust
let w = Worker {id, thread: Some(thread::spawn(||{}))};
workers.push(w);
```
When I test thread_pool.rs with
`cargo test --test thread_pool`
There's no error. But I wonder how can I use `receiver`.

**Comment by Lee-Janggun** [comment]
@DaeyongKwon98 can you please make a new issue for your new problem?
