### ISSUE TITLE
Video session on September 21th (Wed)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#630]
Please do the following for the video session.

- Watch the following video(s):
  + https://www.youtube.com/watch?v=uuHHMQgv_9s&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=9
  + https://www.youtube.com/watch?v=Pccs-JhZBQE&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=10
  + https://www.youtube.com/watch?v=ja_cdKF72vU&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=14 (ignore the "acquire/release" things for now)

- There will be no quizzes.

**Comment by ichianr** [comment]
Does "Video session" mean that there will be no in-person class on Wednesday?

**Comment by jeehoonkang** [comment]
No in-person class. Please watch the videos home.
