### ISSUE TITLE
[Homework #1] Concurrent (read and write) or (write and write) on hierarchical data

### ISSUE THREAD

**Issue by KAIST16-Ryu** [kaist-cp/cs431#631]
Hello, I have a question about rust handling for hierarchical lock data structure, especially for a lock with hashmap and its several (key, value) with another locks.

lock ( Hashmap   ->  (Key, **lock(Value)**)            )
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp;  &nbsp; &nbsp;  &nbsp;   &nbsp; &nbsp;  &nbsp;  &nbsp; ->  (Key2, **lock(Value2)**)     )

For a test cache like cache_no_reader_block() and cache_no_block_disjoint(), **2 concurrent access involving at least 1 write lock** is used in the structure.

Since any insertion of key-value pairs invoke write lock, hashmap lock is used and I cannot get or access inside key-value lock without outer hashmap lock, and it prevents me to implement concurrent access.

I think Vec with multiple key-value pairs are also changed for insertion and it will cause the same problem.

Can I get some idea for accessing inside lock only or handling such problem? Thank you very much!

**Comment by Lee-Janggun** [comment]
Check https://github.com/kaist-cp/cs431/issues/339, especially https://github.com/kaist-cp/cs431/issues/339#issuecomment-750347278

**Comment by KAIST16-Ryu** [comment]
Thank you for your advice. It helped me a lot !!!
