### ISSUE TITLE
[Question HW1] How to use receive in worker?

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#632]
I change defining new worker and push it to vector like this.
```rust
let w = Worker {id, thread: Some(thread::spawn(||{}))};
workers.push(w);
```
When I test thread_pool.rs with
`cargo test --test thread_pool`
There's no error. But I wonder how can I use `receiver`.
Code in Rust book uses receiver like below, but I can't use Worker::new method,
so I don't know the way to do this.
```rust
for id in 0..size {
    workers.push(Worker::new(id, receiver));
}
```
Thank you.

**Comment by Lee-Janggun** [comment]
- You can't use `Worker::new` because it's simply not defined. What we are asking you to do here is essentially to re-implement the `Worker::new` you saw at the Rust book.
- The two options are as follows.
  1. Implement a `Worker::new` function as in the Rust book.
  2. Spawn the thread inside the for loop and use the `Worker {id, thread: Some(spawned_thread)};` syntax.

**Comment by DaeyongKwon98** [comment]
I choose first option and implement like this.
1. spawn thread in for loop
2. `let message = receiver.recv();`
3. match `message` same as `Worker::new` function code in the Rust book.
4. push new `Worker`

My code is only different in defining message, where I don't use `lock()`.

When I try to execute, error is like below.

```rust
error[E0282]: type annotations needed for `(crossbeam_channel::Sender<T>, crossbeam_channel::Receiver<T>)`
  --> src\hello_server\thread_pool.rs:77:13
   |
77 |         let (sender, receiver) = unbounded();
   |             ^^^^^^^^^^^^^^^^^^
   |
   = note: type must be known at this point
help: consider giving this pattern a type, where the placeholders `_` are specified
   |
77 |         let (sender, receiver): (crossbeam_channel::Sender<T>, crossbeam_channel::Receiver<T>) = unbounded();
   |                               ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

But giving type annotation like that is not correct in my opinion.
What's problem in this case?
Thank you always.

**Comment by Lee-Janggun** [comment]
Oh... I think this is a bit of problem with rustc. You have two options.

1. You need to give type annotation.
2. You should have some code like
   ```rust
   match job {
       Ok(job) => {
           ...
       }
       Err(err) => {
            ...
       }
   }
   ```
  if you followed the book. Change `Ok(job)` to `Ok(Job(job))`, and it should work.

**Comment by DaeyongKwon98** [comment]
Changing `Ok(job)` to `Ok(Job(job))` makes it work! :)

**Comment by DaeyongKwon98** [comment]
Changing `Ok(job)` to `Ok(Job(job))` makes it work! :)

**Comment by tomtomjhj** [comment]
This also works
```
let (sender, receiver) = unbounded::<Job>();
```
