### ISSUE TITLE
[Question] VM connection fails (WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED)

### ISSUE THREAD

**Issue by psb0623** [kaist-cp/cs431#636]
I am trying to connect my VM (s20190252@cp-service.kaist.ac.kr), but it fails with the error message below.

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[15:30:21.939] > @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
> Someone could be eavesdropping on you right now (man-in-the-middle attack)!     
> It is also possible that a host key has just been changed.
> The fingerprint for the ECDSA key sent by the remote host is
> SHA256:mPOLXndIdFgqDa7Pn+cXKvKJwqif2W7oVISwpKUN5fs.
> Please contact your system administrator.
> Add correct host key in C:\\Users\\psb06/.ssh/known_hosts to get rid of this mes
> sage.
> Offending ECDSA key in C:\\Users\\psb06/.ssh/known_hosts:1
> ECDSA host key for [cp-service.kaist.ac.kr]:13002 has changed and you have reque
> sted strict checking.
> Host key verification failed.
```

I used the same VM in spring for the previous course (CS420) and it worked well at that time.

How can I solve this problem?

**Comment by drash99** [comment]
Delete host information in C:\\Users\\psb06/.ssh/known_hosts.
There will be a line marked with cp-service.kaist.ac.kr:13002. 
Then reconnect and it will work.

**Comment by Lee-Janggun** [comment]
The id for the VM may be the same, but the same credentials don't work probably because we setup a new server.

I recommend making a new ssh connection from scratch, following the comment above.

**Comment by psb0623** [comment]
Thanks a lot! It works very well.
