### ISSUE TITLE
[Question] About Submission

### ISSUE THREAD

**Issue by lgm9** [kaist-cp/cs431#637]
I got all ok in the 3 tests when I ran it on the virtual machine, but when I submit the zip file onto the gg, it starts from installing the rust, and then the code does not compile. Is this normal?
(I'm 20200427 Gangmin Lee)

My checker log :
===== SETUP =====

===== CHECK =====
[2022-09-22 02:34:24,868: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).
**very many lines**

error: could not compile `cs431-homework` due to 11 previous errors
Please fix the issues from `cargo clippy` first.

(Again, my code is alright in the virtual machine)
Should I fix all **warnings** in clippy?

**Comment by Lee-Janggun** [comment]
Yes, you should fix the clippy warnings. As mentioned in https://github.com/kaist-cp/cs431/issues/606#issuecomment-1235141296 I enforced the linters in the grading script.


In the server, running `./scripts/grade-hello_server.sh` should also notify that you need to follow the lints.
