### ISSUE TITLE
[Question HW1] `get_or_insert_with` fail 2 tests

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#640]
Currently I pass 2 cases : cache_no_duplicate_sequential, cache_no_duplicate_concurrent
and fail cache_no_reader_block, cache_no_block_disjoint.

Error says some messages like 'Inserting a different key should not block: Timeout', 'RecvError', 'PoisonError'.

My inner structure has `Arc`, `Mutex` and `Option`. Can it be a problem?
Some issue says without `RwLock` we can pass tests...

My code structure is:
- get `hashmap` with `lock`
- use `or_insert_with_key` function, insert `f(key)` value
- return v

My logic is simply return the value if it already exists, and insert value if it doesn't.
But in previous issue(https://github.com/kaist-cp/cs431/issues/339#issue-773607586), it has different logic with mine.

Especially I can't understand why we have to consider the case: key is in `hashmap` but value is `None`. Also, in that issue, if key is not in `hashmap`, it set the value to `None` and release the lock instead of just putting the value. Can you explain?

Thank you.

**Comment by Lee-Janggun** [comment]
The key point is that (1) we don't want to block (2) we only want to compute `f` once.


For blocking:

Say that two different threads T1 and T2 with different fresh keys k1 and k2 are writing at the same time. As the specification says, since they are inserting to different keys, they should not block.

Following your logic, say T1 gets the lock first. Since `k1` is not yet in the map, it will compute `f(k1)`, and return the computed value.

However, while `f` is being computed, the lock for hashmap will not be released, and `T2` will need to wait an arbitrary amount of time until `f` is done. i.e, it is blocked. 

To avoid this, the referenced comment suggests T1 to temporarily insert `None` to mark that it will compute `f`, and release the lock for the inner hashmap.
 
 As a side note in terms of import: The model solution uses everything imported, which is why we left them there.

**Comment by DaeyongKwon98** [comment]
I have two questions.
First, at previous issue, what means `computatation` and `fight for the write lock again and write the key value pair`? I understand notion that when first I insert key-value pair, insert `key` with `None` value first, then later put value `f(key)`. But I wonder how to implement it.
In other words, you say temporarily insert `None` and it will compute `f`. How can I notice when to compute `f`?

Second, now I try to implement with if-else statement. There are three cases:
1. `key` exists, value is `Some(v)` => return v
2. `key` exists, value is `None` => insert `f(key)` value
3. `key` doesn't exist => insert `None`
Here, case 1 return `value` with `type V`, but case 3 doesn't return anything. So I get `mismatched types` error. How can I deal with this? I try to use `match` also, but I can't handle this issue.

**Comment by Lee-Janggun** [comment]
> In other words, you say temporarily insert None and it will compute f. How can I notice when to compute f?

Please look at https://github.com/kaist-cp/cs431/issues/339#issuecomment-750347278 for a high-level idea for implementation.

> Second, now I try to implement with if-else statement. There are three cases:

The thread that did 3 should be the one that is computing `f(key)` after inserting `None`, and update the `None` to `Some(v)`.

**Comment by DaeyongKwon98** [comment]
Now I only fail at `test cache_no_reader_block`. Actually when I try testing, sometimes it passes but usually fails.
Error says `Inserting a different key should not block: Timeout`
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError'
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }'`
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"'`

My code structure is 
1. Get read lock
2. If `key` exists, `get` the value. If value is `Some(a)`, return a. If value is `None`, return `f(key)`.
3. If `key` doesn't exist, drop read lock and get write lock.
4. Check if `key` exists again. If `key` exists, do excatly same code as 1 and 2.
5. If still `key` doesn't exist, insert `None` value and later change it with `f(key)`, and return that value.

In my opinion, maybe I have problem with 2.
I think when `key` exists but value is `None`, this means other thread is now computing `f(key)` value. So current thread needs to wait until computing is done and value is changed from `None` to `f(key)`.
But in my code, I just return `f(key)` value immediately.

**Comment by Lee-Janggun** [comment]
If you did locking correctly, when you get the value lock in (2), the value should only be `Some(a)`. Can you try calling `Option::unwrap()` on the value in (2), instead of doing pattern matching?

**Comment by DaeyongKwon98** [comment]
I change match block into unwrap(), same error occurs.
Then it means my lock  have some problem?

**Comment by Lee-Janggun** [comment]
Yes, you are probably not releasing the lock for `inner` when you are supposed to.

**Comment by DaeyongKwon98** [comment]
I get `write` lock at (3), and `write` lock at (3) is the only `write` lock I use, and it's immediately dropped at (4).
For (5), `write` lock is dropped right after inserting `None` value.

So I can't find additional place to `drop` the lock.
Also in (2), I `drop` the lock before returning value.

I also look at test case for `cache_no_reader_block`, but still have no idea about it.

**Comment by Lee-Janggun** [comment]
A possible place I see is in 1. 

Make sure your are not waiting for a lock while holding a lock.

**Comment by DaeyongKwon98** [comment]
I finally made it :)
I change position of droping lock from after lock the value to before lock the value.
