### ISSUE TITLE
[Question] Error with `./scripts/submit.sh`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#642]
I try `$ ./scripts/submit.sh` at cs431/homework.
Following error occurs.
./scripts/submit.sh: line 4: zip: command not found
./scripts/submit.sh: line 5: zip: command not found
./scripts/submit.sh: line 6: zip: command not found

How can I deal with this?

**Comment by Lee-Janggun** [comment]
The server should already have `zip` installed. If you are on your local machine, install `zip`.

**Comment by DaeyongKwon98** [comment]
You mean server that I login with ssh?
If it is, I have no homework in cs431 in server.
I can't clarify the meaning of server. Can you explain a little bit?
Thank you always.

**Comment by Lee-Janggun** [comment]
There is no homework directory because you should make your own.

As we mentioned in README.md, the recommended way is to setup a private GitHub repo and do your work there.

**Comment by DaeyongKwon98** [comment]
Sorry, but I think I have poor understanding about github repo and server.
As I understood, setting up a private repo and using it happen in local machine.
So do I need to copy `kaist-cp/cs431` into my private repo, then change code with mine, and make homework directory and put codes in my private repo to the server?

**Comment by Lee-Janggun** [comment]
Which directory are you running bash? You I think you may be running it inside `cs431` directory. 

If that is the case, please try running it after `cd`ing into `cs431/homework`.

**Comment by DaeyongKwon98** [comment]
I somehow make hw-hello_server.zip file and submit in gg.
But doesn't success. Log finally says `Please format your code with `cargo fmt` first.`
How can I deal with this? In ssh server, command `cargo` doesn't work.

**Comment by Lee-Janggun** [comment]
As I mentioned in https://github.com/kaist-cp/cs431/issues/606#issuecomment-1235141296, you need to format your code with rustfmt and clippy.

* For cargo in server: Please read [here](https://github.com/kaist-cp/cs431#tools).
* for formatting, running `cargo fmt` in `homework` directory should work.
* for clippy, you need to look at the errors and fix them yourselves. `cargo clippy --fix` may also work for some errors.

**Comment by DaeyongKwon98** [comment]
Finally I finish HW1!
I modify my code at local machine, so until now I don't even install rust in server.. :(
Thanks for a lot of efforts you gave to me. :)

**Comment by Lee-Janggun** [comment]
No problem! From HW2, I strongly recommend doing HW on the server as you will need to pass the sanitizer tests, which are not supported in Windows and somewhat unstable in MacOS
