### ISSUE TITLE
[Homework 3] Seg fault while dropping the list

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#643]
Hi, 
I am getting a seg fault: `SIGSEGV: invalid memory reference` at the end of the smoke test.
That is, after all assertion statements are passed, the function drops the OrderedListSet, and during the dropping process, I am getting the invalid memory reference error.

However, to remove errors, I have left my drop() implementation as blank.
Currently my drop() function is doing nothing except printing some statements.

Could you explain how it is possible to  get an invalid memory reference error when my drop function is doing absolutely nothing?

**Comment by Lee-Janggun** [comment]
Does the error persist even if you remove the printing statements?

**Comment by choejms** [comment]
Yes. I removed the print statements in drop() function, and I am still getting seg fault errors.
Strangely, my code passes the smoke test on my personal computer, but not on the server.

**Comment by Lee-Janggun** [comment]
1. What is your personal computer?
2. Are you failing just `cargo test --test list_set`, with tsan nor asan?

**Comment by choejms** [comment]
1. My personal computer is Mac OS.
2. I am running `cargo test  --test list_set smoke  -- --nocapture`.

**Comment by Lee-Janggun** [comment]
1. What is your OS and hardware?
2. The model solution passes smoke even with a blank `drop` implementation, so it may be a problem with another part of your code.

**Comment by choejms** [comment]
1. My OS is macOS Monterey Version 12.1(21C52)
2. I just modified my remove() function, and my code passes the smoke test case. However, if I change `assert_eq!(set.remove(&2), Ok(2));` to `assert_eq!(set.remove(&1), Ok(1));`, there is a seg fault while dropping the list. I think there is a problem with my remove() function when I try to remove the first element.  

But it's still strange how I can have an invalid memory reference error in a blank drop() implementation. 

Thank you for the information. I will further work on remove() function.

**Comment by choejms** [comment]
If it is not too much to ask, can I ask if the model solution passes `smoke` with blank drop implementation, after modifying `assert_eq!(set.remove(&2), Ok(2)); ` to `assert_eq!(set.remove(&1), Ok(1));`?

If this is not possible, I understand.

**Comment by Lee-Janggun** [comment]
It's really hard to say what the error is. The simplest (and somewhat most annoying) is running the [lldb debugger](https://www.forrestthewoods.com/blog/how-to-debug-rust-with-visual-studio-code/), or running the sanitizers.

I recommend running address sanitizers to see the problem first.

For why a blank `drop()` implementation may still be a problem: having a blank `drop()` does not mean that nothing is done. 

In particular, the destructor for the mutex `head` will be called, and this may be the issue.

**Comment by Lee-Janggun** [comment]
> If it is not too much to ask, can I ask if the model solution passes `smoke` with blank drop implementation, after modifying `assert_eq!(set.remove(&2), Ok(2)); ` to `assert_eq!(set.remove(&1), Ok(1));` in `smoke`?
> 
> If this is not possible, I understand.

Model solution still passes with this change and a blank drop implementation.

**Comment by choejms** [comment]
Thank you for the explanation. It is very helpful.
