### ISSUE TITLE
[Question] About dealing with write access to rwlock in cache.rs

### ISSUE THREAD

**Issue by kimdh98** [kaist-cp/cs431#646]
I've read through #339 and [#339 (comment)](https://github.com/kaist-cp/cs431/issues/339#issuecomment-750347278), and the issues referencing them. 
From what I understand, it seems like there exists a way to make the main thread T maintain ownership to a mutable reference to the temporary None value in the hashmap even after using or_insert() and dropping the write lock. Then, this reference is updated to the result of expensive computation when it completes. 
Is my understanding of the situation correct? I've been going in circles trying to find a way to do the above and keep getting the feeling that if my understanding is correct, this pattern goes against the intuition behind rwlock, as I will be able to write to the hashmap without obtaining a write lock.

**Comment by Lee-Janggun** [comment]
Your understanding is correct.

The key point of the above discussion you are probably missing is that the Cache does not **directly store**  the value V, but only **stores a reference to V**.

That way, even if the value the reference is pointing to changes, the reference itself does not change.

**Comment by Lee-Janggun** [comment]
I realize my above comment may lack a bit of detail, so let me elaborate a bit more.

The important part is how you will hold this reference. As you may have guessed, simply holding a _immutable reference_ `&` is not good. 

So the way is to 1) hold a reference and 2) have the ability to access it uniquely to access it. For this, please consider the items in "Specifically, make sure that you understand following topics." in [the docs](https://github.com/kaist-cp/cs431/blob/main/homework/doc/hello_server.md#reading-rust-book).

**Comment by kimdh98** [comment]
Thanks for the explanation, I get the idea of design pattern now. I'll reread through the docs and try to figure out the implementation details as advised.
