### ISSUE TITLE
[Question HW1 Cache] get_or_insert_with() how can I know when None changes to Some(result)?

### ISSUE THREAD

**Issue by dripcharacter** [kaist-cp/cs431#647]
I've read #339 , #640 , #646 . And now I passed two tests(cache_no_duplicate_sequential, cache_no_block_disjoint).
My cache inner type uses Rwlock for HashMap and Mutex for V Since I want only one thread can access to V when it is None.
But since I can't lock the inner mutex of V, I don't know when the code update None value to Some(result) and how to notify to waiting threads.

**Comment by Lee-Janggun** [comment]
I don't get what you mean by "I can't lock the inner mutex of V". Why can't you use the `lock()` function?
