### ISSUE TITLE
[Question HW2] `insert_next` 

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#649]
I implement `insert_next` funciton.
I succesfully deal with three cases: empty list, insert at front, insert at last.
I have problem in inserting at intermediate position.

Here for convenience, let me call node A, B, C, where A is `self.head`, B is inserted `node`, C is a node after inserted node. So list will be [ A, C ] -> [ A, B, C ].

My logic is:
1. Create new `node` which has type `<Box<Node<T>>`.
2. With `into_raw`, change `node` to type `*mut Node<T>`.
3. Change `B.next` to `C`.
4. Change `B.prev` to `A`.
5. Change `C.prev` to `B`.
6. Change `A.next` to `B`.
7. Change `self.head` to `node`. (Moving position by one)
8. Increment length by one.

Here, following error occurs.
```rust
failures:

---- test_insert_next stdout ----
thread 'test_insert_next' panicked at 'attempt to subtract with overflow', /home/s20170040/cs431/homework/src/linked_list.rs:147:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I also try `cargo test --test linked_list -- --nocapture --test-threads 1`, but I can't get additional information from this.

I find that error occurs when (3) and (6) exist at the same time.
What's problem in my logic?
Thank you.

**Comment by Lee-Janggun** [comment]
First off, you are probably subtracting when the `len` is already 0, which is where the overflow is coming from. As `note:` says, run with `RUST_BACKTRACE=1` to get more backtraces. e.g,
```
RUST_BACKTRACE=1 cargo test --test linked_list
```
> Change self.head to node. (Moving position by one)

Why are you doing this? The description never mentioned that the iterator moves.

> I find that error occurs when (3) and (6) exist at the same time.

I don't exactly get what you mean by this, but you probably want to consider if you considered the case where the iterator is empty or at the very start.

**Comment by DaeyongKwon98** [comment]
In `next` for Iter (already provided code), it has `self.head = node.next`.
I understand this line to mean current position is `self.head`, and by updating it to next node we can move one step.

**Comment by Lee-Janggun** [comment]
Yes, that is what `next()` does, because the task of `next()` is to give the next item of the iterator.

The task of `insert_next()` is not that. In particular, note that `insert_next` does not even return anything, while `next()` returns `Option<&mut T>`, and the difference should hint that their semantics are very different.

**Comment by DaeyongKwon98** [comment]
Instruction says `Inserts the given element just after the element most recently returned by .next().`

I understand this to mean insert after `self.head`.
Then when call `insert_next(0)` at example, `self.head` is `1` and I have to insert `node` before `self.head`.

Also does `The inserted element does not appear in the iteration.` mean I should only change `list`, not `iterator`? I think `list` and `it` in `tests/linked_list.rs` are same.

**Comment by Lee-Janggun** [comment]
> I understand this to mean inserting after self.head.
Then when call `insert_next(0)` at example, `self.head` is 1 and I have to insert `node(0)` before `self.head`.

You never mentioned what example you are talking about... in this case I can find out it is most likely `test_insert_next`, but please specify from now on for more efficient communication.

Your understanding itself is correct.

> Also does The inserted element does not appear in the iteration. mean I should only change list, not iterator? I think list and it in tests/linked_list.rs are same.

Yes that is correct. You should only change the list.

> I think list and it in tests/linked_list.rs are same.

Clearly they are not; they do not even have the same type. (LinkedList<i32> vs IterMut<i32>).

Please look at https://doc.rust-lang.org/std/iter/index.html to get a more concrete idea of iterators in Rust.

**Comment by DaeyongKwon98** [comment]
My problem with `attempt to subtract with overflow` is because I change length of `iterator`, not that of `list`.
