### ISSUE TITLE
[Article] CACM: Safe Systems Programming in Rust

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs431#650]
I found a interesting article about Rust.
[Safe Systems Programming in Rust](https://cacm.acm.org/magazines/2021/4/251364-safe-systems-programming-in-rust/fulltext)  
Although I haven't finished reading it yet, I wanted to share it because there seemed to be a lot of overlap with the contents of our class.  
Have fun if you're interested!

**Comment by Lee-Janggun** [comment]
I'll actually leave the issue open, since I think the article would help a lot to understand the philosophy behind Rust's type system, especially regarding lifetime and unsafe code, and why we choose to use it in this class. Thanks for sharing it!
