### ISSUE TITLE
[Homework 2] Proposal for `peek_next()`

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs431#651]
While gg.kaist tests `peek_test()` function with DocTest, in `tests/linked_list.rs` file, there is no explicit test case for `peek_next()`.  
I made a testcase which is more rigorous than DocTest one.  
Would be better to add explicit test case in `tests/linked_list.rs` file referring this one.

```rust
#[test]
fn test_peek_next() {
    let mut list: LinkedList<i32> = LinkedList::new();
    let mut it = list.iter_mut();
    assert_eq!(it.peek_next(), None);

    let mut list = list_from(&[1, 2, 3]);
    let mut it = list.iter_mut();

    assert_eq!(it.peek_next(), Some(&mut 1));

    it.peek_next().map(|value| *value = 42);

    assert_eq!(it.next(), Some(&mut 42));

    assert_eq!(it.peek_next(), Some(&mut 2));
    assert_eq!(it.peek_next(), Some(&mut 2));
}
```

**Comment by Lee-Janggun** [comment]
Thanks for the test case! Since there is only a week left for the assignment, we won't add it this year, but will make sure to add it next year.
