### ISSUE TITLE
[Question] Behavior of clear and Iterator (not relevant to the programming)

### ISSUE THREAD

**Issue by Allgot** [kaist-cp/cs431#658]
I've done HW2, but I am curious about the behavior of clear function and Iterator(IterMut) in LinkedList.   
   
(1) For `clear` function, I found that it only contains one substitution:   
```
pub fn clear(&mut self) {
        *self = Self::new();
}
```
I assume that this can remove all the nodes because it ends the older nodes' lifetime and thus they are distructed thanks to Rust.   
Am I right?   
   
(2) While finalizing my code, I found a very strange behavior of IterMut: in peek_next function, accessing to the element through iterator itself immediately proceed to the next iteration, regardless whether I substitute Iterator's head to the next node or not. I solved this problem by just not using Iterator itself , but still I cannot understand why this happens.   
Is it possible for Iterator to iterate without explicit substitution (i.e., substitute current head node with its next node) or calling 'next' function? I am sure that I didn't both of them..   
   
Thank you for answer in advance :)

**Comment by Lee-Janggun** [comment]
> I assume that this can remove all the nodes because it ends the older nodes' lifetime and thus they are distructed thanks to Rust.

Yes you are correct.

>  accessing to the element through iterator itself immediately proceed to the next iteration

I'm not sure what you mean by this. Do you mean that you used `next()` `self`? If that is the case, `next()` does move the iterator.

**Comment by Allgot** [comment]
Thank you, I understood the behavior of clear well, and never mind for second question! It was my mistake ;)
