### ISSUE TITLE
[Question] Can I use module mem in HW3?

### ISSUE THREAD

**Issue by Meraro** [kaist-cp/cs431#660]
I noticed that skeleton code of list_set.rs doesn't have mem module, but I want to use mem::replace function in my code.
Can I use std::mem in my homework?

**Comment by Lee-Janggun** [comment]
I'm not sure why you need it, can you explain you situation a bit?

**Comment by Meraro** [comment]
> I'm not sure why you need it, can you explain you situation a bit?



> I'm not sure why you need it, can you explain you situation a bit?

To implement the insert function, what I want to do is to get a cursor's next(Mutex) value to make a new Node which points to the next node. 
But I can't do that, so what I do here is 

let next = replace(cursor.next, Mutex(null))

to get a next value
I know this is a quiet strange implementation but I don't have better idea...

**Comment by Lee-Janggun** [comment]
You may find https://github.com/kaist-cp/cs431/issues/199 and https://github.com/kaist-cp/cs431/issues/542 helpful

**Comment by Meraro** [comment]
Oh.. I may found an idea

**Comment by Meraro** [comment]
> You may find #199 and #542 helpful

I solved it! Thank you for your advice!
