### ISSUE TITLE
[Question] Why does clh lock use const fn new()?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#662]
Hi,
In clh lock, we have the following function.

```
impl Node {
    const fn new(locked: bool) -> Self {
        Self {
            locked: AtomicBool::new(locked),
        }
    }
}
```

I am wondering why `new()` is declared as `const fn`. I looked up what `const fn` does, and the documentation says 
"the function is interpreted by the compiler at compile time. The interpretation happens in the environment of the compilation target and not the host." But I do not quite get the function of `const` in our code.

Thank you.

**Comment by Lee-Janggun** [comment]
Declaring a function const means that it can run at compile time. This can be used to make global variables.

For example, if a filesystem would like to have a global CLH lock, having, or you wanted to make a fixed size array living in the stack, making a function const allows for it to be used in such context.

In general, if one can mark a function as const, there is no reason not to, as it will simply increase the number of ways it can be used.

**Comment by choejms** [comment]
Thank you for the explanation.
