### ISSUE TITLE
[Homework 3] Dummy submission file created

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs431#665]
I submitted HW3, and got this screen:  

![image](https://user-images.githubusercontent.com/52380072/195045307-4d098501-6053-4af1-b17c-028647e07035.png)
Is okay to ignore `list_set_KNdgi0j.rs`?

**Comment by Lee-Janggun** [comment]
Huh...that is very interesting...
1. If you download the weird file, is the file contents ok?
2. Can you try re-submitting and see what happens?

**Comment by woojinnn** [comment]
Oh, it seems like a temporary issue. I reassigned it, and worked normally
