### ISSUE TITLE
[Question] Is there any way to initialize the given server?

### ISSUE THREAD

**Issue by Allgot** [kaist-cp/cs431#666]
I tried to exercise with homeworks, but it seems I broke my whole system down :(
Every .rs file in cs431 folder says the below error.
```
file not included in module tree-rust-analyzer (unlinked-file)
```
Is there any way to initialize the given server..?

Sorry for inconvenience.

**Comment by Lee-Janggun** [comment]
Does removing the VSCode extension and re-installing it not help?

**Comment by Allgot** [comment]
Yes, I tried (1) re-install extensions (2) re-install VS code(using remote command) (3)pull this repository, but nothing changed.. ;(

It seems some files in my account(e.g. .s20190511/.cargo) are broken..

**Comment by Lee-Janggun** [comment]
Please send an email to the professor who can reset your server.

**Comment by jeehoonkang** [comment]
Do `mv ~/.cargo ~/.cargo-backup` and install Rust again.

**Comment by Allgot** [comment]
Thank you for replying!

I backed up .cargo, .cache and .rustup and install Rust again, but same error occurs again..

**Comment by jeehoonkang** [comment]
I suggest you (1) `mkdir ~/temp; mv ~/* temp; mv ~/.* temp`, and then (2) `cp /etc/skel/.* ~`.

**Comment by Allgot** [comment]
Thanks a lot!

Finally it begins to work :)
