### ISSUE TITLE
[Question] Why is there a PhantomData in the Node only in MCS parking lock but not in others?

### ISSUE THREAD

**Issue by SansyHuman** [kaist-cp/cs431#668]
In the lock implementation which use linked list, there is a PhantomData in the Node only in MCS parking lock but not in others such as CLH or MCS lock. Why is that?

**Comment by Lee-Janggun** [comment]
I actually think we can delete it... but I'm not sure. @jeehoonkang do you possibly have an answer?

As a note, we won't ask about `PhantomData` in the exam since even though it is needed for concurrency in some cases, it is not the purpose of this course.

**Comment by jeehoonkang** [comment]
- I don't know too :) @tomtomjhj what do you think?
- We'll figure out what's happening here and either fix the implementation or add comments.
- As @Lee-Janggun said, it will not be asked in the midterm exam.
