### ISSUE TITLE
[Question] About Compile result of Atomic, and CachePadded in clhlock

### ISSUE THREAD

**Issue by TriangleYJ** [kaist-cp/cs431#670]
I am reviewing memos in my lecture note, and I have two independent questions about mentioned in the title.

First, I think I heard that the rust compiler compiles Atomic like structs to normal `load` and `store` instructions, but I don't understand how the compiler guarantees the atomic operations.
After `load` instruction done, if OS context switched to another thread by the unfortunate scheduling, then it is not an atomic becuase the `store` has not been called. So I understood that this operation should be supported in hardware, and there is actually an x86 instruction like `CMPXCHG` for this. Does Rust compiler compiles Atomic to this operation? 

Second, the professor said that It is required to wrap `AtomicPtr` with `CachePadded` in the line 30, and he suggested the student who asked the question open the new issue. However, I think this code is okay because there is no possibility that `prev` value changes(line 41), so no false sharing happened because of no invalidation. However, `Node` value can be changed by another thread, so it is required to add `CachePadded` to `Node`. Is it correct?

https://github.com/kaist-cp/cs431/blob/e5f2b0d3ee6251ea73c2191b9ee99bc21028161f/src/lock/clhlock.rs#L28-L48

**Comment by Lee-Janggun** [comment]
> First, I think I heard that the rust compiler compiles Atomic like structs to normal load and store instructions, but I don't understand how the compiler guarantees the atomic operations.

This is not true. I'm not sure who you heard it from, but hope you can correct them :)

> So I understood that this operation should be supported in hardware, and there is actually an x86 instruction like CMPXCHG for this. Does Rust compiler compiles Atomic to this operation?

This is correct. If you look at the [implementation of `compare_exchnage()`](https://doc.rust-lang.org/src/core/sync/atomic.rs.html#618-632), it calls an [intrinsic function](https://doc.rust-lang.org/nightly/src/core/intrinsics.rs.html#74), which (by doing a lot of internal compiler stuff which you nor I need to know) will ultimately emit hardware instructions guaranteed to be atomics. Hence if you observe that Rust's atomic instructions are actually not, it is (1) a `rustc` (the standard rust compiler) bug or (2) an hardware bug.

> However, I think this code is okay because there is no possibility that prev value changes(line 41), so no false sharing happened because of no invalidation. 

Actually this is false. Here, [`swap()`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html#method.swap) **stores** a value to `tail`, and  returns the old value, i.e, it is a read-modify-write. So L41 will invalidate the cache `prev` lives in, hence nodes should be `CachePadded` to ensure that they are not at the same cache line as `prev`, and other nodes.

**Comment by TriangleYJ** [comment]
Thank you for your kind answer!

Then, about the second question, is it okay to wrap only in the `Node`, and no need to change tail type to `CachePadded<AtomicPtr<CachePadded<Node>>>>`? Now I think `self.tail` could be invalidated due to `swap()`, so false sharing could be happen...

**Comment by Lee-Janggun** [comment]
> Then, about the second question, is it okay to wrap only in the Node, and no need to change tail type to CachePadded<AtomicPtr<CachePadded<Node>>>>?

Since there is only one `tail` per lock, if every node is `CachePadded`, then `tail` will also be on a different cache line than every other node. Now this is assuming only one lock exists. If you are in a situation where you have many instances of locks and multiple of them are active, then you might want to pad `tail`.

> Now I think self.tail could be invalidated due to swap(), so false sharing could be happen...

Well, it will actually **always** be invalidated, because unlike `compare_exchange()` where it _might_ write, `swap()` _always_ writes.

**Comment by TriangleYJ** [comment]
Oh, now I clearly understand. Thank you for your reply!

**Comment by Lee-Janggun** [comment]
No problem! Thank you for the detailed question.

**Comment by dubuduru** [comment]
Can you explain more about why L41 invalidates the cache line prev lives in? I understand that swap makes the cache line where self.tail is in invalid. Why prev's line will be also invalidated?

**Comment by Lee-Janggun** [comment]
Sorry, I should have been more careful with my work choices. What I really meant is that it **may** invalidate the cache line `prev` lived in, if `prev` and `self.tail` used to live in the same line.

**Comment by dubuduru** [comment]
Thanks for clarifying.
Then as far as I understood, as we cachepad all Nodes, we do not have to worry that invalidation of self.tail's line would invalidate prev's line (as prev is pointer of Cachepadded<Node>. And why we need to wrap AtmoicPtr with CachePadded is that there can be multiple locks so that they can interfere tail of one another. Is it right?

**Comment by Lee-Janggun** [comment]
Yes you are right.

**Comment by dubuduru** [comment]
Thank you so much :)
