### ISSUE TITLE
[Question HW3] Question about homework server log

### ISSUE THREAD

**Issue by DoHoonKim8** [kaist-cp/cs431#671]
I submitted `list_set.rs` to homework server and got the following log.

```
Running with cargo_asan...

running 1 test
test stress_sequential ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.39s

Test failed:    cargo_asan test  --test list_set stress_sequential

running 1 test
test stress_concurrent ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 6.54s

Test failed:    cargo_asan test  --test list_set stress_concurrent

running 1 test
test log_concurrent ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 23.04s

Test failed:    cargo_asan test  --test list_set log_concurrent

running 1 test
test iter_consistent ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 4.70s

Test failed:    cargo_asan test  --test list_set iter_consistent
Score: 10 / 80
```

I'm not sure whether `cargo_asan` test is passing or not from the log because it says that `test result: ok`, but `Test failed` too. I ran the following commands in my local machine...

`cargo_asan test  --test list_set stress_sequential`
`cargo_asan test  --test list_set stress_concurrent`
`cargo_asan test  --test list_set log_concurrent`
`cargo_asan test  --test list_set iter_consistent`

and it says `test result: ok`. What is making the log `Test failed:    cargo_asan test  --test list_set ~~~`?

**Comment by tomtomjhj** [comment]
Please post the full output from `cargo_asan` commands.

**Comment by Lee-Janggun** [comment]
`test result: ok` means that the tests written in [`src/tests/list_set.rs`](https://github.com/kaist-cp/cs431/src/tests/list_set.rs) succeeded. Since there is no way to write "there is a memory problem (e.g, leak)" into the program, even if there is a memory leak, the log may still say `test result: ok`. To make sure no leaks happen, we run the address sanitizer.

**Comment by DoHoonKim8** [comment]
Ah, I see. Thanks for your comment!
