### ISSUE TITLE
If T is Send, is &mut T Send?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#674]
Hi I am looking at Rust documentation for Send trait, and I noticed the following. 
<img width="332" alt="스크린샷 2022-10-15 오전 1 16 48" src="https://user-images.githubusercontent.com/90259205/195893688-dc8ad8d7-d010-4a40-85f5-66c04006389f.png">

Rust documentation says if T is Sync, &T is Send, which I understand.
But what I don't understand is why is it that if T is Send, &mut T is Send?
I want to know why Sync condition is unnecessary in this case because I thought T should implement both Send and Sync for &mut  T to be Send.

**Comment by Lee-Janggun** [comment]
A good example to think about why this choice is needed is a type that does implement `Send` but not `Sync`, such as `RefCell<T>` where `T : Sync`, and think about if it is ok to `Send` `&mut RefCell<T>`.

Now to actually reason about why this trait bound is sound, really boils down to what **really** send means. Normally we would look at [the nomicon](https://doc.rust-lang.org/nomicon/send-and-sync.html), but it has the really "helpful" definition of...

> A type is `Send` if it is safe to send it to another thread.

So let's instead take a look at [the book](https://doc.rust-lang.org/book/ch16-04-extensible-concurrency-sync-and-send.html#allowing-transference-of-ownership-between-threads-with-send) which is somewhat more helpful:

> The `Send` marker trait indicates that ownership of values of the type implementing Send can be transferred between threads.

Ok... then the question is: what does it mean to _have ownership of_ `&mut T`? The answer is: for the lifetime `'a` that `&mut T` is alive, we have ownership of `T`. 

Hence, while `'a` is alive, transferring ownership of `&mut T` is essentially the same as transferring ownership of `T`. Thus, if transferring ownership of `T` to other threads is safe, then transferring ownership of `&mut T` is safe.

Note: this explanation is the high level of idea of a formalization of the rust type system [described here](https://plv.mpi-sws.org/rustbelt/popl18/paper.pdf), and in particular section 4.2, _Mutable references_.

**Comment by choejms** [comment]
Thank you for the explanation!
