### ISSUE TITLE
[Question] Is thread.clone() is mandatory in MCS parking lock's unlock()?

### ISSUE THREAD

**Issue by kohs100** [kaist-cp/cs431#677]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/20630805/196021374-70fd7f49-c0ac-4523-968f-bcd85655ddf7.png">
In slide43, I understood that thread.clone() is needed for unparking parked thread.

However, in rust reference
<img width="546" alt="image" src="https://user-images.githubusercontent.com/20630805/196021273-c632199b-1a6c-4290-bb16-3eefd1c5bf46.png">
Since unpark method receives readonly reference, it seems that there are no need for cloning thread object.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/20630805/196021407-3dfa42d2-6a5a-4cf2-ac33-b12216b08ee2.png">

So I modified the code not to clone the object but use reference for unparking, and it is compiled and works well. 
Is there any other need for cloning the thread? Did I misunderstand something?

**Comment by choejms** [comment]
I think this is a duplicate with #176

**Comment by kohs100** [comment]
> I think this is a duplicate with #176

Oh thanks!
