### ISSUE TITLE
[Question] About Drawbacks of fine-grained locking

### ISSUE THREAD

**Issue by dripcharacter** [kaist-cp/cs431#678]
In slide 45, there are two drawbacks of fine-grained locking compared to coarse-grained locking.

I understood about second one.(Since there are many locks to consider, reasoning is much more complex than coarse-grained locking.)
And I agree with the first one at point of overhead since fine-grained uses many locks.
But I don't know why it is about single-thread?
If fine-grained locking data or collection is shared with multiple threads, then overhead of each thread's work is for each thread I think...

For example, if our situation is about slide 47's first situation, then overhead of acquire and release lock of A and C is overhead of thread which insert B between A and C, not other threads.

Or does the word single thread just mean that the overhead of the thread for each task increases?

**Comment by choejms** [comment]
I think it just means that if there is a single thread accessing the list, there is no reason to use the lock on  each node. So constant locking/unlocking to traverse through the list leads to overhead.

**Comment by dripcharacter** [comment]
I perfectly understand!!
Thank you
