### ISSUE TITLE
[Homework 3] same problem with issue @645

### ISSUE THREAD

**Issue by gayeun4195** [kaist-cp/cs431#682]
Actually, I had same problem with [@645](https://github.com/kaist-cp/cs431/issues/645) and changing the order of code solved the problem. Can I know what is the reason for this weird solution?

**Comment by Lee-Janggun** [comment]
As I said in https://github.com/kaist-cp/cs431/issues/645#issuecomment-1256318180 ... I really cannot say anything without more information. :(

**Comment by Lee-Janggun** [comment]
You might want to take a look at https://github.com/kaist-cp/cs431/issues/645#issuecomment-1289027021 .
