### ISSUE TITLE
[Question] HW3: submission server error

### ISSUE THREAD

**Issue by dubuduru** [kaist-cp/cs431#683]
When I submit my list_set.rs in gg, it says that linked_list.rs file has a problem and it should be cargo clippy-ed.
Below is the detailed message from gg.
<details>
<summary>server message</summary>

 Compiling arr_macro_impl v0.1.3
    Checking arr_macro v0.1.3
    Checking cs431-homework v0.1.0 (/app/files/checks/e8ca1e78-178d-4abe-a3c3-c0c36f3fe220/cs431/homework)
error: local variable doesn't need to be boxed here
   --> src/linked_list.rs:154:34
    |
154 |     fn push_back_node(&mut self, mut node: Box<Node<T>>) {
    |                                  ^^^^^^^^
    |
    = note: `-D clippy::boxed-local` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#boxed_local

error: could not compile `cs431-homework` due to previous error
Please fix the issues from `cargo clippy` first.

</details>

How can I solve this problem? I did cargo clippy to my list_set.rs file.

**Comment by gayeun4195** [comment]
I have exactly same problem and error message is same too.

**Comment by Lee-Janggun** [comment]
Sorry... it should have been fixed by https://github.com/kaist-cp/cs431/commit/1f65287ccec81a4e2f3dd8d66c7b8994f11cc28a. I forgot that skeleton code needs extra clippy allows.

**Comment by dubuduru** [comment]
Thank you, now the server works well 👍
