### ISSUE TITLE
[Question HW3] Implementation about `remove`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#688]
In lock coupled linked list, if there is list like [A] -> [B] -> [C] and try to remove B, procedure is like below.
acquire A's lock -> acquire B's lock -> read C and make A.next = C, and drop B.

In our homework, suppose list looks like ... -> [A] -> [B] -> [C] -> ... and call `remove(B)`.

My `remove` use `find`, and set `cursor` to `B` (node to be dropped).
Then how can I acquire previous node A's lock? There is only next, no prev...

And in lock coupled linked list and same [A] -> [B] -> [C] example,
After we get B's lock, we drop A and get C's lock to proceed.
I use `lock()` in several places like `Cursor::find`, `remove`.
Do I have to manually call `drop` acquired nodes before such function ends?

Thank you.

**Comment by Lee-Janggun** [comment]
When `Cursor::find` returns `(true, Cursor(guard))`, the `guard` should be `MutexGuard` for `A.next`. Hence, you start by holding onto the lock for `A`.

**Comment by DaeyongKwon98** [comment]
>When **`Cursor::find`** returns `(true, Cursor(guard))`

Do you mean `OrderedListSet::find`? `Cursor::find` returns `bool`.

>the `guard` should be` MutexGuard` for `A.next`. Hence, you start by holding onto the lock for `A`.

I understand this to be:
`MutexGuard` in `Cursor` is `B`, which is `A.next`, so it means we already acquire `A's lock`. So I don't need to try to acquire `A's lock` again. Is it right?

---
Also, I find when I test with insert(1), insert(2), insert(3), remove(2), remove(3),
my `Cursor::find` goes to infinite loop during remove(3), especially when I try to acquire lock of `node(2).next` in `Cursor::find`.
```rust
// n is node [2]
let next_node = n.next.lock().unwrap();
```

I wonder why this line causes infinite loop.
How a line above can cause infinite loop?

**Comment by Lee-Janggun** [comment]
> Do you mean `OrderedListSet::find`? `Cursor::find` returns bool

Ah yes, sorry for the confusion. I really shouldn't think I remember all the details of the homework API :p.

> MutexGuard in Cursor is B, which is A.next, so it means we already acquire A's lock. So I don't need to try to acquire A's lock again. Is it right?

Yes you are right.

> I wonder why this line causes infinite loop.
How a line above can cause infinite loop?

It may be that you didn't release the lock properly when doing `remove(2)`. Does the problem also happen if you don't do `remove(2)`? That is, the following case:
```
insert(1);
insert(2); 
insert(3); 
remove(3);
```

Also, if it is indeed the case something that should be dropped is not dropped, you might have a memory leak, so try running with the address sanitizers.

**Comment by DaeyongKwon98** [comment]
>It may be that you didn't release the lock properly when doing remove(2). Does the problem also happen if you don't do remove(2)? That is, the following case:

Problem doesn't happen at insert(1), insert(2), insert(3), remove(3). So I think as you said problem is about `drop`.

In my implementation, there are two candidates to put `drop`: in `Cursor::find` and `remove`. So there are four possible cases:
1. `drop` in both place -> `free(): double free detected in tcache 2`
2. `drop` only in `remove` -> `free(): double free detected in tcache 2`
3. `drop` only in `Cursor::find` -> infinite loop
4. no `drop` -> infinite loop

For more detailed explanation, in `Cursor::find`, I `drop` node `(*self.0).as_ref()`,
and in `remove`, I `drop` `Box::from_raw(*cursur.0))` before returning key.

Perhaps problem is not only usage of `drop`, but also implementation of `drop`..
In `drop`, my implementation is like below:
1. get mutable reference of `self.head` with `get_mut()` (I will say this [1])
2. if it's null -> break
3. else get `self.head`'s next reference with `get_mut()` (this is [3])
4. if it's null -> drop [1] and break (it means list becomes empty)
5. else change [1] to [3], and drop [1]
6. loop 1~6 until it break

So.. my problem is with usage of `drop`, or implementation of `drop`?
Thank you always.

**Comment by DaeyongKwon98** [comment]
I addtionally find that when I try remove larger value later like remove(1), remove(2), there is error. But when do remove(2), remove(1), it passes the case.
