### ISSUE TITLE
[Homework 5] Error in insert_concurrent 

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#691]
Hi, for growable array, I am implementing a `get` function.

I first tested growable_array, and I passed all cargo tests (I haven't tested asan/tsan yet) except `insert_concurrent`. The error message is 
```
---- insert_concurrent stdout ----
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', tests/map/mod.rs:197:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'insert_concurrent' panicked at 'a scoped thread panicked', tests/map/mod.rs:187:5
```

Line 187 corresponds to assert_eq! statement below.
```
    thread::scope(|s| {
        for _ in 0..threads {
            s.spawn(|| {
                let mut rng = thread_rng();
                for _ in 0..steps {
                    let key = K::rand_gen(&mut rng);
                    let value = rng.gen::<usize>();
                    if map.insert(&key, value, &pin()).is_ok() {
                        assert_eq!(map.lookup(&key, &pin(), |r| *r.unwrap()), value);
                    }
                }
            });
        }
    });
}
```

Since my function passes sequential stress tests, I think there is a data race when there are many threads. I have reviewed my code many times, but I still failed to find the source of error. And it's especially difficult to debug because I cannot use print statements.

Here is the implementation idea.
1. Calculate the desired height of the tree from the input `index`.
2. Start the first loop which repeats the following.
         - Atomically load the `self.root`. If `self.root`'s height is greater than equal to the desired height, break from the loop.
         - Otherewise, create a new segment and initialize segment[0] = raw pointer pointing to the root.
         - perform CAS operation on self.root and update the self.root with the pointable segment with height = original_height + 1.
4. After the first loop is complete, the height of the root should be greater than or equal to the desired height because a tree can only grow and not shrink.
5. Atomically load self.root again. `(let mut root = self.root.load(...))`
6. Start a second loop which repeats the following.
         - Get the height of the root from the loaded root.
         - By using current root's height and index, calculate the corresponding index in the segment.
         - If root's height is equal to 1, first deref the segment from the root using `root.deref()` and return the `Atomic<T>` corresponding to the calculated index. 
         - Otherwise, get the segment pointed by root using `root.deref_mut()`. We will call this segment "segment1."
         - Get the raw pointer stored in the segment1 by using the calculated index. 
                     - If the raw pointer is initialized as zero, create a new segment, segment2, with height = root's height - 1. Set `segment1[calculated_index] = raw pointer pointing to the segment2`. Finally, set `root = segment2` 
                     - If the raw pointer is not zero, it means we already have a segment there.  Let this segment be segment3. Go to the new segment and set `root = segment3`.

I am especially wondering if use of `root.deref_mut()` is okay to access the segment pointed by the root in the multithreaded cases. I have only used SeqCst orderings so far.

Thank you.

**Comment by choejms** [comment]
Hi, I fixed the error in the following way.
The problem was that when I was adding a new segment, I simply updated by 
`segment[index] = atomic_raw_pointer`

Instead I changed the operation above to a CAS operation and `insert_concurrent` passed.

**Comment by Lee-Janggun** [comment]
Ah yes. When preforming updates to CDSs that have multiple writes, one should always use CASes to make sure that the update from other threads are respected. 

In growable array, a common pattern is that (1) one reads `self.root`. (2) do some stuff with info related to the root (mostly the tagged height) and (3) update the root. Between (1) and (3) another thread may have updated the `self.root` value,  so if you naively update `self.root`, the update done by the other thread will be disregarded, which is not what we want.

Doing a CAS ensures that there was no modifications to `self.root` from (1) to (3), hence we can update it.

**Comment by choejms** [comment]
Thank you for the explanation. Appreciate it
