### ISSUE TITLE
[Question HW3] About cursor position in `Cursor::find`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#694]
Ex) List: [2] -> [4]
Insert(1) -> cursor position: ???
Insert(3) -> cursor position: [2]
Insert(5) -> cursor position: [4]

When insert(1), how can I define cursor in first position?

With similar situation, start with empty list.
insert(3) -> List: [3], cursor position: [3]
insert(1) -> how can I insert at left of cursor position?

Is there any way to make cursor to the leftmost of the list?

**Comment by dripcharacter** [comment]
I had same issue and we can't know whether the key should insert left or not in the Cursor::find or OrderedListSet::find.
But, since generic type T in implementing insert function of OrderedListSet has Ord trait, we can compare cursor's key and key to insert.

**Comment by DaeyongKwon98** [comment]
I compare `key` and `data` in `cursor` in `insert`, and deal with that case addtionally.
