### ISSUE TITLE
[Question HW3] How can I change `next` of `node`?

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#695]
While implementing `insert`,
Ex) List: [1] -> [2] -> [4]
Insert(3)

cursor's node: [2]
next_node: [4]

I define new node with `Node::new(key, next_node_ptr)`, which makes [3].next = [4].
Then I need to make [2].next = 3.
Here, `Node`'s next has type `Mutex<*mut Node>`.
So I think I have to define new `Mutex<*mut Node(3)>`, and change [2].next with this.
Is this method (define new mutex and change [2]'s next value with this) right?

**Comment by Lee-Janggun** [comment]
I really can't answer these kind of questions that simply asks if an implementation idea is right or wrong... 

Please try it out and come back if you have a more concrete problem.
