### ISSUE TITLE
[Homework 5] Submission status keeps saying Checking...

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#702]
Hi,
For some reason, the Success? column keeps saying Checking....
<img width="90" alt="스크린샷 2022-10-31 오후 8 05 55" src="https://user-images.githubusercontent.com/90259205/198994102-374a2ec0-5b00-4e07-9fe7-6d520120077f.png">

When I click the log, the scores are displayed and the tests have finished.
What should I do? Is there a problem in the submission server?

**Comment by Lee-Janggun** [comment]
I think the issue is that the server is having a timeout... It may be because SC access is too slow, and we are testing a lot of stuff.
We'll come up with a solution within this week.

**Comment by Lee-Janggun** [comment]
Also, can you send me your code to janggun.lee@kaist.ac.kr so that we can take a look?

**Comment by choejms** [comment]
Hi, I have just sent my code to your email. Thank you!

**Comment by Lee-Janggun** [comment]
We relaxed some tests in https://github.com/kaist-cp/cs431/commit/faf098a086e839fe21535cd90e9df0a4598c0928. Can you try submitting again?

**Comment by choejms** [comment]
Submission works now! Thank you
