### ISSUE TITLE
Server will go down for the planned power outage (Nov 6, 9:00-18:00)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs431#707]
There is a planned power outage for the entire KAIST campus (Nov 6, 9:00-18:00). The server will go down as well.

**Comment by jeehoonkang** [comment]
The server is up again, but the server has been reinstalled. So...
- The SSH fingerprint has changed. You should remove a line in `~/.ssh/known_hosts`.
- Your password (if exists) was reset. Please use SSH key.

**Comment by choejms** [comment]
Hi, could you install LLVM Sanitizer too? 
After the server is reinstalled, I don't think the Address Sanitizers are working anymore.

**Comment by jeehoonkang** [comment]
@choejms I believe it's now addressed.

**Comment by gayeun4195** [comment]
- Your password (if exists) was reset. Please use SSH key.

@jeehoonkang Does it mean that my password had reset to initial password? (123454321)
