### ISSUE TITLE
[Homework 6] How to test cargo_asan

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#709]
Hi,
I am running `./scripts/grade-hazard_pointer.sh` and I am only failing on cargo asan test for retire_threshold_collect.
But the error message only displays 
`running 1 test
test hazard_pointer::retire::tests::retire_threshold_collect ... Test failed:    cargo_asan test  --lib -- --exact hazard_pointer::retire::tests::retire_threshold_collect`

Is there a way to use AddressSanitizer to check where the test is failing?
Or is using AddressSanitizer not possible for tests in grade-hazard_pointer.sh?

Thank you.

**Comment by tomtomjhj** [comment]
```
source scripts/grade-utils.sh
cargo_asan test --lib -- --exact hazard_pointer::retire::tests::retire_threshold_collect
```

**Comment by choejms** [comment]
Thank you!!
