### ISSUE TITLE
Video Lecture for November 9th

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs431#712]
Hi, instead of a regular class, we will have a video lecture on November 9th. In particular, you don't need to come to the classroom.

Please watch the following video, describing the RustBelt project that works to formalize the Rust type system.

https://www.youtube.com/watch?v=1GjSfyijaxo

We may ask questions about the material in the exam.

**Comment by drash99** [comment]
September??? Not november 9th??

**Comment by Lee-Janggun** [comment]
@drash99 Thanks for the notice! I misread my own calendar.
