### ISSUE TITLE
[Homework 4] Grading script fails to prevent use of `Ordering::SeqCst`

### ISSUE THREAD

**Issue by ichianr** [kaist-cp/cs431#715]
Grading scripts of the homework 4, 5, and 6 detect use of `Ordering::SeqCst` with `grep_skip_comment`. However, I found a way to bypass them (i.e., I somehow managed to use `SeqCst` but I got the full score.) I tested it only with the homework 4, but it's highly likely that the homework 5 and 6 will be affected too. I used the `cp-service.kaist.ac.kr` server for testing.

I'm not sure whether it's okay to be uploaded here since it's related to grading. If it's inappropriate, I will report it to TA @Lee-Janggun with an email.

**Comment by tomtomjhj** [comment]
Thanks for the notice. Please report it to jaehwang.jung at kaist.ac.kr.  I'm in charge of the scripts.
