### ISSUE TITLE
[Homework 5] Is it possible to pass the functionality tests **in time** only using `Ordering::SeqCst`?

### ISSUE THREAD

**Issue by giwan-dev** [kaist-cp/cs431#716]
I'm currently working on homewor 5 part 1.
When I run `grade-hash_table.sh` some tests are timed out, so I execute manual test suite, and I got all passed tests but some tests with enormous time cost (ex. `tsan stress_concurrent` took 20373.52s)

I'm not sure that this time cost is caused by my algorithm or `Ordering::SeqCst`.
Should I check my algorithm, or leave it and deal it when working on part 2?

**Comment by Lee-Janggun** [comment]
That... does seem too long. Are you running on the provided server?

I'll check again on the time taken for the model solution.

**Comment by giwan-dev** [comment]
> Are you running on the provided server?

Yes.

Thank you for checking my issue! 🙇‍♂️

**Comment by Lee-Janggun** [comment]
Also, can you send me your code to janggun.lee@kaist.ac.kr ?

**Comment by giwan-dev** [comment]
@Lee-Janggun Sorry for late response. I sent the code right now!

**Comment by Lee-Janggun** [comment]
Hi, sorry for the late response. I just tried timing on the model solution and the one you gave us, and there does not seem to be a significant time difference between the two. 

After `cargo_tsan` has been ran once to prepare the configuration, the model solution passes `cargo_tsan test --test growable_array stress_concurrent` in 31.456s, and yours passes in 37.722s. Can you try again?

**Comment by giwan-dev** [comment]
Oh I missed the test name. Sorry for lack of information. Actually, I tested `split_ordered_list`, not `growable_array`.

Here is my whole manual test script:

```sh
# test.sh

cargo test --test split_ordered_list -- --nocapture stress_sequential > logs/stress_sequential.txt 2>&1
cargo test --test split_ordered_list -- --nocapture lookup_concurrent > logs/lookup_concurrent.txt 2>&1
cargo test --test split_ordered_list -- --nocapture insert_concurrent > logs/insert_concurrent.txt 2>&1
cargo test --test split_ordered_list -- --nocapture stress_concurrent > logs/stress_concurrent.txt 2>&1
cargo test --test split_ordered_list -- --nocapture log_concurrent > logs/log_concurrent.txt 2>&1

cargo_asan test --test split_ordered_list -- --nocapture stress_sequential > logs/stress_sequential_asan.txt 2>&1
cargo_asan test --test split_ordered_list -- --nocapture lookup_concurrent > logs/lookup_concurrent_asan.txt 2>&1
cargo_asan test --test split_ordered_list -- --nocapture insert_concurrent > logs/insert_concurrent_asan.txt 2>&1
cargo_asan test --test split_ordered_list -- --nocapture stress_concurrent > logs/stress_concurrent_asan.txt 2>&1
cargo_asan test --test split_ordered_list -- --nocapture log_concurrent > logs/log_concurrent_asan.txt 2>&1

cargo_tsan test --test split_ordered_list -- --nocapture stress_sequential > logs/stress_sequential_tsan.txt 2>&1
cargo_tsan test --test split_ordered_list -- --nocapture lookup_concurrent > logs/lookup_concurrent_tsan.txt 2>&1
cargo_tsan test --test split_ordered_list -- --nocapture insert_concurrent > logs/insert_concurrent_tsan.txt 2>&1
cargo_tsan test --test split_ordered_list -- --nocapture stress_concurrent > logs/stress_concurrent_tsan.txt 2>&1
cargo_tsan test --test split_ordered_list -- --nocapture log_concurrent > logs/log_concurrent_tsan.txt 2>&1
```

And, `logs/stress_concurrent_tsan.txt` be like,

```text
   Compiling cs431-homework v0.1.0 (/home/s20140219/cs431/homework)
    Finished test [unoptimized + debuginfo] target(s) in 4.53s
     Running tests/split_ordered_list.rs (target/x86_64-unknown-linux-gnu/debug/deps/split_ordered_list-70e64dc2685a8ace)

running 1 test
test stress_concurrent ...  ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 20373.52s
```

**Comment by Lee-Janggun** [comment]
Your `lookup_bucket` is too slow. Switching it with that of the model solution gave it a reasonable time.

**Comment by giwan-dev** [comment]
Ok, then I should focus on my `lookup_bucket`.
Thanks for considerate guidances!
