### ISSUE TITLE
[Question] I cannot access to my server

### ISSUE THREAD

**Issue by gayeun4195** [kaist-cp/cs431#717]
In [@707](https://github.com/kaist-cp/cs431/issues/707), professor said

- The SSH fingerprint has changed. You should remove a line in ~/.ssh/known_hosts.
- Your password (if exists) was reset. Please use SSH key.

I did first line, but I could not access to my account. For server password, I both tried my previous password and original server password(123454321), but both of them didn't work.

Could you please reset my server password? My student id is 20200201. Thank you in advance.

**Comment by Lee-Janggun** [comment]
Please send an email to the professor.

**Comment by jeehoonkang** [comment]
Please consult #728.
