### ISSUE TITLE
[Homework 5] growable array shape

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#718]
Hello!
In the picture below:
1.) (The red circle) is it possible to have a segment and a data element on the same height? I'm asking because according to the explanation in the .md file, we seem to add the segments at the root level everytime we need to increase the indexing.
2.) In get(), we use an index but I don't really see how that index is defined. For example, for the element "cat" , is the index provided 101 100 111 110?
![WhatsApp Image 2022-11-19 at 23 59 18](https://user-images.githubusercontent.com/60548528/203479056-d43297e9-9302-4d93-8782-1fc9ec155a6a.jpeg)

**Comment by tomtomjhj** [comment]
> add the segments at the root level everytime we need to increase the indexing

Right.

>  (The red circle) is it possible to have a segment and a data element on the same height?

No.

> In get(), we use an index but I don't really see how that index is defined.

The deepest level corresponds to the least significant bits.

>  For example, for the element "cat" , is the index provided 101 100 111 110?

110 111 100 101

**Comment by mouna77** [comment]
Okay I see. So unless we are at the last level, everything we load is either a segment or null?

**Comment by mouna77** [comment]
Hello!
if we want to compare indexes to get() an element in the growable_array(), how should we do that? should we compare bit by bit? 
because from what I understand, the index of "owl" can be given as 111 000  but it is actually equal to 000 111 000.
Also, is there a limit to the growable_array() height? does SEGMENT_LOGSIZE not give a maximum to the heigh of the array?

**Comment by tomtomjhj** [comment]
> if we want to compare indexes to get() an element in the growable_array(), how should we do that? should we compare bit by bit?
> because from what I understand, the index of "owl" can be given as 111 000 but it is actually equal to 000 111 000.

You will need to use the height information.

> Also, is there a limit to the growable_array() height? does SEGMENT_LOGSIZE not give a maximum to the heigh of the array?

See https://github.com/kaist-cp/cs431/issues/724

**Comment by mouna77** [comment]
okay I see. But the problem is when I read #567 I saw that the leafs have the tag 0. This made me think that we know the height of the growable_array and with each hop we subtract 1 from it until we reach 0, so we know we reached the leafs.
But I don't see how we can know the height of the growable_array before.

**Comment by Lee-Janggun** [comment]
The height information is something that you will have to maintain as an invariant. 

In particular, the tag of the root should be the height. 

When you being the get function, you can obtain the current height via reading the tag. 

When you update the root, you should update it with the correct height.

**Comment by mouna77** [comment]
okay. I think I see what you mean. Thank you so much!

**Comment by mouna77** [comment]
Hi! 
When it comes to indexing the segments, should I use the usize value as in `inner[usize]` or should I transform it to an integer?

**Comment by Lee-Janggun** [comment]
The Index/IndexMut trait should be implemented for both i32 and usize for slices, so it shouldn't mattrr.

**Comment by mouna77** [comment]
okay! Thank you!
