### ISSUE TITLE
[Question] (Treiber's Stack push implementation)

### ISSUE THREAD

**Issue by KAIST16-Ryu** [kaist-cp/cs431#719]
The push implementation of the Treiber's stack is as follows.

<pre>
pub fn push(&self, t: T) {
    let mut n = Owned::new(Node {
        data: ManuallyDrop::new(t),
        next: Atomic::null(),
    });

    let guard = crossbeam_epoch::pin();

    loop {
        let head = self.head.load(Ordering::Relaxed, &guard);
        n.next.store(head, Ordering::Relaxed);

        match self
            .head
            .compare_exhange(head, n, Ordering::Release, Ordering::Relaxed, &guard)
        {
            Ok(_) => break,
            <b>Err(e) => n = e.new,</b>
        }
    }
}
</pre>

I asked professor that I'm not sure what the **Err(e) => n = e.new** means.

He answered that the compare_exchange returns not only the previous value also returns the value of n, hence it returns new Owned pointer with pointing n. I recommended to check the API to identify it. But I failed to identify that from the API and test code.

Here below the test code result that I've executed. It didn't returned the new value and it returned the previous value.

![image](https://user-images.githubusercontent.com/71695489/203484931-02052b02-0680-47f9-87f1-a546556c4e63.png)

And I couldn't find proper result from the API neither. I think my approach is not correct and I think that it will be helpful if I can find how to find the correct API for this case... Can I have any advice for that where and how can I find the appropriate resources guiding the code? Thank you very much!!!

![image](https://user-images.githubusercontent.com/71695489/203485270-e68065e5-2303-4ad1-8211-6fff3a0aa8fc.png)

![image](https://user-images.githubusercontent.com/71695489/203485551-7b879dcd-c792-4710-976a-c87e0ea054d3.png)

![image](https://user-images.githubusercontent.com/71695489/203485793-dd39dce8-3516-41dc-b1b8-9815d8911758.png)

![image](https://user-images.githubusercontent.com/71695489/203485927-a598f2db-b6c9-4199-a89c-0c54a75dc406.png)

I lost here because it doesn't show any code. it is just a definition.  How can I understand the code from the API? Thank you very much!!!

**Comment by Lee-Janggun** [comment]
You're looking at the wrong API. The API you are looking

**Comment by Allgot** [comment]
@woojinnn, why does it so?
From my understanding, compare_exchange takes the reference (&self), so we can reuse the value..

The below code is the sample:
```
use crossbeam_epoch::Atomic;
use std::sync::atomic::Ordering;

fn main() {
    let ptr1 = Atomic::new(1);
    let ptr2 = Atomic::new(2);
    let ptr3 = Atomic::new(3);
    
    let guard = crossbeam_epoch::pin();
    
    let ptr2_shrd = ptr2.load(Ordering::SeqCst, &guard);
    let ptr3_shrd = ptr3.load(Ordering::SeqCst, &guard);
    
    match ptr1.compare_exchange(ptr2_shrd, ptr3_shrd, Ordering::SeqCst, Ordering::SeqCst, &guard) {
        Ok(_) => println!("oOo"),
        Err(e) => unsafe { println!("current: {:?}, new: {:?}", e.current.deref(), e.new.deref()) },
    }
    
    let ptr1_shrd = ptr1.load(Ordering::SeqCst, &guard);
    match ptr1.compare_exchange(ptr1_shrd, ptr3_shrd, Ordering::SeqCst, Ordering::SeqCst, &guard) {
        Ok(o) => unsafe { println!("o: {:?}", o.deref()) },
        Err(_) => println!("T_T"),
    }
}
```

In the above example, I used ptr1 twice and it had been compiled & executed.

**Comment by Allgot** [comment]
@Lee-Janggun Could you explain the reason why we have to state `n = e.new`?

Can n be altered during the CAS operation? If it is the case, `n = e.new` seems essential. Otherwise, it is unnecessary.

**Comment by Lee-Janggun** [comment]
@Allgot 

> From my understanding, compare_exchange takes the reference (&self), so we can reuse the value..

This is a not a correct observation, as the topic is about what we are trying to make `self` point to, not the pointer itself. I assume you are trying to say that you used `ptr3_shrd` twice? Yes, that is possible as the type is `Shared<_, i32>` which implements `Copy`.

In our example, `n` is `Owned<i32>`, which **does not** implement `Copy`. Hence when we give `n` as a parameter to `compare_exchange`, we give up ownership of it, hence need to get it back for the next iteration of the loop.

You can try deleting the line `n = e.new` yourself and see the error message to indeed see that this is the case.

**Comment by Allgot** [comment]
Oh I got totally confused. Actually I should have focused on `new: P` among the arguments, not `&self`. Thanks a lot!!
