### ISSUE TITLE
[Question] my rust-analyzer failed to load workspace.

### ISSUE THREAD

**Issue by dripcharacter** [kaist-cp/cs431#720]
I am now trying to check my homework source code's test, but I can't do anything because rust-analyzer failed to load workspace.
![image](https://user-images.githubusercontent.com/53895663/203845278-c0e17e32-511e-4b42-8797-9d8447dc233c.png)
Since I can't load workspace, I can't do anything related to cargo.
![image](https://user-images.githubusercontent.com/53895663/203846082-4c19713d-9e03-4eeb-b9ad-cb31f6d4c1f8.png)
I googled it and found some result 'https://users.rust-lang.org/t/cargo-error-error-parsing-override-file/53520'.
Their saying was there is something wrong in Cargo.toml or rust-toolchain. So I made them same as kaist-cp/cs431, but it didn't work.
Pictures under this line are my original Cargo.toml and rust-toolchain.
![image](https://user-images.githubusercontent.com/53895663/203846486-495e02ed-1a57-42b3-a551-7406b0f10018.png)
![image](https://user-images.githubusercontent.com/53895663/203846512-db7970dd-707b-4243-a3a2-ed292a6cb7c2.png)
I really need some helps.

**Comment by tomtomjhj** [comment]
try `cargo clean`

**Comment by dripcharacter** [comment]
cargo clean didn't work, but I just remake Cargo.toml and it worked... Thank you.
