### ISSUE TITLE
[Homework-Arc] Confusion about make_mut

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#721]
Hello!
I understood that to return a mutable reference to the data, when we have counter>1, we need to create a new arc containing a copy of the initial data. Only we can't return it since it's owned by the function. Even using `Arc::get_mut_unchecked(new_arc) `fails.
I tried to return `Arc::get_mut_unchecked(this)`, but this still points to the previous data which is still referenced 1 or more times, which can't be done.
Am I missing something here? 
And in the .md file, we have that we need to clone the inner value, I don't suppose this means cloning the ArcInner? Because we need a new counter for the new allocation, no?

**Comment by tomtomjhj** [comment]
> Only we can't return it since it's owned by the function. Even using `Arc::get_mut_unchecked(new_arc) `fails.
> I tried to return `Arc::get_mut_unchecked(this)`, but this still points to the previous data which is still referenced 1 or more times, which can't be done.
> Am I missing something here?

Sorry I don't understand the question. Can you elaborate?

> And in the .md file, we have that we need to clone the inner value, I don't suppose this means cloning the ArcInner? Because we need a new counter for the new allocation, no?

You're right. You only need to clone the inner value, and do `Arc::new()`.

**Comment by tomtomjhj** [comment]
> sorry ... I don't think I get what you mean by cloning the inner value.

clone `T`

> when I implemented get_mut, I tried to return the data of the newly created arc

You mean make_mut, right? Note that the type of `this` is `&mut Self`, so you can change `this`.

**Comment by mouna77** [comment]
Ah! yes I get it now. Thank you!
