### ISSUE TITLE
[Homework 5]trivial question about with_tag()

### ISSUE THREAD

**Issue by dripcharacter** [kaist-cp/cs431#724]
In class, professor said that tag uses least significant bits(LSBs) in pointer.(Since pointer is made by block as unit, some LSBs is not important in pointer specification.)
When I used with_tag and tag in rust playground(https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=96cde5b7a4573bbc36391b49e3d95878).
It looks like tag uses 3 LSBs and if tag exceeds 7(which is biggest number with three bits), they do mod operation(like 0=8mod8, 1=9mod8).
Then I think we can specify our height in growable array by 0 to 7...
Does my conclusion is right?
If then, does our homework assume that our index is under 1024^8?

**Comment by tomtomjhj** [comment]
1024^8 is bigger than the range of usize.

**Comment by Lee-Janggun** [comment]
You don't need to worry about height being out of range for the tag
