### ISSUE TITLE
[Homework5] Problem with recursive drop

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#725]
Hello!
I tried to implement a recursive way to drop the growable_array. So at some point I did a loop where I create a new instance of growable_array with one of the segments as the head.
but I get the following error: `expected array of 1024 elements, found struct `std::sync::atomic::AtomicUsize`` about the new growable array I created. and I get the error `explicit destructor calls not allowed help: consider using `drop` function: `drop`` about the use of GrowableArray::drop() inside the drop() function.

I think that I understood drop() wrong. Can you please help?

**Comment by tomtomjhj** [comment]
> I tried to implement a recursive way to drop the growable_array.  So at some point I did a loop where I create a new instance of growable_array with one of the segments as the head.

GrowableArray itself is not recursive. Segment is recursive. 


> and I get the error `explicit destructor calls not allowed help: consider using `drop` function: `drop about the use of GrowableArray::drop() inside the drop() function.

`something.drop()` → `drop(something)`

**Comment by mouna77** [comment]
I'm sorry but does this mean I should implement a recursive drop function on segment?

**Comment by Lee-Janggun** [comment]
That is the "expected" way. You can also probably use a loop, but it should be more helpful to have something like follows:

```rust


impl Segment {

  /// You may want just `&self`, not a `&mut self`, depending on your implementation.
  fn drop_segment(&mut self) {
    ...
  }
}
```
and call the above function in `Drop` for `GrowableArray` and anywhere else you might need..

**Comment by mouna77** [comment]
I see ... thank you!
