### ISSUE TITLE
[Lecture] Why can't write be a Single Instruction Commit Point?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#726]
Hi, 
I am looking at the slide below.
<img width="848" alt="스크린샷 2022-11-28 오후 7 33 05" src="https://user-images.githubusercontent.com/90259205/204256094-0803330a-fb47-48fb-b8f7-8fe8fa8eda5d.png">

What is the function of single instruction commit point?
I think it's a concept necessary for proving that there is a progress in a lock-free data structure.
But in that case, I don't understand why Write cannot be a single-instruction commit point because the fact that there is a successful write operation also shows that there is a progress.
Can anyone explain why RMW can become a commit point but write can't?

Thank you.

**Comment by tomtomjhj** [comment]
That slide has been slightly edited. Please check.
