### ISSUE TITLE
[Question] Linearization in Michael-Scott's queue

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#730]
Hi,
<img width="812" alt="스크린샷 2022-12-01 오전 1 40 51" src="https://user-images.githubusercontent.com/90259205/204856628-f3b94ff6-6f8c-46f3-9c3c-214c77c8cf4e.png">

I have a question about why Michael-Scott's queue is linearizable.
In my understanding, a data structure is linearizable if operations can be ordered in a sequential manner.
Since push() and pop() operation occurs on different places in queue (head and tail), I think it's possible that they happen at the same time.
Then we may not be able to order push() and pop() operations.

Then why is MS queue linearizable?

**Comment by tomtomjhj** [comment]
Linearization is a concept defined in sequentially consistently memory model, where instructions are totally ordered.

There are various ways to formulate consistency conditions for libraries in weaker memory model, but they are quite complex. So in this lecture we only consider the sequentially consistent version.

**Comment by choejms** [comment]
Does that mean Michael Scott's queue is not linearizable?

**Comment by tomtomjhj** [comment]
When we say something is linearizable, we implicitly assume that we are considering the implementation in the sequentially consistent memory model (because otherwise, such a statement does not make sense).

So, Michael Scott's queue is linearizable.

**Comment by choejms** [comment]
Thank you for the explanation
