### ISSUE TITLE
[Question] Build failed in gg submission

### ISSUE THREAD

**Issue by smpak19** [kaist-cp/cs431#731]
Hi, I'm just finished HW4 and submitted arc.rs in gg.kaist.ac.kr.
But I got this 'build failed error'. Is this my problem?
Thank you.
`Running with cargo_asan...
Build failed! Error message:
error: "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
--------------------------------------------------------------------------------`

**Comment by jeehoonkang** [comment]
@smpak19 would you please try again?

**Comment by smpak19** [comment]
Now it works! Thank you professor.
