### ISSUE TITLE
[Homework 5] Atomic<T> or Atomic<Segment>

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#732]
Hi!
In the _hash_table.md_ file, you said to use `from_usize `and `into_usize ` for integer-pointer casts, but you also mentioned #225 . And in this issue, we just use `as *const Atomic<T>` to get the `Atomic<T>` from `AtomicUsize`. 
This confused me since if we don't know the type of the `AtomicUsize`, how can we use `as *const ....`?

**Comment by mouna77** [comment]
sorry, I meant if we don't know if the AtomicUsize is an Atomic<T> or an Atomic<Segment>.

**Comment by tomtomjhj** [comment]
>  if the AtomicUsize is an Atomic< T > or an Atomic< Segment >.

You need to use the height information.

> how is getting the usize representation of Atomic< T > different than that of Atomic< Segment > ??

The physical representations of `Atomic<T>` and `Atomic<Segment>` are exactly the same (ignoring the tags). They are just memory addresses. This is why you need to make use of the height.
