### ISSUE TITLE
[HW5 Question] My address sanitizer doesn't work well

### ISSUE THREAD

**Issue by dubuduru** [kaist-cp/cs431#734]
Hello,

I'm working on homework 5 with cargo-asan.
However, it does not give clear description about the memory leak problem.
When I run the code with cargo-asan, it gives me traceback, but with meaningless descriptions as below:

In previous homeworks, it gave me exact name of functions and locations of them. However in this time it gives me outputs that are not understandable..

I saw the issue about similar problem, but I cannot find it. How can I fix this?

**Comment by tomtomjhj** [comment]
Fixed. Please try again.
