### ISSUE TITLE
[Question] Garbage collection

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#738]
When we talked about epochs in EBR and PEBR, were we talking about the access to one memory location?
As in if thread T1 accesses x and y and thread T2 accesses x and thread T3 accesses y, if we want to draw the active states of these threads, the epoch for T2 and T1's access to x and the epoch of T1 and T3's access to y would be totally different and unrelated? is that right?
And If I understand correctly, I can't start an e+n instance, while a thread of instance e+n-2 still has an active state?

**Comment by Lee-Janggun** [comment]
No, epochs are independent on the locations. In your case, any pair of T1 T2 T3 must satisfy the epoch consensus rule.

**Comment by mouna77** [comment]
Even if T2 and T3 are not concurrent? should they satisfy the epoch consensus rule as well?

**Comment by Lee-Janggun** [comment]
Non concurrent threads do not need to satisfy the epoch consensus ruke.

**Comment by mouna77** [comment]
okey Thank you!
