### ISSUE TITLE
[Question HW6] About `try_protect`, `Shield::drop`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#740]
In `try_protect`, step 1 is `Store *pointer to the hazard slot.`

My method is
1) Get `*const HazardSlot` from `next` field of given `HazardSlot. (self)`
2) Keep going to next `HazardSlot` while next pointer is `null`. (with `is_null()`)
3) Change `null` pointer to given `*pointer`.

But type of `*pointer` is `*const T`, and `next`'s type is `*const HazardSlot`, so there's an error. How can I deal with this? **(Q1)**

Also, when I call `Shield::drop`, is it right to drop one `HazardSlot` I get from `self`?
Or do I have to drop all `HazardSlot` in same `HazardBag`? (In this case I have to keep moving with `next` field.) **(Q2)**

**Comment by Lee-Janggun** [comment]
Q1: You shouldn't need to do try_protect yourself. Please check the updated skeleton code.

Q2: You should only care about the slot the shield is owning.
