### ISSUE TITLE
[Homework 6] HazardSlot

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#741]
Hello!
I'm curious as to why you chose the 'next' field in `HazardSlot` to be an immutable pointer and a `*const` ?

**Comment by Lee-Janggun** [comment]
We need a raw pointer here because we want HazardBag's head to be an atomic pointer, and it is immutable, so we use a `* const`.

**Comment by mouna77** [comment]
Okay. I see thank you!

**Comment by mouna77** [comment]
Hello!
after reviewing treiber's stack, I don't see how the next field can use *const. Because we actually need to modify it in push() L50.

**Comment by Lee-Janggun** [comment]
We dont use the raw pointer to modify the data it points to, hence why we have it as a const pointer.

**Comment by mouna77** [comment]
I see. Thank you!
