### ISSUE TITLE
[Question] Why do we send guard as parameter in Michael-Scott's queue?

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs431#742]
I think we dealt this issue during the class, but I forgot the reason...
We manually `pin()` in [Treiber's stack implementation](https://github.com/kaist-cp/cs431/blob/main/src/lockfree/stack.rs#L46) whereas [Michael-Scott's methods](https://github.com/kaist-cp/cs431/blob/main/src/lockfree/queue.rs#L68) take guard as an argument.
What is the underlying reason for that design choice?

**Comment by Lee-Janggun** [comment]
By doing this, we can send an unprotected guard to the methods so that they can be more efficient when we don't need smr, e.g, destructors.

**Comment by woojinnn** [comment]
Oh, you mean that it would be better to pass guard in Stack implementation, right?

**Comment by Lee-Janggun** [comment]
Yes, at least I think so.
