### ISSUE TITLE
[Homework 5 ] buckets' cursor

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#744]
Hello!
I wanted to ask about the cursor , because I think my lookup_bucket implementation is wrong.
From what I understand, we have to make a cursor using the Cursor struct in lock free List.
Then use the cursor to go through the growable array and get the index to the bucket that has the same index.

But it seems weird since the cursor is created by the list, but we use it to go through the last segments of the growable array.
Is that right? If not can you please clarify this?

**Comment by Lee-Janggun** [comment]
> Then use the cursor to go through the growable array and get the index to the bucket that has the same index.

This is not true. They way you should go around the growable array is via the get function you have implemented.

> But it seems weird since the cursor is created by the list, but we use it to go through the last segments of the growable array.

When this will happen is when you recursively initialize the parent bucket. When this is done, you will get a cursor to the parent, and can use this to move the cursor to the desired child index.

**Comment by mouna77** [comment]
So is this true?:
The traversal of the growable array is by using the get() function.
the traversal of the list is done through a certain cursor from the struct Cursor.
And the child buckets that are actually directly linked to the list are the segments of height = 1

**Comment by Lee-Janggun** [comment]
Yes, that's how you should view it. The array is a way of getting to a location in the list quickly.

**Comment by mouna77** [comment]
I see. But is using the cursor from the Cursor struct the right way to go? Because I saw that its curr field is private and so I don't think that would help me much.
Should I just use a new cursor struct for the splitorderedlist?

**Comment by Lee-Janggun** [comment]
You shouldn't need to need to access the cursor's struct directly. If you want to make a new cursor, just use Cursor::new

**Comment by mouna77** [comment]
Yes I understand that, but my problem is that when I try to use the cursor for traversal, which I believe is the purpose of it. I can't update the curr and prev values since they are private.

**Comment by Lee-Janggun** [comment]
Your not suppose to update it yourself; the cursor methods (e.g, find_harris) will do that for you.

**Comment by mouna77** [comment]
I see. Thank you!
