### ISSUE TITLE
[Question] [Homework 5] I have very rare rate of failure in my code...

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs431#746]
I think I made some mistakes in my delete function in split_ordered_list
But the error case is very very rare so I can't successfully check my error.. 
(expected failure rate is about 1~5%.. even I successfully passed the test cases in gg and I got full score except memory ordering...)
I really really want you to check my code and please give me any small advice..

**Comment by Lee-Janggun** [comment]
What are the errors you are getting? What is your high-level idea in delete? 

I really can't simply 'debug your code' with no information. Please open a new issue with more specific questions.

**Comment by Meraroo** [comment]
In some part of my code, I missed dealing with some cases of `cursor.find( ... )`. It doesn't affect in most of cases, but it somehow affects the deletion of the list then It may cause an undefined behavior (deleting the sentinel node, etc)
If you suffer from very rare undefined behavior with deletion, checking if you really dealt of every cases of `cursor.find( ... )` might be helpful.
