### ISSUE TITLE
[Question] cargo_asan not found

### ISSUE THREAD

**Issue by Ariaspect** [kaist-cp/cs431#751]
Suddenly my cargo_asan wouldn't work...
![image](https://user-images.githubusercontent.com/101387210/206812118-3cae105e-9ce1-49ba-a8db-22bc77c52167.png)
As I was testing, testing with cargo_asan would never end, so I tried that.
I think my local repository got corrupted(?).

Is there any way to re-install or re-initialize cargo_asan command?

**Comment by Lee-Janggun** [comment]
Run '. ./scripts/grade-utils.sh'

**Comment by Ariaspect** [comment]
After the installs, it's still not found...

**Comment by Ariaspect** [comment]
Oh it was '. ./scripts/grade-utils.sh', it works now, thx!
But still, the cargo_asan test would never end even after 10s (timeout).
I think my code is wrong somewhere.
