### ISSUE TITLE
[Question] Case #19 in Causality Test Cases

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#753]
[Causality test case 19](http://www.cs.umd.edu/~pugh/java/memoryModel/CausalityTestCases.html)
```
Initially,  x = y = 0

Thread 1:
join thread 3
r1 = x
y = r1

Thread 2:
r2 = y
x = r2

Thread 3:
r3 = x
if (r3 != 42)
  x = 42

Behavior in question: r1 == r2 == r3 == 42
```

Website's explanation: Decision: Allowed. This is the same as test case 17, except that thread 1 has been
  split into two threads.

According to the slides, the the decision is in fact disallowed. (Case19 is in fact one of wrong test cases according to our slide).
I also read [Zhao's slide](https://docs.google.com/presentation/d/1INonaKICTV7ygiams-0xkA6BjCv3L_kFLtE8_Zp66xI/edit#slide=id.p), but I do not understand why X = 42 is not recertified. I think X = 42 is recertified if Thread 1 updates its view to Y = 42 and Thread 2 updates its view to X = 42.

Even in the slide, he says "If we update thread 1’s view first, then it is fulfillable."

Then why is the test case above disallowed?

**Comment by dubuduru** [comment]
Have you seen [this issue](https://github.com/kaist-cp/cs431/issues/131#issuecomment-706830784)? I think it is understandable explanation.

**Comment by choejms** [comment]
Thank you!
