### ISSUE TITLE
[Question] Necessity of Acquire ordering in MS queue

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs431#755]
I mostly understood the rationale behind the choice of orderings for MS queue, except for this [one](https://github.com/kaist-cp/cs431/blob/main/src/lockfree/queue.rs#L128)

This load has an `Acquire` ordering, so it will acquire the snapshot that `head.next` holds. 

I understood that the [previous load](https://github.com/kaist-cp/cs431/blob/main/src/lockfree/queue.rs#L125) requires an Acquire ordering because `head.next` is accessed afterwards and if it doesn't have an acquire ordering a wrong `head.next` can be read.

However, I don't understand whiy the `Acquire` ordering is necessary for the load of `head.next`. What problems will arise if it is changed to `Relaxed`?

**Comment by pr0cf5** [comment]
Thinking about it, I realized the reason. It must transitively pass the snapshot via the consecutive CAS. (to swing the tail)

If my thinking is wrong, please tell me. I will leave this issue open for the sake of it.

**Comment by choejms** [comment]
Hi, actually I don't understand why Acquire ordering is necessary either. 
Could you elaborate what you mean by "transitively pass the snapshot via the consecutive CAS"?

Thank you

**Comment by pr0cf5** [comment]
Oh, thanks for giving interest about this issue.

First, I want to ask, do you think all `Acquire` orderings are unncesseary or only the one in line 128 is unnecessary?

My understanding about why `Acquire` for line 128 is necessary is as follows:

By the load in 125, the view for `head` is obtained.

By the load in 128, the view for `head.next` is obtained.

Then, if `tail` == `head`, `next` is 'maybe' written to `self.tail` via CAS. This write is a release, which means that the view obtained in line 128Then, if `tail` == `head`, `next` is 'maybe' written to `self.tail` via CAS. This write is a release, which means that the view obtained in line 128 is 'released'.

Then `next` is used in CASes after the load, where views are released. If line 128 is not `Acquire`, the view released in the CASes will not be recent enough.

**Comment by pr0cf5** [comment]
Never mind what I just said. The slides corroborate my initial claim, so I this matter is still in question.

**Comment by woojinnn** [comment]
In MS queue, unlike Treiber's stack, since tail side is also updated, same logic that you reasoned about `self.head`'s acquire_load should be applied equivalently I think.

**Comment by tomtomjhj** [comment]
It's necessary for `next_ref.data.assume_init_read()`.

**Comment by imsj114** [comment]
I understand that `Acquire` is needed at line 128 because it accesses the inner data.

However, do we need `Acquire` at [line 81](https://github.com/kaist-cp/cs431/blob/main/src/lockfree/queue.rs#L81) also? 
It seems that we use `next` only as a pointer, where its view is guaranteed when we load `tail` with `Acquire`.

**Comment by tomtomjhj** [comment]
The view of msg in `self.tail` must have seen the msgs of the pointed node's fields. To maintain this invariant at `self.tail.compare_exchange(tail, next, Release, ...)`, you should release the view that has seen the msgs of fields `next`. You obtain this from `tail_ref.next.load(Acquire)`. This works because the view of msg in `next_ref.next` must have seen the msgs of the pointed node's (`next`'s) fields.

**Comment by choejms** [comment]
Could you explain why we need Acquire ordering at line [77](https://github.com/kaist-cp/cs431/blob/518270ed6e35132361a6dbc45c79a6801faf74ea/src/lockfree/queue.rs#L77) too?

**Comment by tomtomjhj** [comment]
> Could you explain why we need Acquire ordering at line 77 too?

necessary for `tail_ref.next.load(...)`

**Comment by choejms** [comment]
Could you explain why the invariant that the tail's view has a release view greater than next pointer's view is important? Thank you in advance.

**Comment by tomtomjhj** [comment]
Otherwise, `tail_ref.next.load` may read uninitialized value.

**Comment by choejms** [comment]
So if I am understanding correctly, you are saying next in `let next = tail_ref.next.load(...)` could lead to `next` being `Shared::null().` But subsequent CAS will fail in line [96](https://github.com/kaist-cp/cs431/blob/518270ed6e35132361a6dbc45c79a6801faf74ea/src/lockfree/queue.rs#L98) if it is the case that tail_ref.next is in fact not a `Shared::null()`. So I don't see what problems will arise even if `tail_ref.next.load` readsuninitialized value. 

Why is tail_ref.next.load reading an uninitialized value problematic?

**Comment by tomtomjhj** [comment]
Uninitialized value is not just `Shared::null()`. It's an imaginary and arbitrary value, and using it is immediately UB. https://doc.rust-lang.org/nomicon/uninitialized.html

**Comment by choejms** [comment]
Wow that's a big thing I have missed! Ok that explains a lot. Thank you
