### ISSUE TITLE
[Question] Questions about MS queue, HHS find, Epoch consensus

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#756]
**Q1**. In lecture slide 61, 
In pop, why updating tail if it points to the dummy?
To make sure head doesn’t “overtake” tail (why? see the GC part)

But I can't find explanation about this in GC part. What's the reason?

**Q2**. In lecture slide 63,
Why HHS cannot be used for insert/delete?
Cursor’s “prev” may have already been deleted and cannot be updated

In which situation this happens?

**Q3**.
Epoch consensus rule says concurrent epochs may differ by at most 1.
![image](https://user-images.githubusercontent.com/70640395/206890933-d6ff8e21-2360-4803-99b3-87130dea656d.png)

Then T2's first active state, T3's active state can be e or e+1.
How can we define to use between e and e+1?
(Define to use same epoch, or increment one)

**Q4**.
In lecture slide 73, the order of successful CAS on head, node's next pointers are DS operation order, but not on tail.
Why tail's CAS is excluded?

**Comment by tomtomjhj** [comment]
Q1: For safety of `defer_destroy(head)`, you should guarantee that `head` is unreachable from the queue. If `self.tail` lags behind `self.head`, `head` can be reachable by `self.tail`.

**Comment by tomtomjhj** [comment]
Q2:
`remove(1)` and `add(2)` are running concurrently
```
┌────┐      ┌────┐                  ┌────┐
│head├─────►│ 1  ├────────/────────►│ 3  │
└────┘      └────┘                  └────┘
```

Possible outcome: 2 is not added
```
  ┌───────────────────────────────────┐
  │                                   ▼
┌─┴──┐      ┌────┐      ┌────┐      ┌────┐
│head│      │ 1  ├─────►│ 2  ├─────►│ 3  │
└────┘      └────┘      └────┘      └────┘
```

**Comment by tomtomjhj** [comment]
Q3: define what?

**Comment by tomtomjhj** [comment]
Q4: The tail pointer is basically a shortcut to the last node. MS queue works like a proper queue even if you remove the tail pointer and traverse to the last node when enqueuing.

**Comment by DaeyongKwon98** [comment]
> Q3: define what?

I mean is it possible to be like this. I think this case doesn't violate epoch consensus..
![image](https://user-images.githubusercontent.com/70640395/206895767-0e684987-4816-439b-afbf-a07e5bb55ce4.png)

But I think this can't be possible, so active state which start later than epoch e should be larger than e?

**Comment by Lee-Janggun** [comment]
Q3: the epoch will try be as large as possible. When pinning a new thread, if there is a thread at epoch e and e + 1, the epoch will be e + 1. If there is only a thread at epoch e, it will be pinned at epoch e + 1. If there are no other threads, it can really be pinned at anything.
