### ISSUE TITLE
[Question] Difference between as_ref().unwrap() and deref() of Shared

### ISSUE THREAD

**Issue by dubuduru** [kaist-cp/cs431#760]
Hello! While reading code of lock-free list, I have a question about dereferencing Shared.

I wonder what is the difference between those 2 lines below:
```rust
unsafe {node.deref()}
```
```rust
unsafe {node.as_ref()}.unwrap()
```

When the pointer is null, 2 lines all fail, and when the pointer is not null, they all succeed. Is it right?
Then what is the difference between them?

**Comment by hotmandu** [comment]
In crossbeam's source code:
```
    pub unsafe fn deref(&self) -> &'g T {
        let (raw, _) = decompose_tag::<T>(self.data);
        T::deref(raw)
    }
    pub unsafe fn as_ref(&self) -> Option<&'g T> {
        let (raw, _) = decompose_tag::<T>(self.data);
        if raw == 0 {
            None
        } else {
            Some(T::deref(raw))
        }
    }
```
So... I think these two are very similar, except that `.as_ref()` makes you more cautious of dereferencing if you might be holding a null pointer.

**Comment by dubuduru** [comment]
Thanks!

**Comment by Lee-Janggun** [comment]
Yes, unwapping the result from as_ref immediately is the same as deref in correct code. Now in incorrect code where you have a null pointer when it shouldn't, the unwrap would panic, but the deref will UB.
