### ISSUE TITLE
[Question] Does attendace score affect grade?

### ISSUE THREAD

**Issue by dubuduru** [kaist-cp/cs431#762]
Hi,

In the main page of this repo, it says attendance affects ?% of the total grade and if I miss a significant number of sessions, I'll automatically get an F.
Then what is the threshold for F? If my absences do not exceed the threshold, then the attendance status doesn't affect the final grade?

Thank you :)

**Comment by Meraroo** [comment]
I remember professor said he will not consider attendance at all because he trust us.. right?

**Comment by dubuduru** [comment]
I think he said he will not check attendance after midterm because he trusts us... Does that meant he will not consider attendance at all?

**Comment by Meraroo** [comment]
I believe professor

**Comment by jeehoonkang** [comment]
If attendance affects your letter grade, I'll individually contact you.
