### ISSUE TITLE
[Question HW6] `Shield::set`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#766]
In `Shield::set` function, I have to store `pointer` to the hazard slot.

`Hazardslot` has `hazard` field, which has type `AtomicUsize`, which is machine representation of hazard pointer.

So I think with `store` function, I have to store `pointer` to `Hazardslot.hazard`.
But how can I change `pointer: *mut T` to `usize`?

**Comment by Lee-Janggun** [comment]
You can cast using 'pointer as usize'.
