### ISSUE TITLE
[Question HW6] `collect` in `RetiredSet`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#767]
In `retire.rs`, I try to implement `collect` like this.

1. Iterate over vector `self.inner`.
2. For each `(pointer1,fn(pointer2))`, check if `pointer1` is in `hazardbag`.
    If it's in `hazardbag`, it means it's `protected`.
3. If it doesn't exist in `hazardbag`, call `fn(pointer2)` to free.

But when I try to use `head` field of `hazardbag`, it says `field head of struct HazardBag is private`. How can I deal with this?

**Comment by Lee-Janggun** [comment]
you should implement the [`all_hazards`](https://github.com/kaist-cp/cs431/blob/518270ed6e35132361a6dbc45c79a6801faf74ea/homework/src/hazard_pointer/hazard.rs#L150) function and use that.

**Comment by DaeyongKwon98** [comment]
Now I implement `collect` using `all_hazards` like below.

1. Iterate over vector `RetiredSet.inner` until it gets to `Threshold`.
2. Check if `pointer` is contained in `hazardset` I get from `all_hazards`.
3. If it's not contained, it means that I can free. So call `f(p)`.
(`inner` has `Vec(usize, fn(usize))`, and I call this `Vec(f,p)` above.)

But I get `invalid memory reference`. What's wrong with my implementation?

**Comment by Lee-Janggun** [comment]
I don't get what you are doing with 1. The other steps seem fine.

**Comment by DaeyongKwon98** [comment]
Isn't `RetiredSet.inner` a vector of retired pointers?
I mean step 1 is check for all pointer in `RetiredSet` to be contained in `hazardset`.
More specifically, I do like this
```rust
while n < threshold {
    let (p,f) = self.inner[i]
    if p not contained in hazardset f(p)
    i+=1
}
```

**Comment by Lee-Janggun** [comment]
Ah ok, I see the misunderstanding. `THRESHOLD` is a parameter to **call** collect when the length of `inner` is too long. In particular, it shouldn't be used in `collect()`, but you should use it in `retire` and call collect if the local retire set is too large. 

In `collect`, you should try to retire whatever is in the `inner`.

In terms of the invalid memory reference, I'm not 100% sure what is the cause, but try using asan and see what it says.

But I do see a leak in your psuedo-code. consider this: should nothing else be done in the else branch?

**Comment by DaeyongKwon98** [comment]
>In particular, it shouldn't be used in collect(), but you should use it in retire and call collect if the local retire set is too large.

Using this, I change `threshold` in code above with `self.inner.len()`. So it can iterate with the length of vector.

>But I do see a leak in your psuedo-code. consider this: should nothing else be done in the else branch?

You mean when I check if `pointer` is in `hazardset` (else branch), I have to do something? I think then `pointer` should remains in `RetiredSet`, so I have to do nothing..

**Comment by Lee-Janggun** [comment]
Oh... if you remembered to remove it from the retire set if you freed it, and left it if you didn't then I'm not sure what the problem is.
