### ISSUE TITLE
[Question] How can I iterate using *const next in try_acquire_inactive?

### ISSUE THREAD

**Issue by Allgot** [kaist-cp/cs431#768]
In hazard.rs, HazardSlot's next field is *const HazardSlot type. Because of this, I cannot use trivial iteration strategy:
```
loop {
   let mut cur = ~~;
   (...)
   cur = cur.next;
}
```

Thus, I tried a recursive function for iteration:
```
impl HazardSlot {
   fn iterating_find(&self) -> Option<&self> {
   (...)
}
```

Then I got stack-use-after-return error. Is there any other way to iterate in this condition?

**Comment by Lee-Janggun** [comment]
The first is precisely the loop that is being done in the model solution. Are you working on the most recent skeleton? What is your error?

**Comment by Allgot** [comment]
Do you mean [this](https://github.com/kaist-cp/cs431/blob/main/homework/src/hazard_pointer/hazard.rs#L64-L68), by the 'model solution'?

If it's right, then I cannot get how to use it for `HazardSlot`. In my case, I want to iterate through mutating cur(using `cur = cur.next`) but since cur.next is *const, it is impossible to assign cur.next into cur.

**Comment by Lee-Janggun** [comment]
I meant the model solution we have  separately in private.

The fact that one has a *const T field should not block one one reassigning it, what we can't to is write to the value stored in the pointer.

What is the compiler error you are getting?

**Comment by Meraroo** [comment]
[`as`](https://doc.rust-lang.org/std/keyword.as.html) may works

**Comment by Allgot** [comment]
Ohh... the compiler error was simply a type error, but `as` really worked....

This is quite interesting, because I didn't expecet that I could convert *const to *mut!
