### ISSUE TITLE
[HW 5] asan output isn't understandable

### ISSUE THREAD

**Issue by Ariaspect** [kaist-cp/cs431#769]
![image](https://user-images.githubusercontent.com/101387210/208243700-86a5d432-2eb8-41d2-88c0-3c661ed1de34.png)

This is a part of my output running cargo_asan test, and there's no line # or function name at all in the log... Is it supposed to be like this?

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs431/issues/644 may help you

**Comment by Ariaspect** [comment]
I'm using WSL2 in Win 10 and there's no such file..?
Maybe this is WSL issue, I should reinstall llvm, but in what version should I install?

**Comment by Ariaspect** [comment]
Ok after the installation `llvm-symbolizer-8` now exist.
And after linking it to `llvm-symbolizer`,
`llvm-symbolizer: Unknown command line argument '--inlines'.  Try: '/usr/bin/llvm-symbolizer -help'
llvm-symbolizer: Did you mean '-inlining'?`
So I think my installation version was not correct...
Although I fixed memory leaks, it still doesn't work.

**Comment by Ariaspect** [comment]
Ok finally it works.
```
sudo apt update
sudo apt install clang lldb lld
```
and after symlink, it shows file, function, line # properly!
