### ISSUE TITLE
[Homework 5] growable array timeout

### ISSUE THREAD

**Issue by kimdh98** [kaist-cp/cs431#770]
When I try to run tests on cargo, log_concurrent takes about 4s and stress_concurrent takes about 90s.
I tried both on SeqCst and relaxed memory, but they give around the same runtime.
Is this likely due to my relaxed memory version being wrong or is there something fundamentally wrong with my implmentation?

**Comment by Lee-Janggun** [comment]
Something is probably fundamentally wrong.

**Comment by kimdh98** [comment]
It was a println in one of the loops
