### ISSUE TITLE
[Question HW4] Is there any methods to take owndership of data: T in try_unwrap?

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs431#771]
```
let data = inner.data
return data
```
produces an error about memory leak
So, I noticed that there's hint about using mem::forget, but
```
let data = inner.data
mem::forget(data) // takes ownership of data
// I can't use data here
```

How can I take ownership of data with `forget(data)`

**Comment by Lee-Janggun** [comment]
In successful unwrap, we are converting the ownership of 'this' into the inner value, hence we should not call the destructor of 'this'.

**Comment by Meraroo** [comment]
Oh thanks for your advice. I think I was confused about what actually 'unwrap' does.
