### ISSUE TITLE
[Question] u64 in hw5 submission

### ISSUE THREAD

**Issue by SIC98** [kaist-cp/cs431#774]
I submitted the hw5 assignment to gg, and found something strange.
My code failed the `stress_sequential` test as below, I find that the number `4612812193279276113` is used.
The number seems to be of `u64` type, but our code only  support `u32` type.
Is this a bug or is there something I'm misunderstanding?

```
Testing split_ordered_list stress_sequential with cargo --release, timeout 10s...

running 1 test
test stress_sequential ... FAILED

failures:

---- stress_sequential stdout ----
iteration 0: insert(4612812193279276113, 9177852394473909692)
iteration 1: delete(4612812193279276113) (existing)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Err(())`,
 right: `Ok(9177852394473909692)`', tests/map/mod.rs:64:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
drop!

failures:
    stress_sequential

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.00s
```

**Comment by tomtomjhj** [comment]
> but our code only support u32 type.

no

**Comment by Meraroo** [comment]
I think it should be `usize`, not `u32` or `u64`

**Comment by SIC98** [comment]
My question was from looking at the code below. Does `gg` use other test code?
https://github.com/kaist-cp/cs431/blob/518270ed6e35132361a6dbc45c79a6801faf74ea/homework/tests/growable_array.rs#L17-L22

**Comment by tomtomjhj** [comment]
The error is coming from split_ordered_list, not growable_array

> Testing split_ordered_list stress_sequential with cargo --release, timeout 10s...

**Comment by SIC98** [comment]
Opps It's my mistake. Thanks!
