### ISSUE TITLE
[HW5] Is there any way to provide find function to list.rs methods which is private.

### ISSUE THREAD

**Issue by Ariaspect** [kaist-cp/cs431#775]
I found it weird that find, lookup, insert, and delete are private methods.
Basically what I'm trying to do is implement my own find function that can move the cursor efficiently using the bucket array, then feed it to list.rs methods.
In this way I can avoid a lot of hassle like returning lookup value (node.value is also private so I can't have access).
Is my method not allowed?

**Comment by Meraroo** [comment]
You may create cursor then you can use functions like `cursor.find_harris()` .. etc

**Comment by Ariaspect** [comment]
I did. 
> Basically what I'm trying to do is implement my own find function that can move the cursor efficiently using the bucket array, then feed it to list.rs methods.
It is used to implement my own find function. But only using cursor to implement lookup,

**Comment by Ariaspect** [comment]
Omg, I just notice that "Cursor" methods are public... while I was looking at "List" methods 
thx!!
