### ISSUE TITLE
[Question HW6] Infinite loop in `hazard.rs`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#778]
Continuation from #773

I changed `acquire_slot` using Box.
```rust
load head
loop {
    if head is null {
        let newpointer = Box::leak(Box::new(HazardSlot::new()));
        if CAS on head succeed {
            return HazardSlot
        } else { continue }

        if slot is inactive { return HazardSlot }
        head = (*head).next
}
```

Now I get into infinite loop.. How can I get idea of the reason?

Also, for `Sheild::drop` and `HazardBag::drop`, do I have to use `drop(Box::from_raw(something))`?

**Comment by Lee-Janggun** [comment]
You're starting to put too much code that it's on the gray area, I recommend you write a bit more pseudo-code like.

For the infinite loop, I think debugging by adding println! to your code will help.

**Comment by DaeyongKwon98** [comment]
I check where infinite loop happens with println!, and it's inside of `if slot is inactive { return HazardSlot }`.
But I wonder how it can happen, because there's return inside, so it should return HazardSlot and finish the function.

**Comment by Lee-Janggun** [comment]
That is weird. Are you sure its not the case that the function did return, and the loop is happening somewhere outside?

**Comment by DaeyongKwon98** [comment]
>Are you sure its not the case that the function did return, and the loop is happening somewhere outside?

You mean, outside of `acquire_slot` function?
`acquire_slot` function is same as above, so there are no other loops in `acquire_slot`.

There are also loops in `try_acquire_inactive` and `all_hazards`, but they don't use `acquire_slot`. And they have similar structure with `acquire_slot`.
Also `HazardBag::drop` has a loop, but it also doesn't use `acquire_slot`.

Now I find that infinite loop is like
`Shield::new` -> `acquire_slot` -> `if slot is inactive { return HazardSlot }` -> `protect` -> `Shield::new` -> ... 

In `try_protect` function, they always return `Ok(())` value, so `protect` function return `pointer`.

But still I can't find the reason of infinite loop. I think `Shield::new` -> `acquire_slot` is normal, so I have to know relation between `if slot is inactive { return HazardSlot }` -> `protect` -> `Shield::new`.

**Comment by Lee-Janggun** [comment]
The loop is that you are calling `protect` in `try_protect`. `protect` is a wrapper function for `try_protect`, so that shoudln't happen.

**Comment by DaeyongKwon98** [comment]
I'm working on `acquire_slot` function.

`try_acquire_inactive` function is `todo!()`.

`all_hazards` function is 
```
load head
loop {
    if head is null -> return hashset
    if find active slot -> add slot in hashset
    head = (*head).next
}
```

**Comment by Lee-Janggun** [comment]
Returning to your last comment:
> But still I can't find the reason of infinite loop. I think Shield::new -> acquire_slot is normal, so I have to know relation between if slot is inactive { return HazardSlot } -> protect -> Shield::new.

Why are you calling `Shield::new()` in `protect()`, assuming -> means function call.

**Comment by DaeyongKwon98** [comment]
>Why are you calling Shield::new() in protect(), assuming -> means function call.

-> 's meaning is sequence of println!.
`protect()` doesn't call `Shield::new()`, and `all_hazards_protected` test have
```rust
let src = AtomicPtr::new(data as *mut ());
let shield = Shield::new(&hazard_bag);
shield.protect(&src);
```

So after `Shield::new` is called, `shield.protect(&src)` is happen.

`Shield::new` -> `acquire_slot` / `protect` is normal I think, but the problem is between previous `protect` and later `Shield::new`, maybe?

**Comment by Lee-Janggun** [comment]
Ah ok, that makes a lot more sense. Which test case is this happening on?

**Comment by DaeyongKwon98** [comment]
Now I test with `all_hazards_protected`.

When I test with `all_hazard_unprotected`, `Shield::drop` is added in infinite cycle.
From `Shield::new` -> `acquire_slot` / `protect`
To `Shield::new` -> `acquire_slot` / `protect` / `Shield::drop`
