### ISSUE TITLE
[Question HW6] In SeqCst Ordering, is it natural there's error?

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs431#781]
I'm doing HW6 part 2: ordering. 
Before write code, I just run SeqCst ordering code in part1 with 'check-loom' and all of the codes produces error.
Is it OK? or Should I rewrite some part of my code?

**Comment by Lee-Janggun** [comment]
Yes, loom does not support SeqCst accesses. Please ignore it.

**Comment by Meraroo** [comment]
I got it. After I write some `fence`s in my code, I can successfully pass the test case with SeqCst. Thanks for your advice.
