### ISSUE TITLE
[Question] [Homework 5] About Split Ordered List, insert

### ISSUE THREAD

**Issue by lgm9** [kaist-cp/cs431#782]
I got the wrong answer from insert_concurrent, (ok until lookup_concurrent) and figured out I didn't handle the case where cursor.insert() returns Err().
Therefore, if cursor.insert() returns Err(), I tried to get the value from it like

```
match cursor.insert( node , guard) {
 Ok(_) => ...
 Err(v) => {
  v.into_value();
  ....
 }
}
```

but the compiler says move occurs and I can't call the into_value() method. Then, how could I return Err() for this function?
Am I getting something wrong with this?

**Comment by Ariaspect** [comment]
`cursor.insert() -> Result<(), Owned<Node<K, V>>>`
I think you should first use Owned to get the Node then V.
