### ISSUE TITLE
[HW6] all_hazards_protected

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#785]
Hi! I fail all_hazards_protected but not all_hazards_unprotected.
So I want to know what the difference between them. 
The only differences I found are :
// leak the shield so that
                        mem::forget(shield);
And
        let intersection: HashSet<_> = all.intersection(&values).collect();
I'm specially curious about the comment since it's not completed.

**Comment by tomtomjhj** [comment]
* leak the shield so that the slot is not cleared
