### ISSUE TITLE
[Homework 6] program stopped after scope

### ISSUE THREAD

**Issue by leesecre** [kaist-cp/cs431#787]
Hello,

I got stucked in counter test in hazard_pointers.rs

The problem is the test program is just stop (At first, I thought it was infinite loop).
(The test program do nothing : no error message, no progress)

I used print function to find where the program goes down.

And I found that the program stopped in scope after for loop in fn counter.

Weird thing is that when I put print code on drop for Shield, it passed the test.

The last thing that program do was calling drop for RetiredSet and do collect. (It ends well).

asan, tsan does not give me information about why the program goes down.
Can you give me some hints to solve the problem?
(single thread does not make a problem)

The code in hazard_pointers.rs
` 
```
    scope(|s| {
        for _ in 0..THREADS {
            s.spawn(|| {
                for _ in 0..ITER {
                    ...
                }
            });
        }
       // <----- here stop the program after call Drop for RetiredSet
    });
```

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs431/blob/518270ed6e35132361a6dbc45c79a6801faf74ea/homework/src/hazard_pointer/retire.rs#L79
Maybe your solution is looping here. If that's the case, try fixing `Shield::drop`.

**Comment by leesecre** [comment]
Thank you for you answering.

I checked, that collect function returned and while loop is ended.

I put print after while loop and It printed the lines. Does it mean that loop ended well?

**Comment by Lee-Janggun** [comment]
Yes, that means the loop ended. That is very weird then...

**Comment by leesecre** [comment]
Oh, I think it is same problem, my program was stucked in protect too.

Thanks for your help
