### ISSUE TITLE
[HW6] counter_sleep() problem

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#790]
I was having some problems with counter_sleep() test, so after reading issue https://github.com/kaist-cp/cs431/issues/581 I think that I have an ABA problem.
So I tried to change some of the implementations so I can effectively protect the pointers from being reclaimed.
But I'm not so sure of my idea: 
When we call set() function for shield, should we check if the hazard slot is active or no before\after storing the pointer in it??

**Comment by mouna77** [comment]
Well, I think yes we should check the active field.

**Comment by tomtomjhj** [comment]
The `active` field of slot associated with a shield must be true.
