### ISSUE TITLE
[HW6] elim_stack fail: not implemented

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#791]
I don't understand the error I got when running asan\tsan for hw6.

failures:

---- elim_stack::test::push stdout ----
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:39:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:39:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread 'elim_stack::test::push' panicked at 'a scoped thread panicked', src/elim_stack/mod.rs:21:9

failures:
    elim_stack::test::push

Does this mean I didn't implement something?

**Comment by Lee-Janggun** [comment]
What is the command you are running? You probably need to add the type for the test you are running if you are doing something like
```
cargo test --test push
```

**Comment by mouna77** [comment]
i ran cargo_tsan test --release

**Comment by mouna77** [comment]
i just ran cargotsan test --release push and I got the following:

running 2 tests
test elim_stack::test::push ... FAILED
test elim_stack::treiber_stack::test::push ... ok

failures:

---- elim_stack::test::push stdout ----
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:39:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:39:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:39:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:27:9
thread '<unnamed>' panicked at 'not implemented', src/elim_stack/elim.rs:39:9
thread 'elim_stack::test::push' panicked at 'a scoped thread panicked', src/elim_stack/mod.rs:21:9


failures:
    elim_stack::test::push

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.78s

error: test failed, to rerun pass `--lib`

**Comment by Lee-Janggun** [comment]
try `cargo_tsan test --release --test growable_array`.
