### ISSUE TITLE
[Question HW6] HazardBag is a stack?

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#793]
While implementing `acquire_slot`, I have confusion about ways to handle head.

In `acquire_slot`, when I have to allocate a new slot, I always have to make like this?
(Make new allocated slot become new head of hazardbag?)

| head | -> | slot1 | -> | slot2 | -> ... -> (null pointer)
into
| newslot | -> | head | -> | slot1 | -> | slot2 | -> ... -> (null pointer)
(new head)

**Comment by Lee-Janggun** [comment]
That's correct.
