### ISSUE TITLE
[Homework 1] Parallel Web Server with Cache (due: 2023-09-24 23:59:59)

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/cs431#803]
Implement a parallel web server with cache.

- Read [this manual](https://github.com/kaist-cp/cs431/tree/main/homework) for general advice on homework. The manual contains skeleton code that serves as a starting point. You're going to fill out the `todo!()`s.
    + **IMPORTANT**: **DO NOT** fork this repository on github.  It'll be public!
- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/hello_server.md).

- You can grade your solution yourself by running `./script/grade-1.sh` in the `homework` directory. If the server's evaluation results differ from your own evaluation results, please let us know.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/102/). You can create the zip to submit as follows:

  ```sh
  cd cs431/homework
  ./scripts/submit.sh
  ls ./target/hw-hello_server.zip     # file to submit
  ```

- **IMPORTANT**: Only the last submission counts.  Please make sure the last line of the "log" says "Score: ?? / ??".

**Comment by 33577** [comment]
Thanks for the detailed instruction. :) 
I think `./script/grade-1.sh` should be changed to `./scripts/grade-hello_server.sh`. 

> You can grade your solution yourself by running `./script/grade-1.sh` in the homework directory

The file path : https://github.com/kaist-cp/cs431/blob/main/homework/scripts/grade-hello_server.sh
