### ISSUE TITLE
[Question] I am not registered in gg.kaist.ac.kr courses

### ISSUE THREAD

**Issue by ho94949** [kaist-cp/cs431#806]
I can join [https://gg.kaist.ac.kr](https://gg.kaist.ac.kr). However, the course is not showing.

I also tried to join [https://gg.kaist.ac.kr/course/16](https://gg.kaist.ac.kr/course/16), which gave me 403 Forbidden error.

**Comment by gmlwns2000** [comment]
Me too! For my identification, my email is ainl@kaist.ac.kr.

**Comment by marchmelo0923** [comment]
I also not registered in gg. my student number is 20200477, and my email is marchmelo@kaist.ac.kr
Could you solve this problem?

**Comment by losif63** [comment]
I am also not registered in gg as well... My student ID is 20200310 and my email is jaduksuh@kasit.ac.kr

**Comment by RobertoCornacchiari** [comment]
Me neither. My student ID is 20236432 and my email is yugimailrob@kaist.ac.kr

**Comment by jeehoonkang** [comment]
would all of you please try again?

**Comment by matyasrichter** [comment]
Mine works now, thanks!

**Comment by gmlwns2000** [comment]
Thank you, mine works now :)

**Comment by marchmelo0923** [comment]
Thank you for your help. Mine works now too.

**Comment by zadpos** [comment]
Could you add register me to the course, too? My student ID is 20180011, and my email is [whgang99@kaist.ac.kr](mailto:whgang99@kaist.ac.kr)
I am sorry for asking this late.

**Comment by abdirakhman** [comment]
Hello! Is it possible to get registered? my email: abdirakhman@kaist.ac.kr
