### ISSUE TITLE
[Question] Unable to reset the password of my SSO account

### ISSUE THREAD

**Issue by invrtd-h** [kaist-cp/cs431#807]
When I try to reset the password, the SSO login form says that she sent an email to reset my password; however, I cannot find the email in my KAIST mail account.

**Comment by tomtomjhj** [comment]
Please check your spam inbox

**Comment by invrtd-h** [comment]
I already checked my spam inbox, but there was no mail.

**Comment by invrtd-h** [comment]
Found: EVERY mail to my KAIST account is not received. It seems to be a KAIST mail problem.
