### ISSUE TITLE
[Question] gg.kaist.ac.kr registration request

### ISSUE THREAD

**Issue by zadpos** [kaist-cp/cs431#809]
I missed replying to #806. Could you please add me to GG, too? My student id is 20180011, mail address is [whgang99@kaist.ac.kr](mailto:whgang99@kaist.ac.kr)

**Comment by jeehoonkang** [comment]
@zadpos would you please try again?

**Comment by zadpos** [comment]
@jeehoonkang I'm afraid I still cannot access the course page...
![image](https://github.com/kaist-cp/cs431/assets/82881609/b597ebc3-454b-4be9-a0a7-5046698c1a17)
Directly accessing [https://gg.kaist.ac.kr/course/16](https://gg.kaist.ac.kr/course/16), it still gives me 403 forbidden error too...

**Comment by jeehoonkang** [comment]
@zadpos would you please (1) log out of auth.fearless.systems; and (2) log in again with the same email address?

**Comment by zadpos** [comment]
@jeehoonkang It worked! Thank you so much for the support, and at such a late time!
