### ISSUE TITLE
[Question] A minor typo in the today's slide?

### ISSUE THREAD

**Issue by invrtd-h** [kaist-cp/cs431#810]
Please note that my memory is inaccurate. If so, please let me know.

I remember that today's slide suggests this code as dangerous:
```
// ##1
void what(std::unique_ptr<int> p) {
    auto q = std::unique_ptr<int>{p};
}
```
However, it may not be compiled, since C++ STL explicitly deleted the copy constructor and copy-assign constructor of the class std::unique_ptr. (i.e. only moving is allowed for the std::unique_ptr object.)
```
/Users/hyegeun_song/.../solve3.h: In function 'void what(std::unique_ptr<int>)':
/Users/hyegeun_song/.../solve3.h:242:36: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = int; _Dp = std::default_delete<int>]'
  242 |     auto q = std::unique_ptr<int>{p};
      |         
```
Please refer: https://en.cppreference.com/w/cpp/language/function#Deleted_functions

However, the moral of today's lecture still holds, because this code is still compiled yet dangerous:
```
// ##2
void what(std::unique_ptr<int> p) {
    auto q = std::unique_ptr<int>{p.get()};
}
```
Here, `get()` function returns the raw pointer of p. Anyway, I think that code ##1 should be changed to ##2.

**Comment by jeehoonkang** [comment]
@invrtd-h thanks! I reflected this point in the following slide: https://docs.google.com/presentation/d/1LbiQ1Z3FTjp1144GRwEj3EPNj-RspAthlsq3a0PCQHw/edit#slide=id.g1dc8f582261_176_51
