### ISSUE TITLE
[Question] [HW1] gg submission doesn't work - error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed

### ISSUE THREAD

**Issue by greedy-hacker** [kaist-cp/cs431#817]
(YOUR QUESTION HERE)
Hi, I've tested HW1 on my container and submitted `hw-hello_server.rs` to gg.
But In gg, nightly rust is not installed correctly with the msg `error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed`
The full log is below
Thank you!
```
===== SETUP =====

===== CHECK =====
[2023-09-17 15:00:21,230: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.72.0 (5680fa18f 2023-08-23)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
```

**Comment by tomtomjhj** [comment]
hmm that's weird. Can you retry?

**Comment by greedy-hacker** [comment]
I tried four times and failed for all tests...
After first setup, the instance with wrong configuration may be resued all times.
(First test taked around 1minute to print the error msg, but other tests prints the error msg immediately)
![화면 캡처 2023-09-18 011544](https://github.com/kaist-cp/cs431/assets/89894608/478c2b97-e95b-49b0-8f91-d03dabed56a3)

**Comment by greedy-hacker** [comment]
Now, the test works correctly.....
I think The instance may have been reconfigured
