### ISSUE TITLE
About HW1

### ISSUE THREAD

**Issue by systil3** [kaist-cp/cs431#819]
When I try test at terminal the method not found error occurs in the skeleton code like this. what is the problem?

![fef43](https://github.com/kaist-cp/cs431/assets/87977576/28794a16-dd2b-42ad-8386-eb9aa6ce3d38)

**Comment by tomtomjhj** [comment]
Have you changed the type signature of `CancellableTcpListener::cancel`?

**Comment by systil3** [comment]
> Have you changed the type signature of `CancellableTcpListener::cancel`?

ㄴ the error solved when try to return Ok(()) in cancel function, thanks but another one occurs in the helloserver.rs skeleton:

![rgh](https://github.com/kaist-cp/cs431/assets/87977576/a3640db1-663f-421d-9900-bf0058bfe0de)

**Comment by tomtomjhj** [comment]
Don't change the type signature of the existing functions
