### ISSUE TITLE
[Question] Is it allowed to override warnings?

### ISSUE THREAD

**Issue by babam6a** [kaist-cp/cs431#820]
While implementing HW1, rust shows this kind of error.
```
error: very complex type used. Consider factoring parts into `type` definitions
  --> src/hello_server/cache.rs:14:12
   |
14 |     inner: (Something I implemented),
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity
   = note: `-D clippy::type-complexity` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::type_complexity)]`

```
Because I think it is very complex to define custom type in structure, 
I used **#[allow(clippy::type_complexity)]** as rust guide said and passed all tests(both local and gg server).
Is It allowed to use this kinds of macro to ignore warning?

**Comment by Wonigox** [comment]
I agree, I included a
`type mytype<T> = complextype<T>`
before the struct definition in order to simplify the type inside the Cache struct. 
However, I'm not sure if we are allowed to add additional code such as this outside of the todo parts.

**Comment by babam6a** [comment]
Thanks for the suggestion!! I changed the code using `type alias`.
However, as @Wonigox said, I'm also wondering that it is okay to add code outside of todo part...

**Comment by tomtomjhj** [comment]
>  Is It allowed to use this kinds of macro to ignore warning?

You may add macros to ignore warnings, but we don't encourage it. 

>  I'm not sure if we are allowed to add additional code such as this outside of the todo parts.

You may add code outside todo part.

btw there's a simpler solution that doesn't trigger this warning.
