### ISSUE TITLE
[Question] Dereferencing a smart pointer with * 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs431#823]
```
        let k = Box::new(String::from("1234"));
        let s = *k;   // Fine 

        let k = Arc::new(String::from("1234"));
        let s = *k;   // cannot move out of an `Arc`

        let k = Mutex::new(String::from("1234"));
        let s = *k.lock().unwrap(); // same error 
```

Hello, 
I'm wondering why these smart pointer which are implementing Deref trait shows different behavior in dereferencing. 

Of course I agree that the Arc and MutexGuard should not be able to be directly dereferenced, because they are something 'shared' and thus the inner data's ownership should not be taken out in that way while Box is owned within the scope it lives in so it's totally fine. 

But I'm curious about how it is statically rejected by compiler. I mean, could you explain it with the ownership rules and their implementation?

**Comment by tomtomjhj** [comment]
Box is treated specially in Rust. https://doc.rust-lang.org/reference/special-types-and-traits.html#boxt
> The dereference operator for `Box<T>` produces a place which can be moved from. This means that the `*` operator and the destructor of `Box<T>` are built-in to the language.


```rust
fn main() {
    let k = Box::new(String::from("1234"));
    let s = *k;
    println!("{}", k);
}
```
```
error[E0382]: borrow of moved value: `k`
 --> src/main.rs:4:20
  |
3 |     let s = *k;
  |             -- value moved here
4 |     println!("{}", k);
  |                    ^ value borrowed here after move
```
