### ISSUE TITLE
[Question] 2022 Fall midterm question

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs431#830]
> In Rust, if a thread has a `&` reference to a value, the value will not be mutated by other threads in any case.
> True
> False

> In Rust, if a thread has a `&mut` reference to a value, the value will not be mutated by other threads in any case.
> True
> False

Hello, I just wanted to clarify those questions.

Does the statement "value be mutated" includes the case that the 'value' itself is a kind of smart pointer and the inner value that it points to is being mutated? 
e.g. where `Box<T>`(or any other kind of smart pointers) exists and `T` is being mutated by another thread when a thread has `&Box<T>` reference to it. 

Thank you.

**Comment by tomtomjhj** [comment]
Yes, this question is about interior mutability.

**Comment by doxylee** [comment]
Is the answer to the questions false and true?
