### ISSUE TITLE
[Question] Why my `Send` declaration doesn't work?

### ISSUE THREAD

**Issue by 33577** [kaist-cp/cs431#833]
I'm trying to find counterexample of these statement: 
> In Rust, if a thread has a &mut reference to a value, the value will not be mutated by other threads in any case.

I tried to make raw pointer and send it to other thread, but rust compiler complains while I implement Send trait for pointer wrapper. 
I thought that I can bypass this compile error by declaring Send trait like below example but it wasn't. 
https://stackoverflow.com/questions/69292169/how-to-send-a-pointer-to-another-thread

I wonder 
- why and 
- is there any possible way to make a counterexample of the statement. 

I'd appreciate for any helps. 
Thank you. 

``` Rust 

    use std::thread;

    struct RawPointWrapper(*mut i32);

    unsafe impl Send for RawPointWrapper {}

    #[test]
    fn test() {
        let mut value = 666;
        let mut p = &mut value;
        let p1 = p as *mut i32;
        let p2 = p as *mut i32;

        let wrapper1 = RawPointWrapper(p1);
        let wrapper2 = RawPointWrapper(p2);

        let handle1 = thread::spawn(move || {
            unsafe { *wrapper1.0 += 1 }
        });

        let handle2 = thread::spawn(move || {
            unsafe { *wrapper2.0 += 1 }
        });

        print!("{}", unsafe {*p});
        print!("{}", value);
    }
```

<img width="1024" alt="image" src="https://github.com/kaist-cp/cs431/assets/34697855/e5f3a6b5-180b-4de0-8a6c-f75b22cb77f3">

**Comment by inhibitor1217** [comment]
I believe your code does not work because `wrapper1.0` and `wrapper2.0` are captured to the closure (which are `*mut i32`s), not the `RawPointWrapper` itself.

I modified the code a bit and the compiler accepts the program.

```rust
use std::ops::{Deref, DerefMut};
use std::thread;

struct RawPointWrapper(*mut i32);

impl Deref for RawPointWrapper {
    type Target = i32;
    fn deref(&self) -> &Self::Target {
        unsafe {
            return &*self.0;
        }
    }
}

impl DerefMut for RawPointWrapper {
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe {
            return &mut *self.0;
        }
    }
}

unsafe impl Send for RawPointWrapper {}

fn main() {
    let mut value = 666;
    let mut p = &mut value;
    let p1 = p as *mut i32;
    let p2 = p as *mut i32;

    let mut wrapper1 = RawPointWrapper(p1);
    let mut wrapper2 = RawPointWrapper(p2);

    let handle1 = thread::spawn(move || {
        *wrapper1 += 1;
    });

    let handle2 = thread::spawn(move || {
        *wrapper2 += 1;
    });

    print!("{}", unsafe {*p});
    print!("{}", value);
}
```

If the `Send` implementation is commented, then

```
error[E0277]: `*mut i32` cannot be sent between threads safely
  --> src/main.rs:34:33
   |
34 |       let handle1 = thread::spawn(move || {
   |                     ------------- ^------
   |                     |             |
   |  ___________________|_____________within this `[closure@src/main.rs:34:33: 34:40]`
   | |                   |
   | |                   required by a bound introduced by this call
35 | |         *wrapper1 += 1;
36 | |     });
   | |_____^ `*mut i32` cannot be sent between threads safely
   |
   = help: within `[closure@src/main.rs:34:33: 34:40]`, the trait `Send` is not implemented for `*mut i32`
note: required because it appears within the type `RawPointWrapper`
  --> src/main.rs:4:8
```

the compiler rejects program, as you intended.

**Comment by tomtomjhj** [comment]
Actually, the intention of the quoted question was that **safe** Rust guarantees that the referenced object will not be mutated by other threads, and code written in unsafe Rust must abide by that rule. In this year's exam, we are trying to make such statements more clear.   


Anyway, your example doesn't work, beecause the closure captured `wrapper1.0` itself, not `wrapper1` (try hovering on the closure). You can force it to capture `wrapper1` like this
```rust
    let handle1 = thread::spawn(move || unsafe {
        let a = wrapper1;
        *a.0 += 1
    });

    let handle2 = thread::spawn(move || unsafe {
        let b = wrapper2;
        *b.0 += 1
    });
```
But note that this is an incorrect program that has data race. Try running with `cargo miri` or thread sanitizer.

**Comment by 33577** [comment]
@tomtomjhj @inhibitor1217 Oh.... wow.. I see! Thanks!! 

> Actually, the intention of the quoted question was that safe Rust guarantees that the referenced object will not be mutated by other threads, and code written in unsafe Rust must abide by that rule. In this year's exam, we are trying to make such statements clearer.

Thanks for your explanation : )
