### ISSUE TITLE
[Question] Responsibility of each location in ticket lock.

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs431#834]
In the video lecture provided as part of our homework assignment, I noticed a statement made around the 9-minute and 37-second mark. The lecturer mentioned that the 'curr' field of the ticket lock is responsible for distinguishing ordering, while 'next' is used for checking waiting.

However, my understanding was that each thread runs 'fetch_add' on the 'next' value, resulting in different orders, which makes 'next' responsible for ordering. On the other hand, I believed that 'curr' is used to check whether the lock has been acquired, making it responsible for waiting. Could you please clarify the content of the lecture for me?

**Comment by 33577** [comment]
You can see the correction in the comments above the Kim jung un or something..
 
<img width="568" alt="image" src="https://github.com/kaist-cp/cs431/assets/34697855/68c4f290-8b82-4bdd-9339-79d68dabfbc1">

**Comment by blziiiin** [comment]
> You can see the correction in the comments above the Kim jung un or something..
> 
> <img alt="image" width="568" src="https://user-images.githubusercontent.com/34697855/275320649-68c4f290-8b82-4bdd-9339-79d68dabfbc1.png">

Oh sorry, I missed to check comment. Sorry for my mistake
