### ISSUE TITLE
[Question] Development server seems to have exploded

### ISSUE THREAD

**Issue by losif63** [kaist-cp/cs431#836]
I can't access the development server since 1 AM today...
Could you please give it a check?

Thank you!

**Comment by Lee-Janggun** [comment]
Hi, the developer servers are having a issue. We will fix it ASAP. We apologize for the inconvenience.

**Comment by Lee-Janggun** [comment]
We have fixed the server. Is your access restored?

**Comment by Lee-Janggun** [comment]
Please re-open if the issue persists :)
