### ISSUE TITLE
[Question] Key role of dummy node in Michael-Scott's Queue

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs431#838]
As professor suggested, I am posting question.

Why is a dummy node required in the implementation of Scott's queue?
1. One possibility is that it prevents head-tail inversion, but is head-tail inversion necessarily a problem? Even without the ability to find the tail from the head during iteration, having a relaxed tail pointer that can point to the actual tail node seems useful. Can you think of scenarios where head-tail inversion might be a problem or why it should be avoided?

2. What issues or challenges can arise in the absence of a dummy node in Scott's queue? Can you provide examples or situations where not using a dummy node could lead to complications or difficulties in the implementation of the queue?

**Comment by tomtomjhj** [comment]
The original paper says:

(on older queue algorithm that uses sentinel node)
> Valois [23, 24] presents a list-based non-blocking algorithm that avoids the contention caused by the snapshots of Prakash et al.'s algorithm and allows more concurrency by keeping a dummy node at the head (dequeue end) of a singly-linked list, thus simplifying the special cases associated with empty and single-item queues (a technique suggested by Sites [17]).

(on MS queue itself)
> [...] we keep a dummy node at the beginning of the list. Because of the dummy node, enqueuers never have to access Head, and dequeuers never have to access Tail, thus avoiding potential deadlock problems that arise from processes trying to acquire the locks in different orders.
