### ISSUE TITLE
[Homework 3] How can we invoke ReadGuard::finish() in Cursor.find()?

### ISSUE THREAD

**Issue by khf7000** [kaist-cp/cs431#839]
In optimistic_fine_grained::Cursor.find(), we must call ReadGuard.finish() for self.prev.
In cursor.find(), we iterate until we points cursor to right place. 
That is, we must do ReadGuard::finish() for each iteration.
I think the usage must be self.prev.finish(), but it is impossible as self is mutable reference, but finish() requires full ownership.

I read crossbeam_epoch::Atomic and github SeqLock part, but it is hard to find the right method. 

Could you give some hint how to use ReadGuard::finish()? Thank you in advance!

**Comment by tomtomjhj** [comment]
hint: std::mem::replace

**Comment by khf7000** [comment]
> hint: std::mem::replace

Thank you very much for your answer even 2:30 AM! Have a good night!
