### ISSUE TITLE
[Homework 3] Reclamation of the node should be deferred.

### ISSUE THREAD

**Issue by khf7000** [kaist-cp/cs431#840]
For OptimisticFineGrainedListSet.remove(), if we successfully find the key and read_lock is valid, we need to drop node.
For example let us list is A -> B -> C and we want to remove node B.
Then I think the removed step is

1.  check the validation of A's read lock. (if not, return false)
2.  Get B's lock.
3.  check the validation of B's read lock. (if not, return false)
4.  upgrade A's read lock to write lock.
5.  write A.next = C
6.  drop the node B

But we need to defer dropping as other threads may read the node B. 
unsafe { drop(Box::from_raw(node as *mut Node<T>)) } gives error in multi-threaded environment. (It passes stress_sequential())
How can we defer dropping? Could you give some hint for deferring? Otherwise, is my step wrong? 
Thank you in advance!

**Comment by tomtomjhj** [comment]
Good observation. This will be (or already have been?) discussed in the lecture. In short, you need to use crossbeam_epoch::Guard::defer_destroy. Btw we have deferred the deadline for this homework.

**Comment by khf7000** [comment]
> Good observation. This will be (or already have been?) discussed in the lecture. In short, you need to use crossbeam_epoch::Guard::defer_destroy. Btw we have deferred the deadline for this homework.

I think we discussed shortly right before lecture. Thank you!
