### ISSUE TITLE
[Question] Question on a midterm problem about the interior mutability

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs431#841]
Dear TAs and professor,

https://github.com/kaist-cp/cs431/issues/830#issue-1931656357
Consulting this previous question, I was trying to verify one of the midterm question.

> TRUE
> If a thread has a `&mut` reference to a value, the value will not be mutated by other threads in any case.
> 

I tried to make a counterexample like this. 

```
use std::sync::{Arc, Mutex};
use std::thread;
fn main() {
    let mut counter = Arc::new(Mutex::new(0));

    let mut handles = vec![];

    for i in 0..10 {
        let counter = Arc::clone(&counter);
        let handle = thread::spawn(move || {
            let mut num = counter.lock().unwrap();
            println!("{} is incrementing counter", i);
            *num += 1;
        });
        handles.push(handle);
    }

    let counter_ref = &mut counter;
    println!("created a mutable reference to the Arc<Mutex>");
    let mut mutexguard = (**counter_ref).lock().unwrap();
    println!("main is modifying counter");
    *mutexguard = 100;
    drop(mutexguard);
    for handle in handles {
        handle.join().unwrap();
    }

    println!("Result: {}", *(**counter_ref).lock().unwrap());
}

```

which shows following output: 

```
1 is incrementing counter
2 is incrementing counter
created a mutable reference to the Arc<Mutex>
4 is incrementing counter
0 is incrementing counter
3 is incrementing counter
6 is incrementing counter
main is modifying counter
5 is incrementing counter
7 is incrementing counter
9 is incrementing counter
8 is incrementing counter
Result: 104
```

Can't this be a counterexample against the statement that it is true? 
Basically, I thought that this question was asking about bypassing the immutability to interiorly mutate a value using Mutex. 

In addition to that, if the question was 

> If a thread has a **`&` reference** to a value, the value will not be mutated by other threads in any case.

what would be the answer?

**Comment by tomtomjhj** [comment]
>     let counter_ref = &mut counter;

You have `&mut` reference to the Arc, not the mutex. Even if you have `&mut Arc<T>`, you might not get `&mut T` (https://doc.rust-lang.org/std/sync/struct.Arc.html#method.get_mut).

The intention of the question was that `&mut` is (must be) exclusive.

One instance of interior mutability is getting `&mut` from `&` when it does not violate this condition (e.g., Mutex, RefCell, ..).

> If a thread has a & reference to a value, the value will not be mutated by other threads in any case.

This would be a problem about interior mutability.
