### ISSUE TITLE
Validity check in HW server doesn't finished

### ISSUE THREAD

**Issue by 33577** [kaist-cp/cs431#844]
Hi :) 
In the gg server, the 'VALID?' status is stuck on 'Checking' for recent submissions. 

Is there an issue with the server? 
Also, should I be concerned if the validity of my submission isn't marked as 'Yes'?

I observed this while working on HW3. 
Thanks!

<img width="624" alt="image" src="https://github.com/kaist-cp/cs431/assets/34697855/2fa6dc7d-008d-4fd0-a4e5-fe9211f315e4">

**Comment by Hwanseok-Yoo** [comment]
I have similar problem too in HW4. The valid column still remain as 'Checking' although it print 'echo "Score: $SCORE / 180"'. 

in my case, all of these submit emit some error like '/usr/bin/addr2line: DWARF error: invalid or unhandled FORM value: 0x23' (it occur error, but it scored as Ok).

**Comment by jmink1896** [comment]
Hello, I've faced the same issue in HW4. Has anyone yet found out the cause?

**Comment by tomtomjhj** [comment]
If you're still having this issue, please send your submission to jaehwang.jung at kaist.ac.kr.

**Comment by 33577** [comment]
> If you're still having this issue, please send your submission to jaehwang.jung at kaist.ac.kr.

Thanks! I'm still experiencing this issue in HW3 and HW4. I'll send my code.

**Comment by jeehoonkang** [comment]
I wonder: how long does it take to check your solutions? Longer than 10 minutes?

**Comment by Hwanseok-Yoo** [comment]
> I wonder: how long does it take to check your solutions? Longer than 10 minutes?

in my case, it still checking after print the score.

**Comment by jeehoonkang** [comment]
@Hwanseok-Yoo how much time? and can you try again? and please send us (me and @tomtomjhj via emails) your submission files.

**Comment by 33577** [comment]
For submission Id 24212, total sum of seconds in below lines is 722.89seconds which is longer than 10 minutes. 
`test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out; finished in 1.64s`

Also I am trying to manually polling the log to determine real execution time, but it stucks in below and doesn't finished while it's over the timeout limit. Also I faced some 502 Bad gateway messages. 
```
running 1 test
test fine_grained::stress_concurrent ...
```

**Comment by Hwanseok-Yoo** [comment]
I re-submit the code, and get the `Timeout` too!!

**Comment by 33577** [comment]
@jeehoonkang @tomtomjhj  For clarification, if `VALID` status is `Timeout`, is submission invalid? 
Not counted even if scores are max? 
Is it an additional limitation while there is timeout limitation for each test case?

**Comment by tomtomjhj** [comment]
We will increase the timeout to 20 minute or reduce the number of repetitions. I'll announce in the issues for each hw once we update it.

**Comment by 33577** [comment]
Thanks! 
Just for additional information, differently as I said first, I got `YES` in HW3 after I enhance my implementation.
And I'm still experiencing Timeout in HW4.

**Comment by junggernaut** [comment]
same problem here. 
I got full point (140/140) but it says Timeout. 

Do I have to resubmit my code after update announcement?

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs431/issues/812#issuecomment-1837775591
https://github.com/kaist-cp/cs431/issues/814#issuecomment-1837775907

**Comment by jmink1896** [comment]
Hello, I have just tried hw4 resubmission and had the following issues:
<img width="625" alt="image" src="https://github.com/kaist-cp/cs431/assets/126305608/cbf55b00-18dc-4063-8016-0c4b8ed771c8">
1. After the server timeout extension, occasional submissions never leave the Checking... state even after the grading is finished.
2. Grading in gg server takes longer than before.
Before the server update, my submissions resulted in full marks.
Now, submitting almost the same version on gg server causes occasional timeouts. Are there any changes gg server's grading criteria? (other than tsan performance + timeout update)

Thank you in advance!

**Comment by jeehoonkang** [comment]
@jmink1896 how much time does it take?

**Comment by jmink1896** [comment]
<img width="528" alt="image" src="https://github.com/kaist-cp/cs431/assets/126305608/9c215a64-56dc-444b-bc1c-72cc35aee004">
On our development server, the grading takes around 15-16 minutes professor.

**Comment by jmink1896** [comment]
I've made minor fixes to the code, and now the submission is valid.
Thank you for your assistance!
