### ISSUE TITLE
[Question] Attempting double-free happening with defer_destroy

### ISSUE THREAD

**Issue by RobertoCornacchiari** [kaist-cp/cs431#845]
Good afternoon,
I'm implementing `list_set/optimistic_fine_grained.rs`. I'm not passing the tests `stress_concurrent` and `log_concurrent` because, looking at the sanitizer, I see that a double free is happening, but I can't figure out why.
In particular I implemented the remove function in the following way (high-level speaking):

- pin the thread;
- place cursor to the node to remove;
- request exclusive access to the prev pointer (pointing to the node to remove) and the next pointer;
- link the next node to the previous (unlinking the node to be removed);
- deref_destroy the node;

Do you see any problem in my approach? Also, in my code I'm not using `unprotected` anywhere, maybe I couldn't completely understand the expected usage of the library. I understood that with `unprotected` we are just created a dummy guard just to use it for the different functions, which will be executed immediately and not deferred as it happens using `pin`, but I don't understand where I would prefer this behavior.
Thanks in advance.

**Comment by tomtomjhj** [comment]
Overall looks correct. 

I think you might be attempting to remove an already removed node. This could happen if you don't use `finish()` and `upgrade()` properly.

**Comment by khf7000** [comment]
I have same issue with @RobertoCornacchiari. I wonder why misuse of `upgrade() ` makes an double-free error. Upgrade() just checks validation and try to get write_lock. If upgrade success, then w.store() and guard.defer_destroy(). Otherwise, just finish for read_lock. Is this logic wrong?

**Comment by tomtomjhj** [comment]
> just finish for read_lock.

this sounds strange. `upgrade()` consumes *the* read lock regardless of the result, so you are not supposed to have a read lock to `finish()`. So I guess you have an extraneous read lock that is somehow misused.

**Comment by khf7000** [comment]
If we want to delete node B btw A / C. My implementation was that get `read_lock() `for A and C first, then try to `upgrade` A. If `upgrade` fails, then `finish` C. But maybe it is OK to get read_lock for C after upgrading, but double-free happens, too..

**Comment by RobertoCornacchiari** [comment]
Sorry for replying only now.
I actually had to re-implement part of my solution, since I noticed I was not performing the operations correctly, but the problem has not changed.
What I modified is that now I'm correctly (in case of a remove for example) reaching the node before the one to delete. So let's say that we want to delete B in A -> B -> C. I use the cursor to get to A and, as described during the lecture, in order to perform the operations safely, I have to acquire the lock of both A and B (which I understood means to have a WriteGuard of those) and then I perform the operations, after which i derefDestroy the node to delete. I'm still getting the same error, `attempting double-free`, but I also don't uderstand one part, that is why the test `read_no_block` should work.
We saw that also for inserting nodes we have to acquire the lock of the previous element. Since the iter points to the element 2 in the test case, when the threads are spawned they are going to insert elements after the 2, acquiring his lock, ivalidating the one of the iter. What am I missing? I don't know if the 2 problems that I'm having are related or not, but maybe I'm missing something on the functioning of the library.

**Comment by tomtomjhj** [comment]
Your description on remove() looks correct. 

> Since the iter points to the element 2 in the test case, when the threads are spawned they are going to insert elements after the 2, acquiring his lock, ivalidating the one of the iter. 

At this point, iter has a read lock on the (`.next` field of) node that contains 1, not 2.

**Comment by RobertoCornacchiari** [comment]
Just to check if I understood correctly, we should check for validity immediately after acquisition and not before usage?

**Comment by tomtomjhj** [comment]
In `next()`, when you're about to return a value, you should make sure that the returned value is not already removed from the list. So `next()` should validate the read lock from the previous invocation of `next()` (or `head()`).

**Comment by RobertoCornacchiari** [comment]
> At this point, iter has a read lock on the (`.next` field of) node that contains 1, not 2.

That is the guard to the node that contains 2, the same guard that we should access to insert 3 for example. Inserting, we have to upgrade the read_lock to write_lock on the `.next` field of 1, that is the lock for the node containing 2 (as far as I understood), as the insert procedure requires so. So if, after the insertion, we check for validation of the readGuard on the `next` before returning the value, this is going to be returned as invalid, since the upgrade was performed. Am I incorrect in any part?

**Comment by tomtomjhj** [comment]
I think you're not distinguishing the field itself and the pointer value read from the field. You have lock on the field, not the value.

**Comment by RobertoCornacchiari** [comment]
I don't think I have completely understood your point.
Each node has a inner value and the pointer to the next node, in the form of a SeqLock. The cursor has one Node as curr and the ReadGuard of the SeqLock of the previous node in the list, that is the node holding the SeqLock of the curr node. If I want to access one node I have to acquire (as read or write) the lock from the previous node (or from the head). If then I want a write access on node B I try to upgrade the ReadGuard obtained by the SeqLock that is the `.next` field of node A. Doing so I will invalidate all the ReadGuard already present around the code, meaning that all the executions must restart (or return error, depending on the implementation).
If I want to access a node I have to pass through the field `.next` of the previous node in all the cases, so I don't understand your comment regarding the difference between the field and the value pointed.

**Comment by tomtomjhj** [comment]
In `A -> B`, the `A.next` seqlock is highly related to `B`, but that doesn't necessarily mean that operating on `B` always require locking `A.next`. The only case that could be problematic is when `B` is removed, but that's prevented by holding `B.next` lock.
