### ISSUE TITLE
[HW5] [Question] Purpose of "hazards" field in the struct RetiredSet

### ISSUE THREAD

**Issue by johnpooh121** [kaist-cp/cs431#850]
Hi,
I'm curious about the purpose of "hazards" field in the struct RetiredSet in retire.rs.

Does it mean that I should declare a thread-local hazardBag different from the global HAZARDS bag (like shown in the fig.4 of https://ieeexplore.ieee.org/document/1291819)?

Then why does the default value of "hazards" field is set to HAZARDS (like https://github.com/kaist-cp/cs431/blob/main/homework/src/hazard_pointer/retire.rs#L70)?

Also, I think the only usage of thread-local hazards bag in the above paper is when the thread retires earlier than the hazard pointer it owns, but this does not happen since the struct Shield automatically owns hazard pointer and drops before the thread ends. So isn't it unnecessary?

Please tell me if I misunderstood, thanks.

**Comment by 33577** [comment]
In my understanding, you don't need a thread-local hazard bag. Retired set is thread local. 
You should check address from thread local retired set with global hazard bag.

**Comment by johnpooh121** [comment]
Oh, so the purpose of the `hazards` field was to tell the `RetiredSet` which `HazardBag` it should use, which is `HAZARDS` by default but it is allowed to use some other predefined global `HazardBag`. Thanks!
