### ISSUE TITLE
[Homework 4][Question] How to replace a node in SplitOrderedList?

### ISSUE THREAD

**Issue by salierisp** [kaist-cp/cs431#851]
After reading the textbook, my understanding of the implementation `SplitOrderedList::insert(key, value, guard)` is:

1. find a cursor at the position where the new node with `key` (but in bit-reversed order) would be inserted to, using `SplitOrderedList::find()`.
2. if there was no node with `key` (in bit-reversed index), make a new node with the key and value and insert it.
3. otherwise, there already exists a node with `key`. replace it with the new node with `value`, extract value from the old node and return it.

But I don't know how to replace a node in step 3, as `lockfree/list.rs` doesn't provide such a function.

I could first remove the old node and then insert the new node, but then there becomes no value associated with `key` between the removal and insertion operation. I think such an implementation would break the consistency of the list.

Or, I could first insert the new node, but then I cannot remove the old node because the old node and the new node cannot be distinguished by key. I could implement the remove operation if I can access private fields of `Cursor` and `Node`, but the public methods of `lockfree/list.rs` can only find a node by `key`.

Are there any other options to implement replace operation?

**Comment by tomtomjhj** [comment]
> otherwise, there already exists a node with key. replace it with the new node with value, extract value from the old node and return it.

oh the intended behavior is just to fail the insertion and return back the value as in `Err`.

**Comment by salierisp** [comment]
Thanks! I misunderstood the API of trait `NonBlockingMap`.
