### ISSUE TITLE
[Question] Advantage of MaybeUninit compare to Option in lockfree queue

### ISSUE THREAD

**Issue by 33577** [kaist-cp/cs431#853]
Hi :) 
In lock-free queue implementation in this repository, it uses `MaybeUninit`.

``` Rust
#[derive(Debug)]
struct Node<T> {
    /// The slot in which a value of type `T` can be stored.
    ///
    /// The type of `data` is `MaybeUninit<T>` because a `Node<T>` doesn't always contain a `T`.
    /// For example, the sentinel node in a queue never contains a value: its slot is always empty.
    /// Other nodes start their life with a push operation and contain a value until it gets popped
    /// out. After that such empty nodes get added to the collector for destruction.
    data: MaybeUninit<T>,

    next: Atomic<Node<T>>,
}
```
https://github.com/kaist-cp/cs431/blob/main/src/lockfree/queue.rs#L32

If the main purpose of using `MaybeUninit` is differentiate sentinel and ordinal nodes, 
**then is there any advantage compare to using simple `Option`?**

I believe that a simple `Option` could serve the same purpose with less unsafe blocks.
I've tested an implementation using `Option` and it seems function correctly, also under tests with an address sanitizer.
https://github.com/33577/cs431/commit/ddffded2b48eeef4cb408cee1e2b7cd8d9539df5

If there's any aspect I'm overlooking, please let me know.
Thanks!

**Comment by tomtomjhj** [comment]
Option usually uses more space than MaybeUninit because it needs to remember whether it's Some or None. With MaybeUninit, you need to reason about whether it contains data or not.
