### ISSUE TITLE
[Question] Purpose of MASK in rand.rs

### ISSUE THREAD

**Issue by 33577** [kaist-cp/cs431#854]
Hi,
In rand.rs, I wonder the purpose of the particular bit masks.
I understand the reason for `MSB=0`.
Then, why it is `0x4004004004007777usize` rather than `0x7FFFFFFFFFFFFFFFusize`?

``` Rust 
impl RandGen for usize {
    /// pick only 16 bits, MSB=0
    fn rand_gen(rng: &mut ThreadRng) -> Self {
        const MASK: usize = 0x4004004004007777usize;
        rng.gen::<usize>() & MASK
    }
}

impl RandGen for u32 {
    /// pick only 16 bits
    fn rand_gen(rng: &mut ThreadRng) -> Self {
        const MASK: u32 = 0x66666666u32;
        rng.gen::<u32>() & MASK
    }
}
```
https://github.com/kaist-cp/cs431/blob/main/homework/src/test/rand.rs#L23-L37

**Comment by tomtomjhj** [comment]
smaller set of keys -> more contention -> more likely to reveal bug
