### ISSUE TITLE
[Question] memory leak - split_ordered_list

### ISSUE THREAD

**Issue by junggernaut** [kaist-cp/cs431#857]
When I run each individual test, the
(e.g. cargo_asan test --test split_ordered_list --release -- --exact stress_concurrent --nocapture)
memory leak pops up about once every more than 20~30 times. (very weird..) so that it is really hard to debug with the individual test. (it 99.9% passed for all the test when i run it as individual)..
So,  I run a test scripts that takes about 15 minutes, I get a memory leak and don't get a full score. (Sometimes, when I get a perfect score in my local, I mistakenly think that I fixed it properly and submit it to the GG server, but when I submit it to the GG server, the memory leak pops up again and I don't get a full score. I'm in a very time-wasting situation...) 

+ My memory leaks always leaked in 1 or 2 allocation. Also, there is a case when function line is came out at sanitizer summary, but like figure below, sometimes there is no function line.. It makes me harder to debug.
+ Is there any case that split_ordered_list gets memory leaked because of growable array? Im asking it because eventhough i never failed to get 70(full score) for growable array, sometimes function line of sanitizer summary is pointing at the line where i use get method of growable array.

I've been debugging for two days now, and I can't even detect it with individual tests anymore, and as I said before, when I submit it thinking I got a full score, it doesn't work again at gg, so I'm leaving an issue to ask for help.

![image](https://github.com/kaist-cp/cs431/assets/75027598/274d7573-14d1-4bff-b550-82023cd0232a)

**Comment by tomtomjhj** [comment]
Don't screen capture the log. Paste the text.

Put llvm-symbolizer in you $PATH to make the stack trace from sanitizer more readable.

**Comment by tomtomjhj** [comment]
Also try running the tests in our development server
