### ISSUE TITLE
Can we allow to use notepad during exam?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs431#860]
Hi,

I looked up the previous exam questions, and it seems there are many code blank-filling questions. 

However, since the place of code example and answer textbox is quite far away sometimes, writing answers was quite difficult.

I had to scroll up and down A-LOOOT to look up the code, write some code, and repeat this process.

So, I think it is quite convenient if we are allowed to use a notepad program, such as notepad.exe in Windows.

I am not sure this could be done with SEB. 

Therefore, if it is impossible, I think adding a link to a simple notepad program online, just like the link to gg, is good. 

- https://onlinenotepad.org/notepad

- https://notes.orga.cat/yz3h9 (source code: https://github.com/pereorga/minimalist-web-notepad)

Thank you!

**Comment by tomtomjhj** [comment]
Thanks for suggestion. 

I guess you want two split windows for the exam form and notepad?  I'm not sure if that's possible. 

Some alternatives
* Use the gg's question textbox as scratch space, and do alt-tabbing between gg and the exam form.  
* Use the google form's answer textbox as scratch space
* We can bring some good old-fashioned scratch papers.

**Comment by alex9801** [comment]
To add to the complaint, Google form's textbox is not in monospace font, has no indentation support, and has no word wrap indication. IIRC two split windows are already possible in SEB, so adding some online notepad website to the whitelist (and adding a link somewhere in the form) will work and would immensely improve the coding experience.

**Comment by tomtomjhj** [comment]
Added the Ace editor to gg. https://gg.kaist.ac.kr/editor/. It supports some basic code editing functionalities. You will be allowed to access this page during the exam. Note: this page doesn't save any data, so be careful.

split windows: We'll try to make it work, but I can't guarantee.

**Comment by tomtomjhj** [comment]
split windows: it just works at least for me (seb 3.6 on win 11)
