### ISSUE TITLE
[Question] Linearization and tail of Michael Scott Queue

### ISSUE THREAD

**Issue by 33577** [kaist-cp/cs431#863]
Hi,
I'm wondering about "but not on tail" in below slide.
I think enque operation in tail is also critical, but why it doesn't considered as a linearization point? 

<img width="951" alt="image" src="https://github.com/kaist-cp/cs431/assets/34697855/6534209d-736c-4fca-bcc4-0404f38beee3">
[slide](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g1582e4c3e87_0_143)

**Comment by khf7000** [comment]
It seems that tail.next pointer is critical, rather than tail? (I'm not sure..)

**Comment by babam6a** [comment]
https://github.com/kaist-cp/cs431/issues/756#issuecomment-1345483553
Maybe this will answer your question..?

**Comment by 33577** [comment]
> Q4: The tail pointer is basically a shortcut to the last node. MS queue works like a proper queue even if you remove the tail pointer and traverse to the last node when enqueuing.

Even it is a shortcut, isn't the CAS on the last node's next 
one of crucial operations that should considered for linearization?

**Comment by Lee-Janggun** [comment]
> Even it is a shortcut, isn't the CAS on the last node's next one of crucial operations that should considered for linearization?

This CAS is the "node's next pointers" mentioned on the slides.

The CASes done on tail mentions on the slide strictly mean the CASes done in the `tail` field of `struct Queue<T>`.

**Comment by 33577** [comment]
Oh I see! Thanks : )
