### ISSUE TITLE
[Question] About the claim session for final exam

### ISSUE THREAD

**Issue by junggernaut** [kaist-cp/cs431#865]
Since the deadline for posting grades is next Thursday(i check it on portal calendar), I assume the final claim session will be held before then. 

Do you already decide a date for the claim session? If not, I'm opening this issue to ask if it's possible for next Monday at the latest(I will be out of the country from next Tuesday..). 
So, I would like to respectfully request that the final claim session could be held no later than Monday.

BTW, professor and TA, thank you so much for a great semester of teaching. I think it was the course that taught me the most out of all the courses I took at KAIST.  
Sincerely.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs431/issues/848#issuecomment-1849527386
