### ISSUE TITLE
[Question] HW3 sanitizer output

### ISSUE THREAD

**Issue by hyuenmin-choi** [kaist-cp/cs431#866]
Hello I'm currently using cargo_asan to debug some memory issues in my homework.
However, It seems that cargo_asan output is not readable.

For example like below.

I think symbolizer is a issue.
So I read previous issue which dealt with same problem with me.
So I found out that $PATH to symbolizer should be present in my server.
However when I "echo $PATH", 

"/home/ubuntu/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/bin/remote-cli:/home/ubuntu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/coder.af1oRW"

I can't find path to symbolizer.
How can I handle this?

---------------------------------------------------------------------------------------------------------------------------
Thread T8 created by T1 here:
    #0 0x5630a3653d9d  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x1bcd9d) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #1 0x5630a3e8124e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x9ea24e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #2 0x5630a376cd8e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x2d5d8e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #3 0x5630a36bdaca  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x226aca) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #4 0x5630a36cbd17  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x234d17) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #5 0x5630a36c53fe  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x22e3fe) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #6 0x5630a3746d2d  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x2afd2d) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #7 0x5630a37aaf6e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x313f6e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #8 0x5630a37af8da  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x3188da) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #9 0x5630a36c3a7e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x22ca7e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #10 0x5630a36ca8fe  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x2338fe) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #11 0x5630a37b4c8f  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x31dc8f) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #12 0x5630a37f1bbe  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x35abbe) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)

Thread T7 created by T1 here:
    #0 0x5630a3653d9d  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x1bcd9d) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #1 0x5630a3e8124e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x9ea24e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #2 0x5630a376cd8e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x2d5d8e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #3 0x5630a36bdaca  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x226aca) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #4 0x5630a36cbd17  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x234d17) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #5 0x5630a36c53fe  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x22e3fe) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #6 0x5630a3746d2d  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x2afd2d) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #7 0x5630a37aaf6e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x313f6e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #8 0x5630a37af8da  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x3188da) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #9 0x5630a36c3a7e  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x22ca7e) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #10 0x5630a36ca8fe  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x2338fe) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #11 0x5630a37b4c8f  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x31dc8f) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)
    #12 0x5630a37f1bbe  (/home/ubuntu/cs431/homework/target/x86_64-unknown-linux-gnu/debug/deps/list_set-df648de70007fe90+0x35abbe) (BuildId: 8299ab0f5d9be8f33aaab5d78040f51838291d5d)

**Comment by Lee-Janggun** [comment]
Please manually add the path of `llvm-symbolizer` to your `$PATH`.

**Comment by hyuenmin-choi** [comment]
Do you mean "export PATH=$PATH:/usr/local/bin/llvm-symbolizer" command in bash?

**Comment by Lee-Janggun** [comment]
Did you symlink it to `llvm-symbolizer`? (c.f, https://github.com/kaist-cp/cs431/issues/644#issuecomment-1256026952)

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs431/commit/a5520748bbcd9dc11c9229f93790b41eafb2a21e
