### ISSUE TITLE
[Question] How can I reset my Coder server?

### ISSUE THREAD

**Issue by 5262362** [kaist-cp/cs431#868]
While I was debugging my code, something went wrong with cargo and the error message keeps saying

```
ubuntu@cs431:~/cs431/homework$ cargo build
   Compiling nix v0.27.1
error[E0599]: no method named `si_pid` found for reference `&siginfo_t` in the current scope
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.27.1/src/sys/wait.rs:262:30
    |
262 |         let si_pid = siginfo.si_pid();
    |                              ^^^^^^ method not found in `&siginfo_t`

error[E0599]: no method named `si_status` found for reference `&siginfo_t` in the current scope
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.27.1/src/sys/wait.rs:270:33
    |
270 |         let si_status = siginfo.si_status();
    |                                 ^^^^^^^^^ method not found in `&siginfo_t`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `nix` (lib) due to 2 previous errors
```

So I tried to uninstall rust, cargo and reinstalled, but the error was not gone. 

So I backed up the files and tried to delete the server and make a new one with the coder template, but it does not work. It just gives me my old files and same error. I think the coder website somehow gets the cached file of my server and overwrites it whenever I create a new server with the template. How can I get a new environment with everything new? Or can I fix this error?

**Comment by tomtomjhj** [comment]
have you tried `rm -rf ~/.cargo`?

**Comment by 5262362** [comment]
I just tried that but it doesn't work either. It seems like every files in ./scripts and cargo_asan, cargo_tsan works well but only cargo doesn't work properly.

**Comment by tomtomjhj** [comment]
Try `cargo clean`, `cargo update` in your homework directory

**Comment by 5262362** [comment]
That worked, thanks for your help!
