### ISSUE TITLE
[Question] (Homework 4) Timeout seems too tight.

### ISSUE THREAD

**Issue by ho94949** [kaist-cp/cs431#870]
Regarding timeout on homework #4, the documentation reads, "The test timeout is at least 5x of the time our implementation took on the homework server. It is not a tight timeout, but it will detect clearly incorrect implementations."

I think my implementation is a bit verbose, but correct since my local gives 10-11s out of 15s timeout.
The model implementation would consider weak memory semantic, and it is not covered, so I had to use `Ordering::SeqCst` everywhere to ensure my code was working. I think this change can bring time change quite close to 2-3x, which could make some slow but correct implementations judged to be wrong.

If I should work more on it by finding room for optimization (in terms of time complexity or trials), then I had to, but can you consider increasing the timeout?

**Comment by tomtomjhj** [comment]
`SeqCst` seems to add only about 20% slowdown on our implementation. The slow solutions I've seen so far did have some significant problems.

I just noticed that for split_ordered_list stress_concurrent with cargo_asan --release (current timeout 15s), our impl takes max 5s on gg. So I'll increase the timeout to 25s in this afternoon. But until then please try to figure out the issue. Try reducing the verbosity of your implementation and take a look at discussions in the issue board.

**Comment by ho94949** [comment]
It's really a shame, but I have found that I forgot to delete `dbg!` statement, which turns out to cost a lot... After that, it runs in 2-5 seconds, which seems great. I would be glad this might help someone...

Thanks for your advice, and I will leave this issue open. Please close the issue after increasing the time limit.

**Comment by ho94949** [comment]
I found a relevant issue #334. Also, in my case, `cargo_tsan` took a shorter time than `cargo`, It seems that `cargo_tsan` ignores the `dbg!` statement somehow.

**Comment by Lee-Janggun** [comment]
Huh... that is extremely weird since we always run the hash table homework in release mode, which optimizes debug statements away. I think this may be a case where regular mode without asan or tsan fails to optimize the debug statement, which is very very weird.

**Comment by Lee-Janggun** [comment]
Oh wait, dbg! should not be optimized... its printing to stderr. My guess is that since tsan/asan does not interact well with such calls and ignores them?

**Comment by tomtomjhj** [comment]
> I found a relevant issue https://github.com/kaist-cp/cs431/issues/334. Also, in my case, cargo_tsan took a shorter time than cargo, It seems that cargo_tsan ignores the dbg! statement somehow.

I adjusted the tests to run less iterations with less threads under tsan because tsan perf was very unstable.
