### ISSUE TITLE
[Homework 1] Parallel Web Server with Cache (due: 2024-03-31 23:59:59)

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#872]
Implement a parallel web server with cache.

- Read [this manual](https://github.com/kaist-cp/cs431/blob/main/homework/README.md) for general advice on homework. The manual contains skeleton code that serves as a starting point. You're going to fill out the `todo!()`s.

- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/hello_server.md).

- Use [skeleton code](https://github.com/kaist-cp/cs431/tree/main/homework/src/hello_server) as a starting point, and fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- Submit your code [here](https://gg.kaist.ac.kr/assignment/121/).

- **IMPORTANT**: Only the last submission counts. Please make sure the last line of the "log" says "Score: ?? / ??".

**Comment by Lee-Janggun** [comment]
See https://github.com/kaist-cp/cs431/issues/890
