### ISSUE TITLE
[Homework 2] Linked List (due: 2024-04-07 23:59:59)

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#873]
Implement a linked list using unsafe Rust.

- Read [this manual](https://github.com/kaist-cp/cs431/blob/main/homework/README.md) for general advice on homework.

- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/linked_list.md).

- Use [skeleton code](https://github.com/kaist-cp/cs431/tree/main/homework/src/linked_list.rs) as a starting point, and fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- Submit your code [here](https://gg.kaist.ac.kr/assignment/122/).

- **IMPORTANT**: Only the last submission counts. Please make sure the last line of the "log" says "Score: ?? / ??".

**Comment by ahn9807** [comment]
I noticed a peculiar error in the log status on gg.kaist.ac.kr.

I believe that this error message may not be related to my mistakes in the submission files.

Would you mind checking into this problem?

```
 nightly-2024-03-13-x86_64-unknown-linux-gnu unchanged - rustc 1.78.0-nightly (a165f1f65 2024-03-12)

info: checking for self-update
info: component 'rust-src' is up to date
error: couldn't read /app/files/checks/cfd36329-ae82-4740-8534-fca7c610b9cf/cs431/homework/src/linked_list.rs: stream did not contain valid UTF-8
  --> /app/files/checks/cfd36329-ae82-4740-8534-fca7c610b9cf/cs431/homework/src/lib.rs:16:1
   |
16 | mod linked_list;
   | ^^^^^^^^^^^^^^^^

Error writing files: failed to resolve mod `linked_list`: cannot parse /app/files/checks/cfd36329-ae82-4740-8534-fca7c610b9cf/cs431/homework/src/linked_list.rs
    Updating crates.io index
    Updating git repository `https://github.com/kaist-cp/cs431`
   Compiling crossbeam-utils v0.8.19
   Compiling libc v0.2.153
    Checking cfg-if v1.0.0
    Checking memchr v2.7.2
   Compiling rayon-core v1.12.1
    Checking regex-syntax v0.8.3
    Checking ppv-lite86 v0.2.17
    Checking either v1.10.0
    Checking aho-corasick v1.1.3
    Checking crossbeam-epoch v0.9.18
    Checking crossbeam-channel v0.5.12
    Checking crossbeam-deque v0.8.5
    Checking cs431 v0.1.0 (https://github.com/kaist-cp/cs431#0bb98050)
    Checking getrandom v0.2.12
    Checking rand_core v0.6.4
    Checking rand_chacha v0.3.1
    Checking rayon v1.10.0
    Checking rand v0.8.5
    Checking regex-automata v0.4.6
    Checking regex v1.10.4
    Checking cs431-homework v0.1.0 (/app/files/checks/cfd36329-ae82-4740-8534-fca7c610b9cf/cs431/homework)
error: couldn't read src/linked_list.rs: stream did not contain valid UTF-8
  --> src/lib.rs:16:1
   |
16 | mod linked_list;
   | ^^^^^^^^^^^^^^^^

error: could not compile `cs431-homework` (lib) due to 1 previous error
Please format your code with `cargo fmt` first.
Please fix the issues from `cargo +nightly clippy -- -D warnings` first.
```

**Comment by Lee-Janggun** [comment]
@ahn9807 Are you sure you didn't accidentally add invalid UTF-8 chars in your source code?

**Comment by ahn9807** [comment]
Certainly, there could be mistakes, but my solution works on my local machine, also when I check the gremlins using an external tool, I cannot find any UTF-8 character set mismatches. If this problem keeps occurring, may I request to check my codes using an external evaluation server? I will certainly accept any penalties for using an external server. Thank you.

**Comment by Lee-Janggun** [comment]
@ahn9807 Can you send your `linked_list.rs` to janggun.lee@cp.kaist.ac.kr?

**Comment by ahn9807** [comment]
> @ahn9807 Can you send your `linked_list.rs` to [janggun.lee@cp.kaist.ac.kr](mailto:janggun.lee@cp.kaist.ac.kr) and [sunho.park@cp.kaist.ac.kr](mailto:sunho.park@cp.kaist.ac.kr)?

I send mail to you. Thank you for your service.

**Comment by Lee-Janggun** [comment]
@ahn9807 hmm... I can't find any mistakes either. Do you have the same error when you resubmit?

**Comment by kingdoctor123** [comment]
@ahn9807 I also ran your solution on gg. I did not modify your solution at all, but it seems there is no problem. Can you try again submitting your solution?
```
  nightly-2024-03-13-x86_64-unknown-linux-gnu unchanged - rustc 1.78.0-nightly (a165f1f65 2024-03-12)

info: checking for self-update
info: component 'rust-src' is up to date
    Updating crates.io index
    Updating git repository `https://github.com/kaist-cp/cs431`
   Compiling crossbeam-utils v0.8.19
   Compiling libc v0.2.153
    Checking cfg-if v1.0.0
   Compiling rayon-core v1.12.1
    Checking memchr v2.7.2
    Checking ppv-lite86 v0.2.17
    Checking regex-syntax v0.8.3
    Checking either v1.10.0
    Checking aho-corasick v1.1.3
    Checking crossbeam-epoch v0.9.18
    Checking crossbeam-channel v0.5.12
    Checking crossbeam-deque v0.8.5
    Checking cs431 v0.1.0 (https://github.com/kaist-cp/cs431#0bb98050)
    Checking getrandom v0.2.12
    Checking rand_core v0.6.4
    Checking rand_chacha v0.3.1
    Checking rayon v1.10.0
    Checking rand v0.8.5
    Checking regex-automata v0.4.6
    Checking regex v1.10.4
    Checking cs431-homework v0.1.0 (/app/files/checks/f41388b3-e750-4745-9529-764e1652d582/cs431/homework)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.01s
Running with cargo...
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.03s
   Doc-tests cs431-homework

running 19 tests
test src/linked_list.rs - linked_list::LinkedList<T>::new (line 198) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::is_empty (line 371) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::push_back (line 597) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::pop_back (line 616) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::front (line 464) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::len (line 391) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::clear (line 416) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::back (line 508) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::push_front (line 553) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::pop_front (line 575) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::back_mut (line 527) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::front_mut (line 483) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::iter (line 307) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::iter_mut (line 336) ... ok
test src/linked_list.rs - linked_list::IterMut<'_,T>::peek_next (line 750) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::contains (line 440) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::append (line 222) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::prepend (line 267) ... ok
test src/linked_list.rs - linked_list::IterMut<'_,T>::insert_next (line 706) ... ok

test result: ok. 19 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out; finished in 0.48s

(omitted)
```

**Comment by ahn9807** [comment]
I made another attempt, but unfortunately, I was unable to successfully execute it.

**Comment by Lee-Janggun** [comment]
@ahn9807 are you getting the same error?

**Comment by ahn9807** [comment]
Yes, I believe that the same error keeps happening.

**Comment by kingdoctor123** [comment]
@ahn9807 To help you with the problem, can you do the following and tell us the result?
- Try to submit your solution to gg using another browser 
  + This checks whether it is the problem of your browser or not
- Try to submit another homework (later ones) and check whether you have the same error or not
  + This checks whether it is a problem of only hw2 or entire gg
- If all of them fail, then can you send us information of your environment? (OS, browser, ...)

**Comment by ahn9807** [comment]
I resubmitted the HW using Chrome (previously Firefox) and failed to execute it.
When I submitted the hw 3 (arc.rs) and hw 1, there were no such errors.

* MAC OS 14.4.1(23E224)
* VScode
* Browser: Firefox and Chrome

If you have any other requests, please let me know. Thank you for your work.

**Comment by kingdoctor123** [comment]
@ahn9807 It's really strange. Thank you for reporting and we will take a look at it later. Since you are not having trouble with submission of other homework and I already confirmed that your solution receives 40/40 points, we decided to give you a perfect score on hw2 even though you cannot submit hw2. So, you don't need to worry about hw2 anymore, and please focus on later homework.
