### ISSUE TITLE
[Homework 4] Behaviour-Oriented Concurrency (due: 2024-04-21 23:59:59)

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#875]
Implement a runtime for Behaviour-Oriented Concurrency (BoC).

- Read [this manual](https://github.com/kaist-cp/cs431/blob/main/homework/README.md) for general advice on homework.

- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/boc.md).

- Use [skeleton code](https://github.com/kaist-cp/cs431/tree/main/homework/src/boc.rs) as a starting point, and fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- Submit your code [here](https://gg.kaist.ac.kr/assignment/124/).

- **IMPORTANT**: Only the last submission counts. Please make sure the last line of the "log" says "Score: ?? / ??".

**Comment by Lee-Janggun** [comment]
Skeleton for BoC has been updated in https://github.com/kaist-cp/cs431/commit/3bcce0e3f56e1fa6474c6334c620be027d508ce3. This should only touch code that student's don't need to care about.

**Comment by Lee-Janggun** [comment]
The tests and grading scripts have been slightly updated https://github.com/kaist-cp/cs431/commit/f867a1db1646e1c5afe9bc6774a5a81b78e5c889 .

**Comment by kingdoctor123** [comment]
The grading script has been updated to test with `cargo_tsan` https://github.com/kaist-cp/cs431/commit/5fea6821f232c7ed4e98831e9fb146b1b0db1bd8.

IMPORTANT: **All previous submissions (before 2024/03/20 16:54:00 KST) have been nullified.** Please resubmit your solution if you have submitted before.

Note: Grading with `cargo_tsan` may print some messages, but this will not crash your grading. So, you don't need to worry about it. (https://github.com/kaist-cp/cs431/blob/main/homework/doc/boc.md#grading-100-points)
