### ISSUE TITLE
[Homework 5] Lock-Coupling Linked List (due: 2024-06-16 23:59:59)

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#876]
Implement concurrent set data structures with sorted singly linked list using fine-grained lock-coupling.

- Read [this manual](https://github.com/kaist-cp/cs431/blob/main/homework/README.md) for general advice on homework.

- [Documentation & Tips](https://github.com/kaist-cp/cs431/blob/main/homework/doc/list_set.md).

- Use [skeleton code](https://github.com/kaist-cp/cs431/tree/main/homework/src/list_set) as a starting point, and fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- Submit your code [here](https://gg.kaist.ac.kr/assignment/125/).

- **IMPORTANT**: Only the last submission counts. Please make sure the last line of the "log" says "Score: ?? / ??".

**Comment by ShinDongHwans** [comment]
I found optimistic_fine_grained.rs file in the list_set folder.
However, there is no mention of the optimistic file in the Documentation & Tips.
Then, don't we have to implement and submit the optimistic file?

**Comment by Lee-Janggun** [comment]
@ShinDongHwans There is. See https://github.com/kaist-cp/cs431/blob/main/homework/doc/list_set.md#advanced-optional.

**Comment by ShinDongHwans** [comment]
@Lee-Janggun Oh Thank you for answering!
I'm sure I've read the entire document, but I might have missed it. Thank you.
