### ISSUE TITLE
[Question] Unable to login via Authentik

### ISSUE THREAD

**Issue by ICubE-** [kaist-cp/cs431#879]
I cannot access gg and dev server using my email in Authentik.
Is the system not ready yet, or is this only occuring to me?

![image](https://github.com/kaist-cp/cs431/assets/8535190/3e3f57d7-dff5-4bee-8097-7b23c6e9f16a)

**Comment by kingdoctor123** [comment]
Hello, currently gg server is not ready, so you cannot login. After the end of class add/drop period (3/4), we will make it ready and make an announcement.

**Comment by ICubE-** [comment]
Thank you for answer!
