### ISSUE TITLE
Try to login to gg and report troubles until Friday

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#883]
Hello,

Currently, we received many inquiries from students that say "I cannot receive an email for password reset."

So, we decided to deal with such problems at once during the weekend.

We apologize for inconvenience, and I ask everyone to

- Try to reset the password and to login to gg **until the Friday**.

- If you cannot receive an email for password reset, then please send your **student id, name, kaist email address** to sunho.park@kaist.ac.kr until the Friday.

- Late inquiries might be addressed late.

- For any other problems in the server (e.g. 500 error, 503 error), you are welcome to report them at any time. Currently we got some error reports of these types and are addressing them.

**Comment by ahn9807** [comment]
I found my password reset email in the trash can. Is this related to the other student problems?

**Comment by kingdoctor123** [comment]
@ahn9807 Thank you for sharing your experience. I hope that this helps other students.
