### ISSUE TITLE
[Question] (Homework 2) cargo_asan build failed due to "Cargo.lock does not exist" on gg

### ISSUE THREAD

**Issue by tncks0121** [kaist-cp/cs431#884]
Whenever I submit HW2 `linked_list.rs` on gg, the following error shows up.

```
Running with cargo_asan...
Build failed! Error message:
error: "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
--------------------------------------------------------------------------------
Score: 0 / 40
```

I get 40/40 consistently (at least 5 times in a row) in my machine (Ubuntu 22.04, same rustc version with gg). Given that the error message looks related with tooling, I think there is some configuration error.

**Comment by kingdoctor123** [comment]
Thank you for your report. It is now fixed. Can you try again?

**Comment by tncks0121** [comment]
It's working now, thanks.
