### ISSUE TITLE
[Question] Deadline of Homework 4

### ISSUE THREAD

**Issue by Delulu-lu** [kaist-cp/cs431#885]
When will the details of homework 4 be released? Also, according to the schedule in the repo, it says, implementation of BoC will be instructed in week 15. Then why the deadline for BoC is right after midterm?

**Comment by kingdoctor123** [comment]
Hello, sorry for being late. We are now finalizing the homework 4 and plan to release it on this weekend.

For the schedule table, it is outdated. Currently, we are planning to
- cover BoC API and implementation before midterm (if time permits)
- or cover only BoC API during the class before midterm and leave the implementation as a homework

In either way, API and implementation of BoC will be included in the scope of midterm exam. So, this is why we set the deadline for homework 4 (BoC) right after midterm.

**Comment by kingdoctor123** [comment]
@Delulu-lu Homework 4 is now released (https://github.com/kaist-cp/cs431/issues/890). This announcement also contains some explanation about deadline of BoC. I hope this answers to your question.
