### ISSUE TITLE
[Question] Are we allowed to write code outside of todo!()s?

### ISSUE THREAD

**Issue by aquacat1220** [kaist-cp/cs431#888]
I wonder if we are allowed to write code outside of todo!()s, i.e. write new functions, add or remove struct members.

I suppose that changing the public API of the module must break tests and grading scripts, but adding and removing (private) struct members, writing new (private) functions, or declaring new (private) structs shouldn't hurt. Are we allowed to make such changes, as long as we do not change the public API of modules?

**Comment by Lee-Janggun** [comment]
Don't touch the existing struct definitions or implementations. You can add more structs for helper functions if needed.

**Comment by aquacat1220** [comment]
Thanks for the reply!
