### ISSUE TITLE
[Question] Is it sufficient to use only the imported modules?

### ISSUE THREAD

**Issue by 08kmc09** [kaist-cp/cs431#892]
I'm now working on homework 4: boc, and I'm curious that just like the previous homeworks (such as cache), is it sufficient to implement the code without using other library? such as mem::forget.

**Comment by kingdoctor123** [comment]
Yes. Our model solution implements BoC only with the libraries already listed in the skeleton code, and I hope you can do it as well.

**Comment by 08kmc09** [comment]
After I posted my question, I found that it can be implemented with the presenting libraries. Thanks for your help!

By the way, it's really challenging to find the right place to clean up the behavior.
