### ISSUE TITLE
[Question] Date and time of midterm exam

### ISSUE THREAD

**Issue by BraSDon** [kaist-cp/cs431#895]
Do you know the time and date of the midterm yet? If yes, could you please update the README

**Comment by Lee-Janggun** [comment]
Thanks for the reminder. Updated in https://github.com/kaist-cp/cs431/commit/3f62a557c60924d5a3e3de0284e79dc56aca3b81 .

A more detailed announcement about the logistics of the exam will be made near the midterm. You can check the announcements from previous semesters if you are interested on what it will look like, as it will be essentially the same.
