### ISSUE TITLE
[Question] Possible Implementation Typo in lock/api.rs

### ISSUE THREAD

**Issue by 08kmc09** [kaist-cp/cs431#898]
Dear TA.

I'm now reviewing the course materials.

However, I learned that LockGuard is a transparent accessor. In order for LockGuard<L,T> to be a Send, it looks like T needs to be replaced with Send.
 
https://github.com/kaist-cp/cs431/blob/3f62a557c60924d5a3e3de0284e79dc56aca3b81/src/lock/api.rs#L90C1-L90C65

Could you address this issue?

I apologize if this has already been covered.

Thank you for your help.

**Comment by Lee-Janggun** [comment]
Yeah that's a typo. Fixed in https://github.com/kaist-cp/cs431/commit/becbb39f1273cded64bda6fde745d7a50e24d1de. I was pretty sure I fixed it, but apparently not...
