### ISSUE TITLE
[Question] Homework 4 grader stuck on "Checking..."

### ISSUE THREAD

**Issue by Non-J** [kaist-cp/cs431#899]
I've tried to submit my homework 4 to the grader, but the status seems to be stuck on "Checking..." despite the log already showing the score. Actually, I tried submitting for the second time, both submissions are still stuck on "Checking...". See the screenshot below taken around 40 minutes after the second submission.

![image](https://github.com/kaist-cp/cs431/assets/45286033/42a254f9-ea41-460a-a8ed-9a014580c0d3)

I've searched through past issues and it seems to be related to timeout on the grader, but my code finished the tests well under the 500s timeout on the grading script (at least it does on my laptop).

**Comment by kingdoctor123** [comment]
Thank you for reporting. It is now solved, so can you try again?

**Comment by Non-J** [comment]
It works now. Thank you.
