### ISSUE TITLE
[Question] [Homework 2] cargo_asan test fails on apple silicon, but success on gg 

### ISSUE THREAD

**Issue by seo-rii** [kaist-cp/cs431#900]
TD;LR: asan check of rust in M1 seems having a malfunction behaviour.

I have tested my code is correct or not in my local laptop(Macbook Air M1), but it has failed on cargo_asan test. However, in my pov, it seems that there should be no error. So I just tried to submit on gg, and interestingly, it passed the test. It seems that cargo_asan test has a bug for Mac platform (might be the problem of LLVM backend of macos)

Test environment: macos sonoma 14.4.1, rustc 1.79.0-nightly, and followed #338 instruction.

**Comment by Lee-Janggun** [comment]
BTW, you're issue is probably related to https://github.com/rust-lang/rust/issues/121624
