### ISSUE TITLE
[Question] [HW4] How to store self in target's last in `start_enqueue`?

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs431#903]
The functions `swap` and `compare_exchange` on `AtomicPtr` wants a `*mut T`. However, in order to enqueue `self` to `target`, I need `&mut self` not `&self`. How can I swap an `AtomicPtr` with a value that I have only immutable reference to?

The reference MCS Lock implementation uses an owned value to enqueue:
https://github.com/kaist-cp/cs431/blob/0bb980500b35d964f342171fe066c8c026ea4f34/src/lock/mcslock.rs#L43-L44

**Comment by Lee-Janggun** [comment]
The return type of 'Node::new()' is '* mut Node<T>'. If you have a '&self', just do 'self as * const T as * mut T'

**Comment by m-spitfire** [comment]
Yep! Didn't know cast like that is valid. Thanks!
