### ISSUE TITLE
[Question] Running cargo run tcp giving error

### ISSUE THREAD

**Issue by Avyukth** [kaist-cp/cs431#907]
I have completed the TCP part of Homework 1, It is passing all the test cases successfully.
But while running 
`cargo run tcp`  getting below error 
`cargo run hello_server                                                                                    
error: target `hello_server` in package `cs431-homework` requires the features: `build-bin`
Consider enabling them by passing, e.g., `--features="build-bin"``

How to solve it

**Comment by Lee-Janggun** [comment]
What are you trying to achieve? Do you want to run the hello_server binary? Then you should run the recommended command, 'cargo run hello_server --features=build-bin'. If you want to run the tests for tcp, run 'cargo test tcp'
