### ISSUE TITLE
Midterm exam rehearsal session (Apr. 8th) / No class on Apr. 10th

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#909]
I announce you a schedule for the next week's class.

## Apr. 8th: Midterm exam rehearsal session

**We will have a rehearsal session for the midterm exam on Apr. 8th**. The primary objective of this session is to familiarize ourselves with the test environment using the Safe Exam Browser (SEB) tool. Your active participation in the rehearsal is strongly encouraged to help prevent any potential penalties related to the test environment.

In preparation for the class, we kindly request that you **bring your laptop, equipped with the SEB software, in a fully charged state.**

---

We are going to rehearse the following items during the class:
1. Download [cs431_midterm_rehearsal.seb](https://drive.google.com/file/d/10xBW2zZVtmPMmfd77uEYHJin3Sph2_5m/view?usp=sharing) and open it with the SEB tool.
1. Check whether your answer is correctly recorded in the sheet: [[CS431 2024 Spring] Exam rehearsal (Responses)](https://docs.google.com/spreadsheets/d/1d2vMJ59W_pIyBSXuZZ9GDRMwFg1pz8uM70lFRS9j2-U/edit?usp=sharing)

Note: Password needed for exiting the SEB is `cs431`.

## Apr. 10th: No class

Due to the election, we have no class.

**Comment by seo-rii** [comment]
> We are going to explain below stuffs in the class tomorrow:

It's not important, but there seems to be a typing error.

**Comment by Lee-Janggun** [comment]
@seo-rii Good catch! Updated the description.
