### ISSUE TITLE
Midterm exam on April 15th (Mon), 13:00-15:00 in the lecture room

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#910]
### Date and Place

We will conduct the **midterm exam on April 15th (Mon), 13:00-15:00 in the lecture room (Rm. 1101, Bldg. E3-1).**

### Coverage

* Everything you've learned until the midterm
  * lecture materials: from the beginning to BoC (inclusive)
    * including all materials that are covered in video lecture: https://github.com/kaist-cp/cs431/issues/893
  * Homework 1, 2, 3, 4
* All the discussions from the lecture and GitHub issues

### Presence

* You must be **physically present** in the lecture room.

* You may not take a break for restrooms or other reasons.

* You may leave 30 minutes after the beginning.

### Supplies

* You should bring **your own laptop** to take the exam.

* If you don't any, please borrow one from the CS admin office by sending an email to [Mr. Gwonhyu Jin](https://cs.kaist.ac.kr/people/view?idx=594&kind=staff&menu=25) with me cc'ed.

* You should have **a valid Google account** because the problem/answer sheet will be given as a Google Form.

* You will use the **Safe Exam Browser (SEB)** for the exam. Install and test SEB before the exam. We will have a rehearsal on Apr 8th (Mon) lecture.

  * Instructions: https://docs.google.com/presentation/d/1M8N8HTh7St-hfjuegpyOefxEXJdbdvv4Xr4wK7FXEn8/edit?usp=sharing

  * See https://github.com/kaist-cp/cs431/issues/909

* You should bring your **student ID card.** If you don't have any, bring a government-issued ID card.

* You may use pencil and paper, but you may not use calculators, tablets, and text editors.

### Screen Policy

On the laptop screen, you can only look at the following websites:

* <https://gg.kaist.ac.kr/>
  
  * Go to <https://gg.kaist.ac.kr/course/19/> and click the exam event.
  * Here, you can see the "event token" (see below).
  * Here, you can also ask questions.
    If your question is not answered for 10 minutes, please let us know.
    You can ask questions in English and Korean.

* The problem/answer sheet as a Google Form
  
  * It will be announced in gg.
  * To answer the Google Form, you need to (1) log in with a Google account, and (2) fill out your KAIST email address, name, student ID, and the event token.
  * The problems will be in English. You may answer either in English or Korean.
  * Frequently save your answer.
    Google Forms does not automatically save your answers unless you "submit" them.
    You are allowed to resubmit the answers as many times as you want, so it is strongly recommended that you submit your answers frequently.
    It is your responsibility to maintain your answers reliably and we will not make any exceptions due to technical problems such as network disconnections, web browser crashes, web browser hanging, etc.
  * We will have a rehearsal on Apr. 8th. During the rehearsal, please make sure you successfully submitted your solution to the practice sheet **before taking the exam.**

### Remote Participation Policy

* If you really cannot be physically present in the lecture room, send an email to [jeehoon.kang@kaist.ac.kr](mailto:jeehoon.kang@kaist.ac.kr) to **ask for explicit permission for remote participation.**
  Without such explicit permission, you will be regarded as absent from the exam.

<details>
<summary>Details on remote participation policy</summary>

* You should **join two Zoom rooms with two Zoom accounts:** ["Announcement" room](https://kaist.zoom.us/my/jeehoon.kang) and the "CCTV" room (privately emailed).
  If you have only one account, please sign up once again.

* Join the Announcement room with a device (probably a desktop/laptop) in which you'll solve the exam problems.
  Turn off the camera and microphone.

* Join the CCTV room with another device (probably a laptop/mobile) that observes you during the exam.
  **For the entirety of the meeting, you need to (1) turn on the camera and microphone; (2) show your hand, paper, keyboard, and monitor; and (3) turn off the speaker.**
  (For privacy concerns: please be noted that you agreed to do this at the beginning of the semester.)
  I've attached the model scene from the experienced TA below.

* **You should be properly present in both the Announcement and CCTV rooms 10 minutes before the beginning to the end of the exam.**
  If you disappear from the camera after the exam starts, we will assume that you gave up on the exam and your score will be automatically zero.
  Network disconnections and/or power outages will not be excuses. Make sure you find a place where you can get a reliable internet connection and power supply.

* Your Zoom name should be in the form of "200711632 강지훈". Otherwise, you may be disqualified.

* At the beginning of the exam, you will be asked to show your student card.
  Please show it in front of the CCTV camera.

* Frequently read Announcement Zoom room messages. We'll DM you when your CCTV doesn't work properly.

</details>

**Comment by SirCollypso** [comment]
My windows laptop cannot hold charge for more than 20 minutes. Is it possible to provide me with a power socket during the exam?

**Comment by kingdoctor123** [comment]
@SirCollypso We will try our best to provide power strips to all students who need it, but as there are lots of students in this class, it is difficult to assure that all students have the access to them. So, I recommend you to arrive at the classroom on the midterm exam date a little bit early so that we can deal with the problem smoothly.

**Comment by tncks0121** [comment]
If possible, could you allow us to view https://gg.kaist.ac.kr/editor/ for readability of codes given in the problems?

**Comment by kingdoctor123** [comment]
@tncks0121 Since we already attached a link to gg on the google form as you might have found in rehearsal session, you can actually access there. For better accessibility, we will add that link in the google form explicitly.

**Comment by kingdy2002** [comment]
SEB does not run on my computer. We mentioned this during rehearsal and heard that a separate computer would be provided.

**Comment by kingdoctor123** [comment]
@kingdy2002 Since there are several students having trouble with SEB, we will print out a problem sheet and allow you to write your solutions on paper. So, if SEB does not work on your computer, then please make sure you bring your pen/pencil.

**Comment by seo-rii** [comment]
Should I bring physical ID card? Or is mobile ID allowed?

**Comment by kingdoctor123** [comment]
@seo-rii Physical ID card is preferred, but mobile ID is also allowed.

**Comment by kingdoctor123** [comment]
Please download the seb file here: [cs431_midterm.seb](https://drive.google.com/file/d/116xni9YBS3WYJZStAovTVyOLE9u0xcds/view?usp=sharing)

Exam password will be announced when the exam begins.
