### ISSUE TITLE
[Question] Test timed out on cargo_asan --release (HW2)

### ISSUE THREAD

**Issue by 03psb** [kaist-cp/cs431#911]
When I ran the grading script, all the other parts are ok but cargo_asan --release part creates timeout issue.

Running with cargo_asan --release...
   Compiling aho-corasick v1.1.3
   Compiling regex-automata v0.4.6
   Compiling regex v1.10.4
   Compiling cs431-homework v0.1.0 (/home/seongbeen/cs431/homework)
Test timed out: cargo_asan test --release --doc linked_listework                                                                                   
    Finished `release` profile [optimized] target(s) in 0.04s
     Running tests/linked_list.rs (/home/seongbeen/cs431/homework/target/x86_64-unknown-linux-gnu/release/deps/linked_list-94dd7893f5c4a70e)

above is the terminal message for the timeout part. Is this the problem with my environment, or does it mean that I should modify my implementation for performance?

**Comment by kingdoctor123** [comment]
Have you tried running the grading script on the provided development server or gg site? I would suggest you to try this since I've just checked that I don't have any problems on these environments.

Even if same problem occurs, I guess you need to come up with a better solution since we set the timeout to be not too tight if your solution is correct. Below, I attach a part of the log regarding `cargo_asan --release` that I got by submitting on gg for your reference.
```
Running with cargo_asan --release...
   Compiling crossbeam-utils v0.8.19
   Compiling libc v0.2.153
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.2
   Compiling ppv-lite86 v0.2.17
   Compiling regex-syntax v0.8.3
   Compiling either v1.10.0
   Compiling crossbeam-epoch v0.9.18
   Compiling crossbeam-channel v0.5.12
   Compiling aho-corasick v1.1.3
   Compiling getrandom v0.2.12
   Compiling rand_core v0.6.4
   Compiling crossbeam-deque v0.8.5
   Compiling cs431 v0.1.0 (https://github.com/kaist-cp/cs431#0bb98050)
   Compiling rand_chacha v0.3.1
   Compiling rayon-core v1.12.1
   Compiling rand v0.8.5
   Compiling rayon v1.10.0
   Compiling regex-automata v0.4.6
   Compiling regex v1.10.4
   Compiling cs431-homework v0.1.0 (/app/files/checks/e4877fa5-0dfa-4705-b2d0-9570193bdb72/cs431/homework)
    Finished `release` profile [optimized] target(s) in 7.58s
   Doc-tests cs431-homework

running 19 tests
test src/linked_list.rs - linked_list::LinkedList<T>::len (line 405) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::new (line 197) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::back_mut (line 541) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::iter_mut (line 350) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::is_empty (line 385) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::back (line 522) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::append (line 221) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::push_back (line 611) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::pop_back (line 630) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::front_mut (line 497) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::push_front (line 567) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::front (line 478) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::iter (line 321) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::pop_front (line 589) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::contains (line 454) ... ok
test src/linked_list.rs - linked_list::IterMut<'_,T>::insert_next (line 720) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::clear (line 430) ... ok
test src/linked_list.rs - linked_list::IterMut<'_,T>::peek_next (line 760) ... ok
test src/linked_list.rs - linked_list::LinkedList<T>::prepend (line 266) ... ok

test result: ok. 19 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out; finished in 0.76s
```

**Comment by m-spitfire** [comment]
I have to say that if time-out doesn't occur with debug `cargo_asan` and it occurs with `--release`, it sounds a bit weird, since release should be faster (but maybe it's compilation time issue).

**Comment by Lee-Janggun** [comment]
Actually, optimization of incorrect programs can lead to infinite loops; although it is probably unrelated here.

**Comment by 03psb** [comment]
I tried it on the development server, and it was okay. I kind of forgot the existence of development server. Thank you all for your reply.
