### ISSUE TITLE
[Question] Cannot open new browser inside Safe Browser

### ISSUE THREAD

**Issue by noblekoo** [kaist-cp/cs431#914]
Trying to click the link https://gg.kaist.ac.kr/event/40/ and it does not open a pop-up browser but only gives me the choice to quit the safe exam browser just like the picture below.
![KakaoTalk_20240408_135749028](https://github.com/kaist-cp/cs431/assets/67997257/bdceeeff-6f46-4c14-972d-73be58f10bd9)

Current device is
- macOS Monterey 12.0.1
- MacBook Pro M1 Pro

I tried
- Right click
- Reboot
- Reinstall safe browser
- Use old version of safe browser
- Redownload configuration file

**Comment by noblekoo** [comment]
@Lee-Janggun 
> I tried it on a M2 macbook air, and it worked fine. I have a few questions for clarification.
> 
> 1. When you say "only gives me the choice to quit the safe exam browser", are you saying that clicking on the link makes the exit prompt pop up, instead of a new browser opening?
> 2. Are you in window mode? If you are in fullscreen mode, clicking on the top left green button should make it go to window mode, which makes it easier to spot the new browser.

1. Yes, that right.
2. I tried the window mode, and there is no browser coming up. Only the exit prompt above is coming up.

**Comment by Lee-Janggun** [comment]
Does updating the OS help?

**Comment by noblekoo** [comment]
@Lee-Janggun It worked! Thanks
I updated my macOS into 13.6.6.

**Comment by Lee-Janggun** [comment]
Nice! We'll make a reminder to tell students to update their OS in the future.
