### ISSUE TITLE
[Locks] Can we change while loop of MCSParking lock to If statement? 

### ISSUE THREAD

**Issue by Coll1ns-cult** [kaist-cp/cs431#918]
Hi I wonder if we can change the following statement

`while unsafe { (*node).locked.load(Acquire) } {
            thread::park();
 }`

to this: 
` if  unsafe { (*node).locked.load(Acquire) } {
           thread::park();
}
`

Since we can only unpark() this thread with the lock holder thread, while loop is not a necessity I believe. Is this a valid implementation? 

Thanks in Advance!

**Comment by m-spitfire** [comment]
The [`park`](https://doc.rust-lang.org/std/thread/fn.park.html) call may have spurious wake up. So it's necessary to be in a loop.
