### ISSUE TITLE
[Question] `unsafe` on the traits `RawLock` and `RawTryLock`

### ISSUE THREAD

**Issue by ICubE-** [kaist-cp/cs431#921]
In [src/lock/api.rs](https://github.com/kaist-cp/cs431/blob/1393f452f8e6d8874e71ff9bc5588bae08de0632/src/lock/api.rs), we have `RawLock` and `RawTryLock` traits and they are `unsafe`.
Why are they `unsafe trait`s? Removing `unsafe` seems to work fine.
Is it just for indicating api developers that the trait needs more attention when they're implemented?

```rust
pub unsafe trait RawLock: Default + Send + Sync {
    type Token;
    fn lock(&self) -> Self::Token;
    unsafe fn unlock(&self, token: Self::Token);
}
pub unsafe trait RawTryLock: RawLock {
    fn try_lock(&self) -> Result<Self::Token, ()>;
}
```

**Comment by kingdoctor123** [comment]
Yes you're correct. See related explanation here: https://google.github.io/comprehensive-rust/unsafe-rust/unsafe-traits.html#implementing-unsafe-traits.

**Comment by ICubE-** [comment]
Thank you for the answer!
So, `unsafe trait` on `RawLock` means that "Any struct implementing this trait **must** guarantee the additional safety requirements to be hold. The developer have to ensure it." And the safety requirement is:
> /// # Safety
/// Implementations of this trait must ensure that the lock is actually
/// exclusive: a lock can't be acquired while the lock is already locked.
