### ISSUE TITLE
[Question] Why use AtomicBool instead of non-atomic bool in Node of CLH Lock?

### ISSUE THREAD

**Issue by KalasLavas** [kaist-cp/cs431#922]
Why do we use `AtomicBool` in node of CLH Lock?
https://github.com/kaist-cp/cs431/blob/1393f452f8e6d8874e71ff9bc5588bae08de0632/src/lock/clhlock.rs#L7-L9

Isn't it enough to use non-atomic bool since we only read in `lock()` and write `unlock()`?
https://github.com/kaist-cp/cs431/blob/1393f452f8e6d8874e71ff9bc5588bae08de0632/src/lock/clhlock.rs#L47
https://github.com/kaist-cp/cs431/blob/1393f452f8e6d8874e71ff9bc5588bae08de0632/src/lock/clhlock.rs#L58-L60

**Comment by kingdoctor123** [comment]
Non-atomically reading from or writing to a location that can be accessed by multiple threads are *always* data races. This condition is formally defined in the language semantics (precisely, memory model). Such situation is considered as an undefined behavior, and compilers might perform aggressive optimization while assuming that such situation never happens. This is the reason why we should use `AtomicBool` even if we don't use CAS, FAA, etc.

Reference: https://stackoverflow.com/questions/72639534/why-is-atomic-bool-needed-to-avoid-data-race

**Comment by KalasLavas** [comment]
Understood! Thank you!
