### ISSUE TITLE
[Question] (Do we have Structured flow of Homework according to YouTube Playlist?)

### ISSUE THREAD

**Issue by vaibh27** [kaist-cp/cs431#931]
(YOUR QUESTION HERE)
I've been reviewing the course material to kick off this program. I've got a few questions regarding the homework assignments and how they're organized. Could you clarify how they're structured? It would help me plan to tackle them weekly as I move through the course.

[ ] Do we have a checklist of homework assignments according to each week of study?
[ ] Could you provide the problem statements for the homework assignments?

**Comment by kingdoctor123** [comment]
Hello, I'm assuming you are not attending the course that is being offered in this semester.

> Could you clarify how they're structured?

Youtube video lectures are based on the old curriculum of this course 4 years ago. As a result, the content and organization are quite different from current version of [slide](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit?usp=sharing). If youtube videos are the only resources that you can access, then please follow the organization of the videos.

> Could you provide the problem statements for the homework assignments?

I hope that announcements on assignments might help. It gives you enough details on (1) recommended order of assignments and (2) what to do for each assignment.

- Homework 1: https://github.com/kaist-cp/cs431/issues/872
- Homework 2: https://github.com/kaist-cp/cs431/issues/873
- Homework 3: https://github.com/kaist-cp/cs431/issues/874
- Homework 4: https://github.com/kaist-cp/cs431/issues/875
- Homework 5: https://github.com/kaist-cp/cs431/issues/876
- Homework 6: https://github.com/kaist-cp/cs431/issues/877
- Homework 7: https://github.com/kaist-cp/cs431/issues/878

> Do we have a checklist of homework assignments according to each week of study?

In general, we don't have clear matching between videos and assignments, but except for the following:
- Homework 1: https://youtu.be/wQeUKeSYFzM?si=gdg11eWILZOhJXOi
- Homework 3: https://youtu.be/dSvBTHnJPyo?si=rvT5QoXgYB0weHVZ
- Homework 5: https://youtu.be/nOEJk3vHiTs?si=PYIJQ8gh-UaFJ9OO
- Homework 7: https://youtu.be/drXrIVfBKaQ?si=FsdWdjxuTvFbul9g

**Comment by vaibh27** [comment]
Thanks @kingdoctor123
