### ISSUE TITLE
[Question] HW6 How to get Parent of a bucket?

### ISSUE THREAD

**Issue by Coll1ns-cult** [kaist-cp/cs431#939]
Hi, I don't understand the following line in the paper: "This value is achieved by calling the GET PARENT macro that unsets bucket’s most significant turned-on bit". Does that mean, if we have bucket 0x101101, we have the following parent relationship?
0x101101 -> 0x001101 -> 0x000101 -> 0x000001 -> 0x000000 (where x->y means y is parent of x)

Thanks In Advance!

**Comment by Lee-Janggun** [comment]
See https://github.com/kaist-cp/cs431/issues/699#issuecomment-1296294570.

**Comment by Lee-Janggun** [comment]
Oh, the explanation of this part in the book is pretty rough. For the index with size less than 2^i, you should shift size to be less than the index. See fig 13.19. of the art of multiprocessor programming.

> 0x101101 -> 0x001101 -> 0x000101 -> 0x000001 -> 0x000000 (where x->y means y is parent of x)


In other words, this is correct.
