### ISSUE TITLE
[Question] is gg down for anyone else

### ISSUE THREAD

**Issue by thekioskman** [kaist-cp/cs431#942]
Trying to submit solutions to gg , getting err 502. Is it down for anyone else of just me?

**Comment by kingdoctor123** [comment]
Sorry for inconvenience. It is now fixed. Can you try again?

**Comment by thekioskman** [comment]
working thanks!

**Comment by thekioskman** [comment]
It is a bit slow though, its been 10 minutes and it hasn't started the tests yet

**Comment by kingdoctor123** [comment]
> It is a bit slow though, its been 10 minutes and it hasn't started the tests yet

Are you still having the same problem? If so, please tell me exactly which homework assignment (HW1 ~ HW7) causes such problem.
