### ISSUE TITLE
[Question] workspace build error

### ISSUE THREAD

**Issue by leeyh0623** [kaist-cp/cs431#945]
I am unable to access the workspace due to a build error message. Why is this error occurring?
I am encountering an error like the one shown in the picture below.

![이미지 2024  6  1  오전 1 18](https://github.com/kaist-cp/cs431/assets/85305379/8c6d2b3e-6f2f-4d56-976b-c5cff7947b8f)

**Comment by kingdoctor123** [comment]
It seems the main cause of the problem is that KAIST network blocks access to githubusercontent.com. I will contact the KAIST network team next Monday. So until that, please use your local machine to do the homework.

**Comment by leeyh0623** [comment]
I'm encountering a public key error when trying to git clone locally. Do I need separate permissions?

**Comment by kingdoctor123** [comment]
How about `git clone https://github.com/kaist-cp/cs431.git`? This should work, I guess.

**Comment by leeyh0623** [comment]
I understand now. Thank you!

**Comment by kingdoctor123** [comment]
@leeyh0623 Network problem is now resolved and I checked that everything is working well. If you have any further problems, please let me know.
