### ISSUE TITLE
Final exam on June 10th (Mon), 13:00-15:00 in the lecture room

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#946]
### Date and Place

We will conduct the **final exam on June 10th (Mon), 13:00-15:00 in the lecture room (Rm. 1101, Bldg. E3-1).**

### Coverage

* Everything you've learned after the midterm
  * lecture materials: from the lock-free concurrency to the end
    * including all materials that are covered in video lecture: https://github.com/kaist-cp/cs431/issues/929
  * Homework 5, 6, 7
  * Note: Although you may get full points for the homework without considering deeply about memory orderings (e.g. release, acquire), **the scope of the exam includes the promising semantics** (including "promises" for store hoisting).
* All the discussions from the lecture and GitHub issues

### Presence

* You must be **physically present** in the lecture room.

* You may not take a break for restrooms or other reasons.

* You may leave 30 minutes after the beginning.

### Supplies

* You should bring **your own laptop** to take the exam.

* You should have **a valid Google account** because the problem/answer sheet will be given as a Google Form.

* You will use the **Safe Exam Browser (SEB)** for the exam. Install and test SEB before the exam.

  * Instructions: https://docs.google.com/presentation/d/1M8N8HTh7St-hfjuegpyOefxEXJdbdvv4Xr4wK7FXEn8/edit?usp=sharing

  * As we did in the midterm exam, SEB configuration file will be uploaded to the comment area of this issue.

* You should bring your **student ID card.** If you don't have any, bring a government-issued ID card.

* You may use pencil and paper, but you may not use calculators, tablets, and text editors.

### Screen Policy

On the laptop screen, you can only look at the following websites:

* <https://gg.kaist.ac.kr/>
  
  * Go to <https://gg.kaist.ac.kr/event/42/> and click the exam event.
  * Here, you can see the "event token" (see below).
  * Here, you can also ask questions.
    If your question is not answered for 10 minutes, please let us know.
    You can ask questions in English and Korean.

* The problem/answer sheet as a Google Form
  
  * It will be announced in gg.
  * To answer the Google Form, you need to (1) log in with a Google account, and (2) fill out your KAIST email address, name, student ID, and the event token.
  * The problems will be in English. You may answer either in English or Korean.
  * Frequently save your answer.
    Google Forms does not automatically save your answers unless you "submit" them.
    You are allowed to resubmit the answers as many times as you want, so it is strongly recommended that you submit your answers frequently.
    It is your responsibility to maintain your answers reliably and we will not make any exceptions due to technical problems such as network disconnections, web browser crashes, web browser hanging, etc.

### Remote Participation Policy

* If you really cannot be physically present in the lecture room, send an email to [jeehoon.kang@kaist.ac.kr](mailto:jeehoon.kang@kaist.ac.kr) to **ask for explicit permission for remote participation.**
  Without such explicit permission, you will be regarded as absent from the exam.

<details>
<summary>Details on remote participation policy</summary>

* You should **join two Zoom rooms with two Zoom accounts:** ["Announcement" room](https://kaist.zoom.us/my/jeehoon.kang) and the "CCTV" room (privately emailed).
  If you have only one account, please sign up once again.

* Join the Announcement room with a device (probably a desktop/laptop) in which you'll solve the exam problems.
  Turn off the camera and microphone.

* Join the CCTV room with another device (probably a laptop/mobile) that observes you during the exam.
  **For the entirety of the meeting, you need to (1) turn on the camera and microphone; (2) show your hand, paper, keyboard, and monitor; and (3) turn off the speaker.**
  (For privacy concerns: please be noted that you agreed to do this at the beginning of the semester.)
  I've attached the model scene from the experienced TA below.

* **You should be properly present in both the Announcement and CCTV rooms 10 minutes before the beginning to the end of the exam.**
  If you disappear from the camera after the exam starts, we will assume that you gave up on the exam and your score will be automatically zero.
  Network disconnections and/or power outages will not be excuses. Make sure you find a place where you can get a reliable internet connection and power supply.

* Your Zoom name should be in the form of "200711632 강지훈". Otherwise, you may be disqualified.

* At the beginning of the exam, you will be asked to show your student card.
  Please show it in front of the CCTV camera.

* Frequently read Announcement Zoom room messages. We'll DM you when your CCTV doesn't work properly.

</details>

**Comment by 08kmc09** [comment]
> Note: Although you may get full points for the homework without considering deeply about memory orderings (e.g. release, acquire), the scope of the exam includes the promising semantics (including "promises" for store hoisting).

Do you mean that we should consider the memory ordering for the homework 5 ~ 7?

**Comment by kingdoctor123** [comment]
@08kmc09 When writing a code for homework and submitting your solution to gg, you don't need to do so. But when studying for final exam, you should consider memory orderings for homework.

**Comment by 08kmc09** [comment]
@kingdoctor123 Oh I see, I must re-implement homeworks with memory ordering for final exam.. Thank you!

**Comment by BraSDon** [comment]
Is it once again possible to do the exam on paper?

**Comment by kingdoctor123** [comment]
@BraSDon For those who have trouble with SEB, yes. We will prepare some printed version of exam papers for them.

**Comment by kingdoctor123** [comment]
SEB configuration file: https://drive.google.com/file/d/11ycrmKH39g5_VBprtNY3UQMtcHAvdTfD/view?usp=sharing

Password to begin the exam will be announced soon.
