### ISSUE TITLE
Final claim session on June 17th (Mon)

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs431#962]
There will be offline claim session for final exam on June 17th (Mon). Grading will be finished and you will be able to see your grades on gg on this weekend.

* Type: offline claim session
* Time: 16:00 ~ 18:00
* Place: E3-1 4448
* You can review the exam problems from here: https://github.com/kaist-cp/cs431/issues/826

**Comment by leporia** [comment]
I'm sorry to bother but I'll leave Korea before then will it be possible to have an online session?

**Comment by Lee-Janggun** [comment]
@leporia yes, please send an email to all the TAs to adjust a schedule, or we'll have an claim session via email.

**Comment by kingdoctor123** [comment]
Midterm score has been released. You can check your score at gg.

Statistics:

| | Total | T/F | Enumerating possible outcomes | Incorrect spinlock | Analysis on tail pointers of Michael-Scott queue | SC fences in hazard pointers | Array stack | Sticky counter | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| max | 76 | 36 | 5 | 10 | 12 | 15 | 5 | 15 | 
| 3rd quartile | 63 | 31 | 0 | 10 | 8 | 0 | 5 | 10 | 
| median | 54 | 28 | 0 | 2 | 6 | 0 | 5 | 8 |
| 1st quartile | 38 | 24 | 0 | 0 | 4 | 0 | 0 | 5 | 
| Avg | 50.5 | 27.4 | 0.9 | 4.3 | 5.7 | 1.4 | 3.1 | 7.5 | 
| Std dev | 15.4 | 4.3 | 1.9 | 4.4 | 2.9 | 3.6 | 2.3 | 5.2 |

![CS431 final statistics](https://github.com/kaist-cp/cs431/assets/79883007/0b74aedc-05d0-4176-aa22-e45209cd0e89)

**Comment by kingdoctor123** [comment]
Claim session was finished and you can find your final score on the final exam on gg. 

Update in grading policy:
* Everyone gets full score for problem 24.

Updated statistics:
| | Total | T/F | Enumerating possible outcomes | Incorrect spinlock | Analysis on tail pointers of Michael-Scott queue | SC fences in hazard pointers | Array stack | Sticky counter | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| max | 79 | 38 | 5 | 10 | 12 | 15 | 5 | 15 | 
| 3rd quartile | 64 | 33 | 0 | 10 | 8 | 0 | 5 | 10 | 
| median | 55 | 28 | 0 | 2 | 6 | 0 | 5 | 8 |
| 1st quartile | 41 | 26 | 0 | 0 | 4 | 0 | 0 | 5 | 
| Avg | 52.4 | 29.1 | 0.9 | 4.3 | 5.7 | 1.4 | 3.1 | 7.5 | 
| Std dev | 15.8 | 4.6 | 1.9 | 4.4 | 2.9 | 3.6 | 2.3 | 5.2 |

![CS431 final statistics](https://github.com/kaist-cp/cs431/assets/79883007/c2f1620a-2913-47af-b52d-a75e41d790af)
