### ISSUE TITLE
[Question] HW 7 reason for having atomicUsize type in hazard field

### ISSUE THREAD

**Issue by thekioskman** [kaist-cp/cs431#963]
From my understanding, it seems the hazard: atomicUsize field is meant for storing the pointers to the actual data. But why usize used, when we can just use an atomicPointer? Is there any reasons for this. Or maybe I am misunderstanding the role of hazard: AtomicUsize.

**Comment by kingdoctor123** [comment]
`AtomicPtr<T>` is associated with the data type `T`. But we want to use `hazard: atomicUsize` field to store the address of any data with arbitrary type. For this reason, we use atomicUsize.

p.s. please elaborate your question in your title from next time.

**Comment by thekioskman** [comment]
thank you and will do 👍
