### ISSUE TITLE
[Question] [HW7] Failed Basic Tests in hazard.rs

### ISSUE THREAD

**Issue by JJong84** [kaist-cp/cs431#964]
I submitted the codes for HW7. I failed all the basic test cases in hazard.rs, even I passed all the others.

However, when I tested the same test cases in my environment, they were all passed.

I don't know the reason. Can you help me fix this issue?

<img width="780" alt="스크린샷 2024-06-16 오전 6 52 31" src="https://github.com/kaist-cp/cs431/assets/39782865/7d3db898-9ec9-46a0-bd97-1a28e3e5377e">

![스크린샷 2024-06-16 오전 6 53 31](https://github.com/kaist-cp/cs431/assets/39782865/4f1bab15-ef77-4a5f-b4af-8dab7a643b9a)

**Comment by Lee-Janggun** [comment]
Does your code still pass  when the grade script is used?

**Comment by kingdoctor123** [comment]
I just checked that our model solution runs correctly without error. So I guess your code has a minor bug that happens only occasionally.

**Comment by JJong84** [comment]
> Does your code still pass when the grade script is used?

Yes, the test cases from hazard.rs are all passed with `grade-hazard-pointer.sh`
