### ISSUE TITLE
[Question] Partial Points on HW7 

### ISSUE THREAD

**Issue by thekioskman** [kaist-cp/cs431#966]
Is it possible to just submit the hazard.rs code and get partial points for that section? I don't feel like I have enough time to finish the whole assignment I wanted to see if I could get partial points. But I think without the retire implemented there will be memory leaks on the hazard field in the slot which will result in 0 points. I was just wondering if it was possible to get partial points.

**Comment by kingdoctor123** [comment]
The score printed as "Score: ?? / 70" will be your final score. If it says 0, then you cannot get any partial points. Since we're almost at the end of the semester, I believe we should stick to this original grading criteria.
