### ISSUE TITLE
[Homework 6] only all_hazards_protected test failed but sometimes success

### ISSUE THREAD

**Issue by JerrylzjTom** [kaist-cp/cs431#968]
When l was testing hazard_pointer with script, only the "all_hazards_protected" test failed, but it sometimes success. I have no idea how to fix the bug, I don't know if this is the problem of my environment. The follow is my environment:
OS: Ubuntu 22.04
rustc: 1.83.0-nightly

**Comment by Lee-Janggun** [comment]
If it sometimes fails, you probably have some synchronization bug that only happens from time to time.

Without more information the only tip I can give you is to use LLDB and think hard about the synchronization.
