### ISSUE TITLE
[Question] Resource/Advice for non-KAIST students?

### ISSUE THREAD

**Issue by stevebuildboats** [kaist-cp/cs431#969]
Hi CS431 Course Instructors,

This class has picked up lots of popularities among non-KAIST communities, especially due to its highly practical and open-sourced homework/projects, and public slides. I am also starting to follow the course materials and find them tremendously helpful for learning concurrent models and performant Rust programming. Big thanks to the course staff. 

My question pertains to the resources we may use as self-paced learners:
- Ways to access homework documentation and guidance on getting the solution auto-graded, or on a simpler level, instructions on important aspects on self-composing unit tests.
- community: maybe there can be a monitored chat channel for non-enrolled course takers to discuss the materials. Popular MooC like [CMU 15-445](https://15445.courses.cs.cmu.edu/fall2024/faq.html) for example has a [Discord](https://discord.com/invite/YF7dMCg) channel.
- and any other general directions the instructors may advise for non-KAIST-enrolled students.

Sincerely,

**Comment by Lee-Janggun** [comment]
Hi, thank you for the interest in the course. Regarding the questions...

* homework doc: I'm not sure what you want here, as the docs exists in the `homework` directory as markdown files. For autograding, we also have scripts for them, also documented. I'm really not sure on what you mean by "important aspects of self-composing unit tests".
  * If you have more specific questions on certain parts of the document or grading script, we can answer that.
* community: We intend for students (both from and outside) to use this github repo's issue tracker for questions. As a matter of fact, we had a few occasions where students outside of KAIST asked questions simply using github issues.
* other guidance: nothing special; as we don't have any aspects of this course that is KAIST-specific. If I mentioned above, if you have any questions, feel free to post them in the issue tracker.
