### ISSUE TITLE
[Question](A small word error in doc)

### ISSUE THREAD

**Issue by AdolfRyan** [kaist-cp/cs431#970]
(YOUR QUESTION HERE)
in homework/doc/linked_list.md,line 28.
the link should be https://doc.rust-lang.org/std/primitive.pointer.html instead of https://doc.rust-lang.org/std/primmitive.pointer.html.
(**primitive** instead of **primmitive**)

**Comment by Lee-Janggun** [comment]
The link is correct, I'm not sure where you are getting the incorrect line from.

https://github.com/kaist-cp/cs431/blob/a9ac6e62f1d0e73378490ccfa6aa436d39d5cdce/homework/doc/linked_list.md?plain=1#L28

**Comment by AdolfRyan** [comment]
my bad,sry
